### ISSUE TITLE
When I start a url and Smplayer is on the second monitor on the left, the interface is shifted to the right

### ISSUE THREAD

**Issue by Salvaju29ro** [smplayer-dev/smplayer#10]
**Describe the bug**
When I start a Youtube (or other) url and Smplayer is on the secondary monitor on the left, the interface is slightly shifted to the right
(the video, the menus above and the current playing time of the video)

**To Reproduce**
Ctrl + V, I open the link and it plays

**Your Enviroment**
 - SMPlayer version: 21.1.0 (revision 9475) (64-bit)
 - OS: Windows 10 Pro
 - Multimedia engine: MPV with  -aspect 16:9 option on Advanced - Mplayer/mpv - Option: (i tried also without the option)

**Logs**
[mpv log.log](https://github.com/smplayer-dev/smplayer/files/6164157/mpv.log.log)
[Smplayer log.log](https://github.com/smplayer-dev/smplayer/files/6164158/Smplayer.log.log)

Screenshot:

![Immagine 2021-03-18 133517](https://user-images.githubusercontent.com/10899871/111628348-6917cb80-87f0-11eb-96fa-aab943185100.png)
![Immagine 2021-03-18 134021](https://user-images.githubusercontent.com/10899871/111628358-6e751600-87f0-11eb-8708-cffa56b04639.png)
![Immagine 2021-03-18 135156](https://user-images.githubusercontent.com/10899871/111629015-2276a100-87f1-11eb-8fe6-f5187892dfb2.png)
![Immagine 2021-03-18 133734](https://user-images.githubusercontent.com/10899871/111628648-beec7380-87f0-11eb-86b6-10e597965cca.png)

In the first photo, you can see how the black space has doubled on the left, because the one on the right is not there. The video starts shifted to the right

In the second photo I click on the first item but it doesn't work, to click on the first option I have to click where you see the open menu

In the last photo you don't see the cursor, but I placed the cursor at the beginning and the minutes are seen much further to the right

**Comment by smplayer-dev** [comment]
This is very strange. Does it still happen if you select a different GUI or icon set in preferences -> interface?

**Comment by Salvaju29ro** [comment]
> This is very strange. Does it still happen if you select a different GUI or icon set in preferences -> interface?

The problem persists with the default theme and even with the PapirusDark theme (icons)
I tried to change the minimal interface and put the complete one and the problem persists
![Immagine 2021-03-19 174848](https://user-images.githubusercontent.com/10899871/111814968-66de6b80-88db-11eb-8352-9664720b75f9.png)

**Comment by smplayer-dev** [comment]
I'm afraid I can't reproduce this problem. Tested on Windows and Linux. The menus are shown in the correct place.

**Comment by Salvaju29ro** [comment]
> I'm afraid I can't reproduce this problem. Tested on Windows and Linux. The menus are shown in the correct place.

Thanks anyway
About the video, does it happen to you that it goes right?
However, the problem only occurs if the secondary monitor is on the left and the video starts on that monitor

On Linux I've never had this problem (I've been using it for months)

**Comment by smplayer-dev** [comment]
The video and the menus are in the correct position even when the screen is on the left.
Although if the menu doesn't fit on the screen it may be placed on an expected position.

**Comment by smplayer-dev** [comment]
Just in case, does it make a difference if you turn off "High DPI" in preferences -> interface?

**Comment by Salvaju29ro** [comment]
> Just in case, does it make a difference if you turn off "High DPI" in preferences -> interface?

Wow, It seems that the problem is not there with the Hidpi settings turned off (I set it to 1.1 when I turned them on)
I tried to start two identical videos
With settings enabled the problem is there, I tried to disable and restart smplayer and the problem is not there

**Comment by smplayer-dev** [comment]
Well, then the problem seems to be in the High DPI code in Qt. Maybe updating the Qt libs would fix the problem, since smplayer uses a quite old version. However I'm afraid I can't update them because smtube wouldn't work with newer versions.

**Comment by Salvaju29ro** [comment]
> Well, then the problem seems to be in the High DPI code in Qt. Maybe updating the Qt libs would fix the problem, since smplayer uses a quite old version. However I'm afraid I can't update them because smtube wouldn't work with newer versions.

If that's not possible, it doesn't matter
I don't have an exaggeratedly large screen, even without hidpi it's usable

**Comment by smplayer-dev** [comment]
I've just uploaded a package built with Qt 5.15.2. Could you test if it still has the same problem?

[smplayer-21.1.0.9503-x64.exe](https://sourceforge.net/projects/smplayer/files/SMPlayer/Development-builds/Qt%205.15.2/smplayer-21.1.0.9503-x64.exe/download)

**Comment by Salvaju29ro** [comment]
> I've just uploaded a package built with Qt 5.15.2. Could you test if it still has the same problem?
> 
> [smplayer-21.1.0.9503-x64.exe](https://sourceforge.net/projects/smplayer/files/SMPlayer/Development-builds/Qt%205.15.2/smplayer-21.1.0.9503-x64.exe/download)

I have activated the Hidpi in this edition and it seems that the problem is not there
I tried 4 or 5 videos from youtube

**Comment by MarkJeronimus** [comment]
I'm having the same (or similar symptoms) problem on Linux.

The controls at the bottom appear twice, and BOTH are functional(!). The video is moved up. When I don't maximize the window, the video can completely disappear. It looks like the bottom of the video follows the bottom of the window. It may appear that the video doesn't fill the entire width, but in fact it's zoomed to fit to the window top and bottom.

![image](https://user-images.githubusercontent.com/5273753/176283763-bbf58ef3-1c67-44f9-b0c0-c5ac17dbaef4.png)

My main monitor is left and is shifted down compared to the second monitor by 480px (none of the monitors start at (0,0)).

Everything worked fine in Ubuntu 18.04, but when I installed Mint 20.04 (kept my home directory and the same Unity window manager with same unity+gnome+compiz+smplayer settings afaict), the problem occurs when High DPI is enabled.
