### ISSUE TITLE
Wayland + MPV interpolation, video plays in "fast forward"

### ISSUE THREAD

**Issue by adolfotregosa** [smplayer-dev/smplayer#1017]
**Describe the bug**
Video plays in "fast forward". 

**To Reproduce**
make a smplayer config file with following:

video-sync=display-resample
interpolation-threshold=3
interpolation

**Expected behavior**
For it to work correctly like it does on X11.

**Screenshots**
Video is easier https://youtu.be/Yq6JhNszuiM

**Your Enviroment**
 - SMPlayer version: 24.5.0 (revision 10277)
 - OS: 
![image](https://github.com/user-attachments/assets/9215244b-4bb3-465a-93aa-9da2f1d416de)
![image](https://github.com/user-attachments/assets/6f8fea06-2d5a-4397-b5c2-6bf145a494f3)

 - Multimedia engine you're using with SMPlayer (preferences -> general):
 [ ] MPlayer
 [X ] MPV

**Logs**
[smplayer_log.txt](https://github.com/user-attachments/files/16354076/smplayer_log.txt)

**Additional context**
Same exact settings work perfectly if I use MPV by itself like I show on the video.

**Comment by smplayer-dev** [comment]
It seems to work fine if you select "gpu" or "gpu-next" as video output.

**Comment by adolfotregosa** [comment]
> It seems to work fine if you select "gpu" or "gpu-next" as video output.

Indeed. I'm positive I tried that in the past but indeed ATM it fixes the issue. Thank you.
