### ISSUE TITLE
Subtitle download: cannot change the title anymore

### ISSUE THREAD

**Issue by schusterro** [smplayer-dev/smplayer#1035]
**Describe the bug**
In the "Find Subtitles" dialog, the input field "Search for title" and it's "Search" button are greyed out and cannot be used anymore. This used to work. I have an old version, 19.10.0, which still uses "OpenSubtitles.org", and it works just fine there.

**To Reproduce**
1. Go to Subtitles ->Download subtitles from OpenSubtitles.com
2. Then there is the issue: the input field "Search for title" and its "Search" button are greyed out and cannot be used.

**Expected behavior**
The input field "Search for title" and its "Search" button should not be greyed out.

**Screenshots**

**Your Enviroment**
 - SMPlayer version: 24.5.0 (revision 10277) Flatpak. The same happens with 24.5.0-1 from the Manjaro extra repos.
 - OS: Manjaro KDE
 - Multimedia engine you're using with SMPlayer (preferences -> general):
 [ ] MPlayer
 [X] MPV

**Logs**
Reproduce the bug in your computer and attach the smplayer log (menu View) here.

**Additional context**

**Comment by smplayer-dev** [comment]
Click the "options" button in that dialog, as search method select "filename" or "hash and filename".

**Comment by schusterro** [comment]
Awesome, that was it! Thank you
