### ISSUE TITLE
Smaller volume display popup

### ISSUE THREAD

**Issue by IceBlizz6** [smplayer-dev/smplayer#1046]
The volume display that pops up when adjusting the sound is very large and distracting.
I got sensitive hearing so i tend to adjust the volume frequently.

I would like an option to either remove it or make it very small.

The display could have been a very simple icon or number at the corner of my screen.
I'm not entirely sure if there is anyone that needs such a large volume display at all, so maybe a smaller version could work as a replacement.

This is the display i'm referring to:
![image](https://github.com/user-attachments/assets/c4f2cc29-8422-45f4-a4a6-e45781e7024d)

**Comment by IceBlizz6** [comment]
Realized that there already is volume text in upper left corner.
So maybe option could just hide the horizontal volume bar then.

**Comment by smplayer-dev** [comment]
You can hide that bar selecting the option View -> OSD -> Subtitles only.

**Comment by IceBlizz6** [comment]
> You can hide that bar selecting the option View -> OSD -> Subtitles only.

Thank you, this solves my problem.
I overlooked this because i expected to find something like this under Options.
I looked through options several times.

**Comment by IceBlizz6** [comment]
After using it more i realize that i still want the volume number in the left corner, but without the bar.
Selecting "Subtitles only" it removes both the bar and the volume number.
I hope you won't mind that i resurrect this issue.

**Comment by smplayer-dev** [comment]
Add this to preferences -> advanced -> mplayer/mpv -> options:
`--osd-bar=no`

**Comment by IceBlizz6** [comment]
Yes, this seems to work well.
Think it could have been an actual setting in the UI instead of command line arg, but i'll close this.
