### ISSUE TITLE
Can't really exit SMPlayer. It just minimizes to the system tray icons. Each new SMP intance adds to the pile.

### ISSUE THREAD

**Issue by Crowcore** [smplayer-dev/smplayer#106]
**Describe the bug**
Can't **really** exit SMPlayer. It just goes to the system tray icons. An additional one with each closing. So after a few hours, it gets busy down there (cf. screenshot). This started a few days ago.

**Expected behavior**
I expect the software to close and not minimize to the system tray. 

**Screenshots**
![Screenshot 2021-06-03 084918z](https://user-images.githubusercontent.com/85258451/120600127-b21f0980-c448-11eb-8a10-d31d001c2c92.jpg)

**Your Enviroment**
 - SMPlayer version: 20.6.0 (revision 9418)
 - OS: Windows 10 64 bits
 - Multimedia engine you're using with SMPlayer (preferences -> general):
 [ ] MPlayer
 [x ] MPV

**Comment by smplayer-dev** [comment]
Be sure the option "Show icon in system tray" under the "Options" menu is not enabled.

**Comment by Crowcore** [comment]
Thank you, that solved it.
