### ISSUE TITLE
"--keep-open" + "Remember time position" makes UI Unresponsive

### ISSUE THREAD

**Issue by roninpawn** [smplayer-dev/smplayer#1072]
**Describe the bug**
I've added the `--keep-open` flag to MPV's settings under `Settings > Advanced > MPlayer /mpv > Options`, as reported in #1071 . When I first added that flag, I'd already been using the app for a few weeks with the `Settings > General > General > Remember settings for all files > Remember time position` option on. So smplayer had already stored per-file timestamps for a lot of media. Somehow, this caused some of the videos that I'd watched completely through, to break smplayer's UI.

Because `--keep-open` was now set, the videos I'd watched all the way through opened on the last frame, displaying nothing but black. But once I figured out that the files needed to be manually rewound, I still couldn't rewind them. Clicking/dragging the playback bar didn't move the playhead; Nor did the arrow keys on the keyboard. And it took me quite a while to figure out that just one of the input methods still worked: The mouse scroll wheel.

With the scroll wheel, I _could_ move the playhead, and once I'd broken it free using the scroll wheel, all the other methods worked again, too.

**To Reproduce**
I just found a file that still has the issue, and I'm not fixing it... That way I can send whatever info you ask for. Just let me know. I'm not 100% sure how to _create_ the issue from scratch, and I don't want to experiment with recreating it, and maybe lose the proof I already have in the form of this MP4 that isn't opening right.

That said, this is my best guess at how you _create_ the bug from scratch:
1. Playback an MP4 to its end with `Remember time position` set to true, but before adding the `--keep-open` flag to your MPV settings.
2. Close smplayer after the playback has fully ended.
3. Reopen smplayer, but DO NOT open the MP4 you've just setup, yet.
4. Add `--keep-open` to the MPV options.
5. Restart smplayer and reopen that MP4.
6. Click play/spacebar; Try to drag the playhead; Try to move the cursor with left/right keys. None should work.
7. Mouse scrollwheel down. That should work to rewind the playhead a little.
8. Now re-check everything from step 6. It should all work now.

**Expected behavior**
Refer to #1071 for how I think `--keep-open`, support can be handled with one simple rule... But at the least, all files should be fully navigable by all UI elements and inputs, regardless of changes to settings.

**Your Enviroment**
 - SMPlayer version: 24.25.0 (10277)
 - OS: Windows 10 (1803) 
 - Multimedia engine you're using with SMPlayer (preferences -> general):
 [ ] MPlayer
 [X ] MPV

**Additional context**
The clickable UI AND the keys being unresponsive BUT mouse-wheel working, is hyper-specific. I'd be curious to see what the difference is between what `Remember time position` stores as its EOF when it's in `--keep-open` mode, and when it's not. Whatever the difference is, it really threw the UI for a loop!

**Comment by roninpawn** [comment]
So, in fact, even after you rewind with the scroll wheel the UI elements remain locked. It's PLAYING the video that unlocks them. You have to rewind, hit play, and THEN the UI elements start working.

**Comment by smplayer-dev** [comment]
I think this has been fixed in the latest commit.

**Comment by roninpawn** [comment]
Just pulled your latest build for x64 and flipped `--keep-open` off and on, and it looks to fix it.

Neat little trick, if I get what's changed! The time being remembered isn't the actual last frame anymore, but a bit before it. Maybe its the last keyframe before EOF? Or just an offset?

Anyway, starting on a valid frame _before_ the media has ended allows the player to actually do a little playback. And since it's the _playing_ of the media that triggers all the UI elements to update, this ensures the playhead gets moved, the playback bar gets filled, and all navigation elements and hotkeys are active.

Clever!
