### ISSUE TITLE
Use Esc as keyboard shortcut?

### ISSUE THREAD

**Issue by paul1149** [smplayer-dev/smplayer#1089]
I'd like to use the single key, `ESC`, to close SMPlayer.  I find this key easy to find and reach.

But specifying it to close SMP brings the error "ambiguous shortcut, will not be executed".

Is there a way that `ESC` could be supported as a shortcut?

I'm on 24.5.0, on MX Linux.

Thanks.

**Comment by smplayer-dev** [comment]
The `ESC` key is probably already assigned to another action. It's not possible to use the same key for two actions. So you have to change the shortcut of the original `ESC` action.

**Comment by paul1149** [comment]
Ah, exactly right. I assumed assigning it to a new function would supersede its old assignment (exit fullscreen), but that is not the case. Thanks very much.
