### ISSUE TITLE
openSUSE Factory build failes

### ISSUE THREAD

**Issue by DAP-DarkneSS** [smplayer-dev/smplayer#109]
**Describe the bug**
mongoose.c:1110:33: error: argument 1 of type 'unsigned char[16]' with mismatched bound [-Werror=array-parameter=]

**To Reproduce**
`make`

**Expected behavior**
Successful build.

**Screenshots**

**Your Enviroment**
 - SMPlayer version: 21.1.0
 - OS: openSUSE Factory
 - Multimedia engine you're using with SMPlayer (preferences -> general):
 [ ] MPlayer
 [*] MPV

**Logs**
[   26s] + make 'MAKEFLAGS=-j6 V=1' QMAKE=/usr/lib64/qt5/bin/qmake LRELEASE=/usr/lib64/qt5/bin/lrelease PREFIX=/usr
[   26s] ./get_svn_revision.sh
[   26s] cd webserver && make
[   26s] make[1]: Entering directory '/home/abuild/rpmbuild/BUILD/smplayer-21.1.0/webserver'
[   26s] cc main.c mongoose.c -o simple_web_server -O2 -W -Wall -Werror -Wno-unused-function  -DMG_DISABLE_DAV_AUTH -DMG_ENABLE_HTTP_CGI=0 -DMG_ENABLE_THREADS=0 -DMG_ENABLE_HTTP_SSI=0 -pthread
[   26s] cd src && /usr/lib64/qt5/bin/qmake  && DATA_PATH=\\\"/usr/share/smplayer\\\" TRANSLATION_PATH=\\\"/usr/share/smplayer/translations\\\" DOC_PATH=\\\"/usr/share/doc/packages/smplayer\\\" THEMES_PATH=\\\"/usr/share/smplayer/themes\\\" SHORTCUTS_PATH=\\\"/usr/share/smplayer/shortcuts\\\" make -j6 V=1
[   26s] Info: creating stash file /home/abuild/rpmbuild/BUILD/smplayer-21.1.0/src/.qmake.stash
[   26s] Project MESSAGE: This project is using private headers and will therefore be tied to this specific Qt module build version.
[   26s] Project MESSAGE: Running this project against other versions of the Qt modules may crash at any arbitrary point.
[   26s] Project MESSAGE: This is not a bug, but a result of using Qt internals. You have been warned!
[   26s] mongoose.c:1110:33: error: argument 1 of type 'unsigned char[16]' with mismatched bound [-Werror=array-parameter=]

**Additional context**
gcc11, Qt 5.15.2.

**Comment by smplayer-dev** [comment]
I think this is already fixed: https://github.com/smplayer-dev/smplayer/pull/73/commits/4aa67eac23b0f397c4d4fcc953e739d7c707aad1

**Comment by DAP-DarkneSS** [comment]
Thanks you very much!
