### ISSUE TITLE
On many skins the play etc. buttons are jagged

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [smplayer-dev/smplayer#11]
**Describe the bug**

Many of the skins, in combination with many of the 'styles', make the play, pause, etc. buttons have an unpleasing jaggedness. A give a screenshot, below, of the problem as it manifests itself when I usie the 'black' theme with the 'fusion' style.

**To Reproduce**

I am using Windows; I have not checked to see whether the problem exists on other operating systems. For the settings I am using, please see my text above  and one of the screenshots below.

**Expected behavior**
Less jaggedness!

**Screenshots**

![image](https://user-images.githubusercontent.com/47056543/111810932-71463880-88ce-11eb-968e-b1aa746dc584.png)

![image](https://user-images.githubusercontent.com/47056543/111810987-80c58180-88ce-11eb-8bea-06283f8b6513.png)

**Your Enviroment**
 - SMPlayer version: 21.1.0
 - OS: Windows 10
 - Multimedia engine you're using with SMPlayer (preferences -> general):
 [ ] MPlayer
 [X ] MPV

**Logs**
Not relevant?

**Additional context**

Thank you for your wonderful software.

**Comment by smplayer-dev** [comment]
I'm afraid I can't reproduce this problem. In my computer it looks fine:

![control](https://user-images.githubusercontent.com/10128951/112472522-85c27f00-8d6d-11eb-8243-cd8dd3598b1e.png)

If the High DPI option is enabled, try disabling it (Preferences -> Interface -> High DPI).

**Comment by LinuxOnTheDesktop** [comment]
Thanks. Yet, and once again: (1) that is a potential workaround and not a bug fix; (2) the display is not Hi-DPI and I did not have your application's Hi-DPI setting enabled.

**Comment by smplayer-dev** [comment]
Could you test if this version works better for you?

https://sourceforge.net/projects/smplayer/files/SMPlayer/Development-builds/Qt%205.15.2/smplayer-21.1.0.9503-x64.exe/download

**Comment by LinuxOnTheDesktop** [comment]
I replied to the wrong issue. I think you did too. For, that build does not seem to diminish the jaggedness, but it helps with - though does not solve - the 'lurching problem' (which is #18, and where I've given more information about the behaviour of the new build).

**Comment by LinuxOnTheDesktop** [comment]
Why is this issue closed? The problem has not been solved.

**Comment by smplayer-dev** [comment]
Because I can't reproduce the problem. If I can't reproduce it I can't fix it. I can't see this problem on any computer I tested.

**Comment by smplayer-dev** [comment]
I could reproduce the problem when setting HDPI scaling to 1.4 or so. But I'm afraid I can't fix it because the scaling is done by the Qt library. You have to turn off HDPI scaling or set it to 2x or similar.

**Comment by LinuxOnTheDesktop** [comment]
Right. Thank you for investigating. Should I close this issue, then? I note that this problem forced me to move to another player.

Incidentally, installing a test version allows the following, slightly confusing message to appear:

![image](https://user-images.githubusercontent.com/47056543/116885374-b8d71880-ac1f-11eb-816d-a4899fb8f928.png)
