### ISSUE TITLE
error insert from youtube playlist

### ISSUE THREAD

**Issue by wasya2009** [smplayer-dev/smplayer#12]
v.21.1.0
message:
Error transfering https://youtube.com/list_ajax?
action_get_list=1&style=xml&list=.............(link)
server replied: Not Found

**Comment by smplayer-dev** [comment]
I think this issue was already fixed in the development version.

https://github.com/smplayer-dev/smplayer/commit/e49712fa46108e6f0cf88802d684d176b8829680
