### ISSUE TITLE
smplayer not support "-start" parameter

### ISSUE THREAD

**Issue by luckrill** [smplayer-dev/smplayer#127]
From help info
smplayer support "-start" parameter
smplayer -start x or x:x or x:x:x video

but in linux(debian) or windows10
smplayer not support "-start" parameter

hope check this '-start' issue.

**Comment by smplayer-dev** [comment]
What version are you using? 
I've just tested it and it works for me (linux).

**Comment by luckrill** [comment]
check version: new version support "-start" parameter

no support "-start" version is: 0.5.21

**Comment by smplayer-dev** [comment]
The `-start` option was added in version 19.5.
