### ISSUE TITLE
Is possible configure default aspect ratio for all videos ?

### ISSUE THREAD

**Issue by Augusto7743** [smplayer-dev/smplayer#129]
In menu Video \ Aspect Ratio is possible select 16:9 , but for next videos aspect ratio return to default setting.
Even selecting in Options \ Preferences \ Advanced monitor aspect 16:9 video aspect ratio return to default when playing next video or closing SMPlayer.

How configure aspect ratio 16:9 to all files ?

Thanks for your reply.

**Comment by smplayer-dev** [comment]
Go to preferences -> advanced, type this in the option to run actions when a file is opened:
`aspect_16:9`
