### ISSUE TITLE
Radio tracks not updating

### ISSUE THREAD

**Issue by ghost** [smplayer-dev/smplayer#13]
ahhh never mind

**Comment by ReaLJohnBaker** [comment]
Also a nice feature of VLC not only does it have no problems with track changes but also gives me a nice tray icon notification after each new song > https://i.postimg.cc/yWCzGzSY/2.png

**Comment by ReaLJohnBaker** [comment]
As I continue using smplayer for the first time today I found another issue:
While I'm playing a song it will stop if I press X and send smplayer to the tray.
