### ISSUE TITLE
Repo confusion

### ISSUE THREAD

**Issue by dandv** [smplayer-dev/smplayer#14]
Hi, I'm a little confused about the source code for SMPlayer. I've been using it on Linux for many years, but this repo's description says "Windows":

![image](https://user-images.githubusercontent.com/33569/112055243-b058d180-8afa-11eb-9c8d-2f51354d544d.png)

Also, the instructions at https://www.smplayer.info/en/downloads say to use `svn`. Isn't this a GitHub repo?

Finally, which is the source of truth for the code, SourceForge, or GitHub?

(I would obviously prefer moving to GitHub, as most projects have).

**Comment by smplayer-dev** [comment]
From now on the sources will be here, on GitHub. 
You can of course use git to get the sources but the script `create_deb.sh` still expects a svn repository to work correctly.
I've just fixed the repo's description.
