### ISSUE TITLE
During the installation youtube-dl can not be installed

### ISSUE THREAD

**Issue by sculpordwarfsuntea** [smplayer-dev/smplayer#142]
**Describe the bug**
I have freshly installed Windows 11 on my computer. After the first start I tried to install SMPlayer offline. It did not work. It always comes this message and I have clicked Retry several times.

**To Reproduce**
1. https://github.com/smplayer-dev/smplayer/releases/tag/v21.1.0.9805
2. Install smplayer-21.1.0.9805-x64.exe
3. youtube-dl was not successfully installed. Retry?

**Expected behavior**
I have been using Windows since Windows XP and most of the software I have tested could always be successfully installed offline with .exe file.
This should also work with SMPlayer .exe file, so that the user can install everything offline with .exe file. That means in this case youtube-dl should be able to be installed offline.

**Screenshots**
![Image](https://user-images.githubusercontent.com/87533680/125959155-2efc164f-0e75-4ef0-a691-507739accf41.PNG)

**Your Enviroment**
 - SMPlayer version: 21.1.0.9805
 - OS: Windows 11
 - Multimedia engine you're using with SMPlayer (preferences -> general):
 [ ] MPlayer
 [ ] MPV

**Logs**
N/A

**Additional context**

**Comment by smplayer-dev** [comment]
Maybe you can use the portable version. It won't try to download anything.

**Comment by sculpordwarfsuntea** [comment]
> 
> 
> Maybe you can use the portable version. It won't try to download anything.

Thanks for the answer. But I do not use the portable version.

Is it possible that you integrate youtube-dl and additionally offer the possibility to check for update for youtube-dl during the installation. So the user can decide if he wants to install offline or some specific extensions to check for update.
You could integrate in page 1 during installation an .exe file so checkbox, the user selects whether he wants to check youtube-dl for update or download.

There should be no pop-up window, because it is user-unfriendly. An installation for users should be possible with a few clicks and without a pop-up window.

**Comment by smplayer-dev** [comment]
The development version already has an option to turn off the installation of youtube-dl, so I think the problem is solved.

**Comment by sculpordwarfsuntea** [comment]
> 
> 
> The development version already has an option to turn off the installation of youtube-dl, so I think the problem is solved.

I see what you mean now. The user must disable Youtube support.

![Screenshot 2021-07-19 151937](https://user-images.githubusercontent.com/87533680/126166187-26e8810a-18fa-4ee8-84b6-80b458ec7253.png)

Would it be possible to improve this using this text?

Youtube support (download required)

**Comment by smplayer-dev** [comment]
Sure. I've just changed it.

**Comment by sculpordwarfsuntea** [comment]
> 
> 
> Sure. I've just changed it.

https://github.com/smplayer-dev/smplayer/commit/3ea146ba45c666d574ef2417557d7e76fc79e6a7

Thank you.
