### ISSUE TITLE
No audio when advancing or rewinding with a stream

### ISSUE THREAD

**Issue by Salvaju29ro** [smplayer-dev/smplayer#146]
Hello, I have this problem on Arch Linux for some time and, using Smplayer also on Windows, I realized that the problem is not there

I think that the problem is related to Mpv 0.33, on Windows there is still version 0.32
Basically when I am watching a video on youtube and I go forward or go back with the minutes, for a few seconds the audio is not there, but this only when the "Use adaptive streams (resolution up to 4k)" setting is enabled
If it is disabled, there is no such problem

**Your Enviroment**
 - SMPlayer version: 21.1.0 on Linux, 1.1.0.9503-x64 on Windows (Special" version with updated qt that a developer gave me due to [this problem ](https://github.com/smplayer-dev/smplayer/issues/10) )
 - OS: Arch Linux 64 bit; Windows 10 64 21h1
 - Multimedia engine you're using with SMPlayer (preferences -> general): MPV

**Logs**

[Mpv log with the "use adaptive" setting **deactivated**](https://github.com/smplayer-dev/smplayer/files/6836084/Mpv.log.log)

[Smplayer logs.with the "use adaptive" setting **deactivated**](https://github.com/smplayer-dev/smplayer/files/6836087/Smplayer.logs.log)

[Mpv log with the "use adaptive" setting **activated**](https://github.com/smplayer-dev/smplayer/files/6836088/Mpv.log.log)

[Smplayer logs with the "use adaptive" setting **activated**](https://github.com/smplayer-dev/smplayer/files/6836089/Smplayer.logs.log)

**Comment by smplayer-dev** [comment]
I don't know if it's a bug in mpv 0.33 but I think it can be solved by selecting "mpv + youtube-dl" in preferences -> network.
Edit: I think it can also be solved enabling the option "precise seeking" in preferences -> interface -> seeking.

**Comment by Salvaju29ro** [comment]
> I don't know if it's a bug in mpv 0.33 but I think it can be solved by selecting "mpv + youtube-dl" in preferences -> network.
> Edit: I think it can also be solved enabling the option "precise seeking" in preferences -> interface -> seeking.

In fact it seems work
