### ISSUE TITLE
Misfunctioning

### ISSUE THREAD

**Issue by srezasm** [smplayer-dev/smplayer#151]
It's completely misfunctioning on the latest version of Ubuntu 21.04.
However, it is fine on Ubuntu 20.04 LTS.
Like plenty of keyboard shortcuts not working, with every right-click screen goes black, secondary subtitle track option is disabled and application performance is so bad, etc.

> Ubuntu 21.04, SMPlayer v. 21.1.0 (revision 9475)

**Comment by smplayer-dev** [comment]
Be sure mpv is installed and select it in preferences -> general -> multimedia engine.

**Comment by srezasm** [comment]
@smplayer-dev Thank you!
