### ISSUE TITLE
ResampleDemo.dll not found

### ISSUE THREAD

**Issue by iqsoft** [smplayer-dev/smplayer#156]
Error opening smplayer. 
"The code execution cannot proceed because ResampleDemo.dll was not found...."

**Comment by smplayer-dev** [comment]
smplayer doesn't use that library 😕

**Comment by iqsoft** [comment]
Then why the error?

**Comment by smplayer-dev** [comment]
I don't know. Where did you get smplayer?

**Comment by smplayer-dev** [comment]
I can only find this:
https://community.spotify.com/t5/Desktop-Windows/Spotify-Gives-Error-The-code-execution-can-not-proceed/m-p/5047113

**Comment by iqsoft** [comment]
> I don't know. Where did you get smplayer?

From here...
https://www.dll-files.com/resampledmo.dll.html

**Comment by iqsoft** [comment]
> I can only find this:
> https://community.spotify.com/t5/Desktop-Windows/Spotify-Gives-Error-The-code-execution-can-not-proceed/m-p/5047113

thanks. let me try downloading media feature pack.
