### ISSUE TITLE
Power saving mode.

### ISSUE THREAD

**Issue by sephid86** [smplayer-dev/smplayer#173]
Hello.

First of all, thank you for making smplayer.

It's a great program.

I am using smplayer on Debian.

However, there is one very inconvenient thing that I am writing here.

It turns off the screen when the time promised in the system settings is reached.

Power saving mode.

I sincerely hope.
Hopefully this will be fixed in the next version

thank you.

Debian 11 bullseye
Gnome 3.38
SMPlayer 21.1.09475

**Comment by smplayer-dev** [comment]
I think I already fixed this.
Could you test if the problem is still present in the development version?
https://github.com/smplayer-dev/smplayer/releases/tag/v21.1.0.9864

**Comment by sephid86** [comment]
I tested it with the release you mentioned. (v21.1.0.9864)

The results were very good.

Thank you very much.

As an aside, I'm not a big fan of qt.

But smplayer is a really great program that is absolutely the best.

Until I made a video player program using gtk. (joke)

Thank you again.

**Comment by sephid86** [comment]
> I think I already fixed this.
> Could you test if the problem is still present in the development version?
> https://github.com/smplayer-dev/smplayer/releases/tag/v21.1.0.9864

I tested it with the release you mentioned. (v21.1.0.9864)

The results were very good.

Thank you very much.

As an aside, I'm not a big fan of qt.

But smplayer is a really great program that is absolutely the best.

Until I made a video player program using gtk. (joke)

Thank you again.
