### ISSUE TITLE
paused video plays again in background after going to desktop

### ISSUE THREAD

**Issue by 0lm** [smplayer-dev/smplayer#179]
**Describe the bug**
"Pause when minimized" is enabled. I minimize Windows and Video pauses. Then I click the "Go to Desktop" button on the right bottom corner next to notification symbol. That causes everything to be minimized. I maximized browser and I hear the Video sound. So, the video is still minimized, but it starts to play again when you maximized another window, after you "went to desptpn instantlxy" withthe help of the button in the right bottom corner. This doesnt happen in 21.1

**To Reproduce**
1. Enable Pause when minimized.
2. Minimize Video, it should pause
3. Go instatly to dekstop with button in the right bottom corner 
4. Open another Window (double click a folder on your desktop. or maximized a minimized Browser or whatever)
5. video gets active and starts to play again (this bug didnt exist in smplayer v21.1)

**Expected behavior**
keep video paused, like in v21.1

**Your Enviroment**
 - SMPlayer version: 21.8
 - OS: Windows 10
 - Multimedia engine you're using with SMPlayer (preferences -> general): (doesnt matter, bug is in both)
 [ X ] MPlayer
 [ X ] MPV

**Comment by smplayer-dev** [comment]
I don't have a desktop button in the right bottom corner, but right clicking on the task bar and then on "show the desktop" works as expected for me, the video is still on pause.

**Comment by 0lm** [comment]
> 
> 
> I don't have a desktop button in the right bottom corner, but right clicking on the task bar and then on "show the desktop" works as expected for me, the video is still on pause.

Thanks for your answer. Did you also do Step 4? The 4th step (which is the key here) is the one causing the video to play again, and not the act of solely going to desktop. Basically, when your video is running, and you go to "Show desktop" (then your video should be paused), - but: then you open another folder or something else, while the video is still minimized because you went did "show desktop", it should start to play. The act of opening something else, while the video was minimized because of "show the desktop" (or the button on the right corner, both options doing the same) makes the video pause fail. This bug is in v21.8, but not in v21.1. Windows 10, 64bit

**Comment by smplayer-dev** [comment]
Ok, I was able to reproduce it now.
I guess this is a bug in Qt. It doesn't happen with the [version compiled with the old Qt 5.6](https://github.com/smplayer-dev/smplayer/releases/download/v21.8.0/smplayer-21.8.0-win32-qt5.6.exe).

**Comment by 0lm** [comment]
Thanks for the Info! I will use the newest pre-release x64 qt5.6 for now then. (unfortunately I couldn't find x64 qt5.6 for stable release, only x32 ist there)
