### ISSUE TITLE
On Windows, window snapping misfires

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [smplayer-dev/smplayer#18]
**Describe the bug**

See the section immediately below.

**To Reproduce**

1. Load the player and a file.
2. Snap the player to the left of the screen and another window to the right.
3. Start playing the media.
4. Press 'stop'.
5. Wait a second.
6. Press 'play'.
7. See what happens to the snapping - the player window lurches to a new position.

**Expected behavior**
No lurching.

**Screenshots**

After step 4:
![image](https://user-images.githubusercontent.com/47056543/112323348-9dd0ca80-8ca9-11eb-815b-0d553c2bfc37.png)

After step 6:
![image](https://user-images.githubusercontent.com/47056543/112323702-f1431880-8ca9-11eb-9ca7-1ab8fec91f6c.png)

**Your Enviroment**
 - SMPlayer version: 21.1.0
 - OS: Windows 10
 - Multimedia engine you're using with SMPlayer (preferences -> general):
 [ ] MPlayer
 [X ] MPV

**Logs**
Not relevant?

**Comment by smplayer-dev** [comment]
I'm afraid I can't reproduce this problem.

**Comment by LinuxOnTheDesktop** [comment]
Thanks for the attention. Is there someone else who might see whether she or he can reproduce the problem? (Also, I tried to reproduce the problem, myself, _but_ on Linux Mint Cinnamon as against Windows, and unsurprisingly I could not.)

**Comment by LinuxOnTheDesktop** [comment]
[Here (on Box)](https://app.box.com/s/aes3c2hbxe7kxhwvsjhjp6r3e3niypse) is a video of the problem.

**Comment by LinuxOnTheDesktop** [comment]
smplayer-dev: have you enabled the player's HPDI option? I have not. Also: pausing-and-unpausing does not cause the problem, so that's a clue for you to investigate.

**Comment by smplayer-dev** [comment]
Is the option to stay on top enabled?
If so try disabling it.

**Comment by LinuxOnTheDesktop** [comment]
I don't know whether that Smplayer option (it _is_ an smplayer option, yes?); where is it? Also: surely, at least by design, that option should not cause the behaviour at issue.

**Comment by smplayer-dev** [comment]
Menu Video -> Stay on top. That option has caused problems in the past, so be sure it's disabled.

**Comment by LinuxOnTheDesktop** [comment]
Thanks. That option is currently set to 'off'.

**Comment by LinuxOnTheDesktop** [comment]
The new build (see #11) diminishes the gap that appears between the snapped versions. It does not eliminate the gap. Screenshot of what happens, with the new build, at step 7: 

![image](https://user-images.githubusercontent.com/47056543/112544731-4b79d180-8daf-11eb-9789-e1e89592e27e.png)

There is of course an irony here in the title of the podcast!

**Comment by LinuxOnTheDesktop** [comment]
Why is this issue closed? The problem has not been solved.

**Comment by smplayer-dev** [comment]
Because I can't reproduce it. If I can't reproduce it there's no way I can't fix it. If anyone else has this problem and can find a solution I will apply the patch. Until then, the issue is closed.
