### ISSUE TITLE
Play/Pause when moving window

### ISSUE THREAD

**Issue by ThomasSeeker** [smplayer-dev/smplayer#184]
**Describe the bug**

I have Grab&Drag activated and since recently Play/Pause gets triggered, when moving the player-window by left-clicking on the screen and moving it.

I believe this started with the last update.

**Your Enviroment**
 - SMPlayer version: 21.8.0 (Revision 9887)
 - OS: Linux Mint

**Comment by smplayer-dev** [comment]
I'm afraid I can't reproduce this problem. I don't have Linux Mint but I tested on other distros (Ubuntu, Fedora, Manjaro), it works fine for me.

**Comment by ThomasSeeker** [comment]
I tried it with a fresh Kubuntu-Install and here to: Not reproducible!
Strange!

Thank you for you effort!
