### ISSUE TITLE
screenshot fails when backend is mpv and is playing an video from smtube (youtube) 

### ISSUE THREAD

**Issue by sergiomb2** [smplayer-dev/smplayer#188]
**Describe the bug**
screenshot fails when backend is mpv and is playing an video from smtube (youtube) 
screenshot works when backend is mpv and is playing an file from filesystem mp4
screenshot works when backend is mplayer and is playing an video from smtube (youtube) 

**To Reproduce**

4. OSD  show an message "error writing a screenshot !"

**Expected behavior**

**Screenshots**

**Your Enviroment**
 - SMPlayer version:
 - OS: Fedora 33
 

**Logs**

```
Error opening '/home/sergio/smplayer_screenshots/cap_videoplayback?expire=1630437328&ei=cCsuYeaHL5CTmLAP4Yi2qAo&ip=2001%3A8a0%3Aff08%3A1700%3A243c%3Ae00c%3A1101%3Ab53b&id=o-AGI57lGC6Cn-G92yR5TzHpFUf9B45yeKyqiYeCLX92kS&itag=247&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C278%2C313%2C394%2C395%2C396%2C397%2C398%2C399%2C400%2C401&source=youtube&requiressl=yes&mh=QM&mm=31%2C29&mn=sn-2vgu0b5auxaxjvh-v2vd%2Csn-apn7en7l&ms=au%2Crdu&mv=m&mvi=7&pl=42&initcwndbps=1493750&vprv=1&mime=video%2Fwebm&ns=SRtsu29QPtx9q4nEXU3dzKgG&gir=yes&clen=29836665&dur=225_00:00:10_01.jpg' for writing!
Error writing screenshot!
```

**Additional context**

**Comment by smplayer-dev** [comment]
Maybe because the filename is too large or something. You can change the screenshot template to use something else than the filename, in preferences -> general. Replace the `%F` with something else or delete it.
https://mpv.io/manual/stable/#options-screenshot-template
