### ISSUE TITLE
Add support for yt-dlp instead of/alongside youtube-dl. 

### ISSUE THREAD

**Issue by corvus1** [smplayer-dev/smplayer#191]
https://github.com/yt-dlp/yt-dlp is a fork of youtube-dl, and they maintain compatibility, so the change should be trivial. 

It has many improvements, such as importing cookies from browser and working with age-restricted videos.

**Comment by smplayer-dev** [comment]
It doesn't work on my computer.

```
./yt-dlp 
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./yt-dlp/__main__.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1139, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1115, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1096, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 533, in spec_from_file_location
  File "./yt-dlp/yt_dlp/__init__.py", line 4
    f'You are using an unsupported version of Python. Only Python versions 3.6 and above are supported by yt-dlp'  # noqa: F541
                                                                                                                ^
SyntaxError: invalid syntax
```

**Comment by corvus1** [comment]
Well, it says it needs python3.6 at the minimum. I'm currently running python3.9

**Comment by corvus1** [comment]
I just looked it up, python3.5 that you're using EOLed 11 months ago. In a week it'll be 12 months. :-D

**Comment by smplayer-dev** [comment]
Well, the original youtube-dl still works even with python2...

Anyway, I installed python 3.8 from the snap store and now I can test yt-dlp. It seems to work with smplayer without changes. There are two ways to use it:

Easy one:
- Download yt-dlp and save it to ~/bin as youtube-dl.

A little more complicated:
- Edit smplayer.ini, look for streaming\youtube\ytdl_bin and set the full path to yt-dlp.

**Comment by corvus1** [comment]
So I edited the smplayer.ini:
`streaming\youtube\ytdl_bin=/usr/bin/yt-dlp`

then I uninstalled youtube-dl, and I'm getting this:
```
[ytdl_hook]  
[ytdl_hook] youtube-dl failed: not found or not enough permissions 
Failed to recognize file format.
Exiting... (Errors when loading file)
```

So, apparently, smplayer is still trying to call youtube-dl. What am I doing wrong?

**Comment by smplayer-dev** [comment]
If you configured smplayer to use "mpv + youtube-dl" in preferences -> network, then you need to pass mpv the path of yt-dlp, adding this option to preferences -> advanced -> mplayer/mpv:

`--script-opts=ytdl_hook-ytdl_path=/usr/bin/yt-dlp`

(requires mpv >= 0.33)

**Comment by corvus1** [comment]
That worked for a singular video, but it doesn't work for playlists. Smplayer still needs youtube-dl installed to extract playlist from youtube. Is there anything else that I could do?

**Comment by smplayer-dev** [comment]
You're right. I'll try to fix it.

**Comment by smplayer-dev** [comment]
I think the playlist problem is fixed now.
Also now it's not necessary to pass the option `--script-opts` to mpv, smplayer will do it automatically.
And it's not necessary to pass the full path in the ytdl_bin option. `streaming\youtube\ytdl_bin=yt-dlp` should be enough.

**Comment by corvus1** [comment]
I just built smplayer from git, it all seems to work just like you said. :-) Closing the issue. Thank you.
