### ISSUE TITLE
not found CancelioEx in Kernel32.dll

### ISSUE THREAD

**Issue by Grzespp** [smplayer-dev/smplayer#203]
I have problem after "fresh" installation smplayer. I have error about "Procedure exit point not found CancelioEx in library Kernel32.dll" 

1. Click on 'smplayer.exe'
2. See error

Everything worked in the earlier version. I'm not very advanced in "programing" so idk what should I do. I replace KERNEL32.dll from cd boot drive but it didn't works :(. I don't have any ideas

![241397726_600739704416440_4244151881037265302_n](https://user-images.githubusercontent.com/88378592/132124836-a432333c-c801-4956-94bc-ff91cab4572f.jpg)

**Your Enviroment**
 - SMPlayer version: 21.8.0
 - OS: Windows XP
 - Multimedia engine you're using with SMPlayer :
 + MPlayer (I used it before crash)

**Logs**
I do not have access

My laptop (T30 IBM)
CPU : Pentium 4 mobile 1.9 GHz
GPU : ATI Mobilty Radeon 7500 with 16 mb ram
Ram : 512 MB

It's my first reported problem on this platform so idk if I did everything right.

**Comment by smplayer-dev** [comment]
Well, according to [this](https://bugreports.qt.io/browse/QTBUG-58407) it seems the Qt library (which SMPlayer uses) doesn't support Windows XP from version 5.8 (SMPlayer 21.8 is using 5.15). 
I guess you can still use [version 21.1](https://sourceforge.net/projects/smplayer/files/SMPlayer/21.1.0/), which uses Qt 5.6.

**Comment by Grzespp** [comment]
oki thx for info ^^

**Comment by smplayer-dev** [comment]
I'll try to build version 21.8 with Qt 5.6.

**Comment by smplayer-dev** [comment]
I've just uploaded a package built with Qt 5.6. Please let me know if it really works on Windows XP:
https://sourceforge.net/projects/smplayer/files/SMPlayer/21.8.0/smplayer-21.8.0-win32-qt5.6.exe/download

**Comment by Grzespp** [comment]
Sorry, I miss your e-mail. I will install your uploaded version. I let you know how it works^^Have a nice dayWysłano z telefonu-------- Oryginalna wiadomość --------Od: Ricardo ***@***.***>Data: niedz., 5 wrz 2021, 17:06Do: smplayer-dev/smplayer ***@***.***>DW: Grzespp ***@***.***>, State change ***@***.***>Temat: Re: [smplayer-dev/smplayer] not found CancelioEx in Kernel32.dll (#203)
I've just uploaded a package built with Qt 5.6. Please let me know if it really works on Windows XP:
https://sourceforge.net/projects/smplayer/files/SMPlayer/21.8.0/smplayer-21.8.0-win32-qt5.6.exe/download

**Comment by Grzespp** [comment]
Sorry, I miss your e-mail. I will install your uploaded version. I let you know how it works^^  Have a nice day  Dnia 5 września 2021 17:06 Ricardo ***@***.***&gt; napisał(a):   I&#39;ve just uploaded a package built with Qt 5.6. Please let me know if it really works on Windows XP:    sourceforge.net sourceforge.net  —  You are receiving this because you modified the open/close state.  Reply to this email directly,  github.com view it on GitHub , or  github.com unsubscribe .  Triage notifications on the go with GitHub Mobile for  apps.apple.com iOS  or  play.google.com Android .

**Comment by Grzespp** [comment]
I install your version and it works pretty. I have one error about youtube.dl 'sendrequest error' but everything works with videos from my drive
