### ISSUE TITLE
last release doesn't seem to be working with xp

### ISSUE THREAD

**Issue by Jantam11** [smplayer-dev/smplayer#207]
so when i updated to the last version from the website everything went as expected, it installed and didn't seem to have any problem but when i try to open the app itself (and smtube aswell) it gives an error message, something about not finding CancelIoEx in KERNEL32.dll.

maybe you dropped xp support and i didn't notice or maybe it could have been a screw up on my part?

**Comment by smplayer-dev** [comment]
This problem was already reported:
https://github.com/smplayer-dev/smplayer/issues/203

Could you test if the package built with Qt 5.6 works for you?

**Comment by Jantam11** [comment]
I will try this tomorrow once I get the PC back on, then I'll let you know how that went, by the way should I uninstall it first?

**Comment by smplayer-dev** [comment]
I'm not sure if it's really necessary, but just in case I would do it.

**Comment by Jantam11** [comment]
That did it! it worked! thx, is there a Qt5.6 build for smtube?

**Comment by smplayer-dev** [comment]
Good to know :)

smtube with qt 5.6:
https://sourceforge.net/projects/smtube/files/SMTube/21.7.0/smtube-21.7.0-win32-qt5.6.exe/download
