### ISSUE TITLE
Add support of DirectShow  to use 3DYD Youtube Source

### ISSUE THREAD

**Issue by trimechee** [smplayer-dev/smplayer#212]
Hello, i think that our beloved SMPlayer is not compatible with this great software "3DYD Youtube Source" which is a set of plugins for watching videos from media sites directly in the video player 

https://ys.3dyd.com/home/

because SMPlayer doesn't support playback using DirectShow, so I had to change my favorite video player SMPlayer for another video player that supports directshow, please it will be great if there an option to support directshow in SMPlayer to use this program which allows  to avoid using a web browser that might have been heavy cpu and full of ads !

SMplayer can't play video from sibnet.ru even with video support enabled in SMPlayer preferences or with 3DYD youtube source" software :

https://video.sibnet.ru/video3492086-Tokubetsuban_Free_Take_Your_Marks_01_VOSTFR_www_vostfree_com/?utm_source=player&utm_medium=video&utm_campaign=EMBED

 Thank you !

**Comment by smplayer-dev** [comment]
That URL plays fine for me (testing on Linux) with both youtube-dl and yt-dlp.

Anyway it's unlikely I could add support fro DirectShow. It's a different technology (and for Windows only) which doesn't fit in the way SMPlayer is implemented and works.

 SMPlayer already supports playing videos from streaming sites by using youtube-dl and now also yt-dlp. If there are some sites missing maybe they'll add them in the future or you can request them to support them.

Regarding "3DYD Youtube Source", I think it would be better if the could provide a library that any application could use, instead of a plugin for a very specific environment.

**Comment by trimechee** [comment]
Thank you very much for your help :)

I just tested and tried again to play the sibnet video by putting the url in SMPplayer, because sibnet is the most used site by anime streaming sites, I am using updated version of windows 10, but unfortunately I cannot not play this video hosted by sibnet ! same failure to play video in vlc .....


Maybe the problem comes that by installing SMPlayer, I did not install mplayer but just installed mpv without checking the installation box of mlayer?



Maybe if I put the vlc plugin recommended by "3DYD Youtube Source" in a SMPplayer directory, it will have directshow support and it will work in SMPlayer lol,  I would like to try this trick but I don't know in which SMPlayer folder to put this plugin .....

https://ys.3dyd.com/changelog/vlc/

I think I'll send in sha Allah our discussion to the author of 3DYD Youtube Source to maybe try that 3DYD Youtube Source is fully compatible with SMPlayer .....


Here is the log of this problem after failure to play this videos in windows 10 :


mpv/mpv.exe --no-config --no-quiet --terminal --no-msg-color --input-ipc-server=C:/Users/Asus/AppData/Local/Temp/smplayer-mpv-574 --msg-level=ffmpeg/demuxer=error --video-rotate=no -v --no-fs --hwdec=auto --sub-auto=fuzzy --vo=direct3d, --audio-device=wasapi/{616a51b4-e1db-4de8-b96e-5ee863d9d704} --ao=wasapi, --priority=normal --no-input-default-bindings --input-vo-keyboard=no --no-input-cursor --cursor-autohide=no --no-keepaspect --wid=524402 --monitorpixelaspect=1 --osd-level=1 --osd-scale=1 --osd-bar-align-y=0.6 --sub-scale=5 --sub-codepage=ISO-8859-1 --sub-pos=100 --volume=60 --cache=auto --no-correct-pts --audio-pitch-correction=yes --volume-max=100 --ytdl --term-playing-msg=MPV_VERSION=${=mpv-version:}
INFO_VIDEO_WIDTH=${=width}
INFO_VIDEO_HEIGHT=${=height}
INFO_VIDEO_ASPECT=${=video-params/aspect}
INFO_VIDEO_FPS=${=container-fps:${=fps}}
INFO_VIDEO_FORMAT=${=video-format}
INFO_VIDEO_CODEC=${=video-codec}
INFO_DEMUX_ROTATION=${=track-list/0/demux-rotation}
INFO_AUDIO_FORMAT=${=audio-codec-name}
INFO_AUDIO_CODEC=${=audio-codec}
INFO_AUDIO_RATE=${=audio-params/samplerate}
INFO_AUDIO_NCH=${=audio-params/channel-count}
INFO_LENGTH=${=duration:${=length}}
INFO_DEMUXER=${=current-demuxer:${=demuxer}}
INFO_SEEKABLE=${=seekable}
INFO_TITLES=${=disc-titles}
INFO_CHAPTERS=${=chapters}
INFO_TRACKS_COUNT=${=track-list/count}
METADATA_TITLE=${metadata/by-key/title:}
METADATA_ARTIST=${metadata/by-key/artist:}
METADATA_ALBUM=${metadata/by-key/album:}
METADATA_GENRE=${metadata/by-key/genre:}
METADATA_DATE=${metadata/by-key/date:}
METADATA_TRACK=${metadata/by-key/track:}
METADATA_COPYRIGHT=${metadata/by-key/copyright:}
INFO_MEDIA_TITLE=${=media-title:}
INFO_STREAM_PATH=${stream-path}
 --term-status-msg=STATUS: ${=time-pos} / ${=duration:${=length:0}} P: ${=pause} B: ${=paused-for-cache} I: ${=core-idle} VB: ${=video-bitrate:0} AB: ${=audio-bitrate:0} https://video.sibnet.ru/video3492086-Tokubetsuban_Free_Take_Your_Marks_01_VOSTFR_www_vostfree_com/?utm_source=player&utm_medium=video&utm_campaign=EMBED

Command line options: '--no-config' '--no-quiet' '--terminal' '--no-msg-color' '--input-ipc-server=C:/Users/Asus/AppData/Local/Temp/smplayer-mpv-574' '--msg-level=ffmpeg/demuxer=error' '--video-rotate=no' '-v' '--no-fs' '--hwdec=auto' '--sub-auto=fuzzy' '--vo=direct3d,' '--audio-device=wasapi/{616a51b4-e1db-4de8-b96e-5ee863d9d704}' '--ao=wasapi,' '--priority=normal' '--no-input-default-bindings' '--input-vo-keyboard=no' '--no-input-cursor' '--cursor-autohide=no' '--no-keepaspect' '--wid=524402' '--monitorpixelaspect=1' '--osd-level=1' '--osd-scale=1' '--osd-bar-align-y=0.6' '--sub-scale=5' '--sub-codepage=ISO-8859-1' '--sub-pos=100' '--volume=60' '--cache=auto' '--no-correct-pts' '--audio-pitch-correction=yes' '--volume-max=100' '--ytdl' '--term-playing-msg=MPV_VERSION=${=mpv-version:}
[debug] INFO_VIDEO_WIDTH=${=width}
[debug] INFO_VIDEO_HEIGHT=${=height}
[debug] INFO_VIDEO_ASPECT=${=video-params/aspect}
[debug] INFO_VIDEO_FPS=${=container-fps:${=fps}}
[debug] INFO_VIDEO_FORMAT=${=video-format}
[debug] INFO_VIDEO_CODEC=${=video-codec}
[debug] INFO_DEMUX_ROTATION=${=track-list/0/demux-rotation}
[debug] INFO_AUDIO_FORMAT=${=audio-codec-name}
[debug] INFO_AUDIO_CODEC=${=audio-codec}
[debug] INFO_AUDIO_RATE=${=audio-params/samplerate}
[debug] INFO_AUDIO_NCH=${=audio-params/channel-count}
[debug] INFO_LENGTH=${=duration:${=length}}
[debug] INFO_DEMUXER=${=current-demuxer:${=demuxer}}
[debug] INFO_SEEKABLE=${=seekable}
[debug] INFO_TITLES=${=disc-titles}
[debug] INFO_CHAPTERS=${=chapters}
[debug] INFO_TRACKS_COUNT=${=track-list/count}
[debug] METADATA_TITLE=${metadata/by-key/title:}
[debug] METADATA_ARTIST=${metadata/by-key/artist:}
[debug] METADATA_ALBUM=${metadata/by-key/album:}
[debug] METADATA_GENRE=${metadata/by-key/genre:}
[debug] METADATA_DATE=${metadata/by-key/date:}
[debug] METADATA_TRACK=${metadata/by-key/track:}
[debug] METADATA_COPYRIGHT=${metadata/by-key/copyright:}
[debug] INFO_MEDIA_TITLE=${=media-title:}
[debug] INFO_STREAM_PATH=${stream-path}
' '--term-status-msg=STATUS: ${=time-pos} / ${=duration:${=length:0}} P: ${=pause} B: ${=paused-for-cache} I: ${=core-idle} VB: ${=video-bitrate:0} AB: ${=audio-bitrate:0}' 'https://video.sibnet.ru/video3492086-Tokubetsuban_Free_Take_Your_Marks_01_VOSTFR_www_vostfree_com/?utm_source=player&utm_medium=video&utm_campaign=EMBED'
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Mon Jan 27 12:34:40 +08 2020
ffmpeg library versions:
   libavutil       56.38.100
   libavcodec      58.67.100
   libavformat     58.36.100
   libswscale      5.6.100
   libavfilter     7.71.100
   libswresample   3.6.100
ffmpeg version: git-2020-01-26-5e6210015

Configuration: /home/shinchiro/build/build64/packages/mpv-stable-prefix/src/mpv-stable/waf configure --enable-static-build --enable-pdf-build --disable-manpage-build --enable-libmpv-shared --enable-lua --enable-javascript --enable-sdl2 --enable-libarchive --enable-libass --enable-libbluray --enable-dvdnav --enable-uchardet --enable-rubberband --enable-lcms2 --enable-openal --enable-spirv-cross --enable-vulkan --enable-vapoursynth --prefix=/home/shinchiro/build/build64/install/mingw
List of enabled features: asm atomics build-date cplayer cuda-hwaccel cuda-interop d3d-hwaccel d3d11 d3d9-hwaccel debug-build direct3d dos-paths drmprime dvdnav egl-angle egl-angle-win32 egl-helpers ffmpeg ffnvcodec gl gl-dxinterop gl-dxinterop-d3d9 gl-win32 glob glob-win32 gnuc gpl iconv javascript jpeg lcms2 libarchive libass libass-osd libav-any libavcodec libavdevice libavutil libbluray libm libmpv-shared libplacebo lua luajit mingw noexecstack openal optimize plain-gl posix-or-mingw rubberband sdl2 sdl2-audio sdl2-gamepad sdl2-video shaderc shaderc-static spirv-cross spirv-cross-static static-build stdatomic uchardet vapoursynth vulkan wasapi win32-desktop win32-internal-pthreads win32-pipes zlib
Setting option 'config' = 'no' (flags = 8)
Setting option 'quiet' = 'no' (flags = 8)
Setting option 'terminal' = '' (flags = 8)
Setting option 'msg-color' = 'no' (flags = 8)
Setting option 'input-ipc-server' = 'C:/Users/Asus/AppData/Local/Temp/smplayer-mpv-574' (flags = 8)
Setting option 'msg-level' = 'ffmpeg/demuxer=error' (flags = 8)
Setting option 'video-rotate' = 'no' (flags = 8)
Setting option 'v' = '' (flags = 8)
Setting option 'fs' = 'no' (flags = 8)
Setting option 'hwdec' = 'auto' (flags = 8)
Setting option 'sub-auto' = 'fuzzy' (flags = 8)
Setting option 'vo' = 'direct3d,' (flags = 8)
Setting option 'audio-device' = 'wasapi/{616a51b4-e1db-4de8-b96e-5ee863d9d704}' (flags = 8)
Setting option 'ao' = 'wasapi,' (flags = 8)
Setting option 'priority' = 'normal' (flags = 8)
Setting option 'input-default-bindings' = 'no' (flags = 8)
Setting option 'input-vo-keyboard' = 'no' (flags = 8)
Setting option 'input-cursor' = 'no' (flags = 8)
Setting option 'cursor-autohide' = 'no' (flags = 8)
Setting option 'keepaspect' = 'no' (flags = 8)
Setting option 'wid' = '524402' (flags = 8)
Setting option 'monitorpixelaspect' = '1' (flags = 8)
Setting option 'osd-level' = '1' (flags = 8)
Setting option 'osd-scale' = '1' (flags = 8)
Setting option 'osd-bar-align-y' = '0.6' (flags = 8)
Setting option 'sub-scale' = '5' (flags = 8)
Setting option 'sub-codepage' = 'ISO-8859-1' (flags = 8)
Setting option 'sub-pos' = '100' (flags = 8)
Setting option 'volume' = '60' (flags = 8)
Setting option 'cache' = 'auto' (flags = 8)
Setting option 'correct-pts' = 'no' (flags = 8)
Setting option 'audio-pitch-correction' = 'yes' (flags = 8)
Setting option 'volume-max' = '100' (flags = 8)
Setting option 'ytdl' = '' (flags = 8)
Setting option 'term-playing-msg' = 'MPV_VERSION=${=mpv-version:}
[debug] INFO_VIDEO_WIDTH=${=width}
[debug] INFO_VIDEO_HEIGHT=${=height}
[debug] INFO_VIDEO_ASPECT=${=video-params/aspect}
[debug] INFO_VIDEO_FPS=${=container-fps:${=fps}}
[debug] INFO_VIDEO_FORMAT=${=video-format}
[debug] INFO_VIDEO_CODEC=${=video-codec}
[debug] INFO_DEMUX_ROTATION=${=track-list/0/demux-rotation}
[debug] INFO_AUDIO_FORMAT=${=audio-codec-name}
[debug] INFO_AUDIO_CODEC=${=audio-codec}
[debug] INFO_AUDIO_RATE=${=audio-params/samplerate}
[debug] INFO_AUDIO_NCH=${=audio-params/channel-count}
[debug] INFO_LENGTH=${=duration:${=length}}
[debug] INFO_DEMUXER=${=current-demuxer:${=demuxer}}
[debug] INFO_SEEKABLE=${=seekable}
[debug] INFO_TITLES=${=disc-titles}
[debug] INFO_CHAPTERS=${=chapters}
[debug] INFO_TRACKS_COUNT=${=track-list/count}
[debug] METADATA_TITLE=${metadata/by-key/title:}
[debug] METADATA_ARTIST=${metadata/by-key/artist:}
[debug] METADATA_ALBUM=${metadata/by-key/album:}
[debug] METADATA_GENRE=${metadata/by-key/genre:}
[debug] METADATA_DATE=${metadata/by-key/date:}
[debug] METADATA_TRACK=${metadata/by-key/track:}
[debug] METADATA_COPYRIGHT=${metadata/by-key/copyright:}
[debug] INFO_MEDIA_TITLE=${=media-title:}
[debug] INFO_STREAM_PATH=${stream-path}
' (flags = 8)
Setting option 'term-status-msg' = 'STATUS: ${=time-pos} / ${=duration:${=length:0}} P: ${=pause} B: ${=paused-for-cache} I: ${=core-idle} VB: ${=video-bitrate:0} AB: ${=audio-bitrate:0}' (flags = 8)
Waiting for scripts...
[ipc] Starting IPC master
[ipc] Listening to IPC pipe.
Set property: shared-script-properties -> 1
Set property: shared-script-properties -> 1
Set property: shared-script-properties -> 1
[osd/libass] Shaper: FriBidi 1.0.8 (SIMPLE) HarfBuzz-ng 2.6.4 (COMPLEX)
[osd/libass] Setting up fonts...
[osd/libass] Using font provider directwrite
[osd/libass] Done.
Done loading scripts.
Running hook: ytdl_hook/on_load
[ytdl_hook] ytdl:// hook 
[ytdl_hook] not a ytdl:// url 
[osd/libass] Shaper: FriBidi 1.0.8 (SIMPLE) HarfBuzz-ng 2.6.4 (COMPLEX)
[osd/libass] Setting up fonts...
[osd/libass] Using font provider directwrite
[osd/libass] Done.
[ffmpeg] Opening https://video.sibnet.ru/video3492086-Tokubetsuban_Free_Take_Your_Marks_01_VOSTFR_www_vostfree_com/?utm_source=player&utm_medium=video&utm_campaign=EMBED
Set property: shared-script-properties -> 1
[ffmpeg] Mime-type: 'text/html; charset=windows-1251'
[demux] Trying demuxers for level=normal.
[lavf] No format found, try lowering probescore or forcing the format.
[demux] Trying demuxers for level=unsafe.
[lavf] No format found, try lowering probescore or forcing the format.
Opening failed or was aborted: https://video.sibnet.ru/video3492086-Tokubetsuban_Free_Take_Your_Marks_01_VOSTFR_www_vostfree_com/?utm_source=player&utm_medium=video&utm_campaign=EMBED
Running hook: ytdl_hook/on_load_fail
[ytdl_hook] full hook 
[ytdl_hook] ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),)) 
[ytdl_hook] youtube-dl failed: unexpected error ocurred 
finished playback, unrecognized file format (reason 4)
Failed to recognize file format.


Exiting... (Errors when loading file)
Set property: shared-script-properties -> 1
Set property: shared-script-properties -> 1

**Comment by smplayer-dev** [comment]
That video plays fine for me on Windows 10 using [version 21.8.0.9953](https://github.com/smplayer-dev/smplayer/releases/tag/v21.8.0.9953) with both youtube-dl and yt-dlp.

Placing a vlc plugin into the SMPlayer folder won't do anything.

**Comment by trimechee** [comment]
It's a mystery, I am using this version Version : 21.8.0 (révision 9887) (64-bit), I updated SMPlayer via SMPlayer updater but i have a stable version and I think i shoud use the last developer version, thank you for your help :)

Please I have a request : sometimes the data plan is low or the wifi is weak and it will be great if you can implement this option present in "3DYD Youtube Source" to avoid buffer and jerky video playback :

Download media data independently from playback :
If this option is checked, filter performs media file download independently of playback. So it continues downloading even when playback is paused.

This approach is useful when you have slow or unstable Internet connection (so playback is stuttering), or when you need to seek a lot within a file. However if all these cases are not about you, and usually you do not watch whole video, it may end up with bandwidth overuse since a lot of downloaded data eventually will be not watched.

When this option is unchecked, filter downloads only part of data that is about to be played.

Filter caches downloaded data in temporary directory regardless of the state of this option and never re-downloads the same data again. Caching is well visualized by Activity popup page.

https://ys.3dyd.com/help/property_pages/

and it will be great if SMPlayer can automatically detect low internet speed and automatically increase network cache a lot if internet connection is too weak and video is in HD, for example automatically increase network cache to 2 minutes or 3 minutes if the internet speed is very low so we could have smooth playback, it's a sort of time shift, thank you very much :)

**Comment by raszpl** [comment]
>[ytdl_hook] ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))
[ytdl_hook] youtube-dl failed: unexpected error ocurred

You have old youtube-dl installed? 

relevant to the discussion https://github.com/smplayer-dev/smplayer/discussions/198

>"3DYD Youtube Source" DirectShow source filters

How the hell does that work? :o You paste http instead of a file and windows magically intercepts it if specific DirectShow filters is installed? what kind of magic is that? Very interesting.

**Comment by trimechee** [comment]
I have an updated youtybe-dl, I dont't know how 3DYD Youtube Source work with DirectShow filters but I tried and this plugin is amazing and it works with many streaming sites and I can buffer whole streaming video to avoid jerks video !

http://ys.3dyd.com/help/
