### ISSUE TITLE
Font scaled too large when rendering ASS Subtitles embedded in MKV

### ISSUE THREAD

**Issue by jmaeshawn** [smplayer-dev/smplayer#234]
I'm having a problem when playing back certain videos that have ass subtitles embedded in an mkv file.

When I play the episode back directly in mpv, the subtitles display properly, as you can see here:
[When played directly in MPV](https://user-images.githubusercontent.com/6907886/136284636-7115e025-b865-45f7-b6b6-bcc66f495d04.png)

But when I play them in smplayer with mpv set as the rendering engine it scales the fonts incorrectly, to the point where they're way too large -- sometimes so large that I can't even watch the video:
[When played in smplayer](https://user-images.githubusercontent.com/6907886/136284759-8b6368cf-420c-4a09-a37d-0e383f55fe1f.png)

This very same bug also happens in the home theater software Kodi, but not in mpv, mplayer, or Media Player Classic.

Given that smplayer seems to have the same issue when set to use Mplayer, I can only assume that smplayer is using a different ASS subtitle rendering engine than mpv itself uses, which is what causes it to render the subtitles incorrectly.

If you could please fix this problem as soon as possible, I'd really appreciate it. In my opinion, smplayer is otherwise perfect, but this problem with subtitles is preventing me from being able to use it.

**Screenshots**
[When played directly in MPV](https://user-images.githubusercontent.com/6907886/136284636-7115e025-b865-45f7-b6b6-bcc66f495d04.png)
[When played in smplayer](https://user-images.githubusercontent.com/6907886/136284759-8b6368cf-420c-4a09-a37d-0e383f55fe1f.png)

**Your Environment**
 - SMPlayer version: 21.8.0 (Revision 9887) 64-bit
 - OS: Windows 10 Version 21H1 (OS Build 19043.1202)
 - Multimedia engine you're using with SMPlayer (preferences -> general):
 [ ] MPlayer
 [X ] MPV

**Logs**
I've attached the smplayer log and the mpv log here:
[smplayer.log](https://github.com/smplayer-dev/smplayer/files/7297185/smplayer.log)
[mpv.log](https://github.com/smplayer-dev/smplayer/files/7297184/mpv.log)

**Comment by smplayer-dev** [comment]
It seems you set a font size too large. You can decrease it in the menu Subtitles. And set the **default scale** in _preferences -> subtitles -> Font and colors_ to 1.

**Comment by jmaeshawn** [comment]
Thank you for your response. 

The thing is... I didn't change any settings with the font size. I just looked at the default scale settings, like you said, and it was already set to 1 as you can see [here](https://user-images.githubusercontent.com/6907886/136362792-adcdbc25-dcf5-4bdb-a353-c796f4b6a457.png). It also shouldn't even be applying any of those default scale settings because the option to use those instead of the ASS subtitle's own style is not checked.

I also tried decreasing the scale in the Subtitles menu, but that caused more problems.
This is a screenshot of what it looked like in smplayer before decreasing the font scale:
![This is a screenshot of what it looked like before decreasing the font scale](https://user-images.githubusercontent.com/6907886/136363671-79ccc081-c8e4-435e-b567-8bc62309b89b.png)

And this is a screenshot of what it looks like in smplayer after decreasing the font scale:
![And this is a screenshot of what it looks like after decreasing the font scale](https://user-images.githubusercontent.com/6907886/136364007-b010e15e-40b6-4bdc-a9af-1b5d513ff895.png)

As you can see, it made the standard dialogue font rendered at the correct size, but it makes everything else (like the typeset title sign) much smaller than it should be.

In contrast, here's how it looks when played directly in mpv, which renders the subtitles entirely correctly:
![here's how it looks when played directly in mpv](https://user-images.githubusercontent.com/6907886/136365289-b4ae537d-cc9a-448b-8dcc-30be5eb03b44.png)

This is why I said it has to be a bug in whatever subtitle rendering engine smplayer is using for ASS subtitles, because mpv (along with Aegisub and every other media player except for Kodi) displays the subtitles exactly how they were intended to display, but smplayer does not.

I *really* hope you can fix this problem, because I really like smplayer and its GUI, but because I work with subtitles as a profession, I can't use it until smplayer is able to reliably display ASS subtitles correctly.

**Comment by smplayer-dev** [comment]
Can you provide a link for a mkv a video with this problem?

SMPlayer doesn't have a subtitle renderer, it's done by mpv, so I guess a font setting it's causing the problem.

**Comment by fredlkrue** [comment]
The "show info on OSD" also is scaled larger than on MPV, maybe is related to the ASS subtitles issue.

**Comment by smplayer-dev** [comment]
This doesn't happen to me. Try this: go to preferences -> subtitles -> Font and colors and set the default scale to 1. Then go to preferences -> general and disable the option to remember settings for all files. Does it make any difference?

**Comment by jmaeshawn** [comment]
Here's a link to one of the many videos that I have this problem with: [Problematic Video](https://mega.nz/file/gNU30Cga#qIYBIz43au_0I4dl6YefMzBRC0c_c3LqECpP60aoFZk).

I tried turning off the option to remember settings for all files, but the problem still happens regardless. The problem with the subtitles being too large also happens on more than just this one video, so it can't be a setting for just this one file...

Hopefully you can check this video and compare it to what standalone mpv shows, and find out why smplayer scales the subtitles too large.

**Comment by smplayer-dev** [comment]
![Captura de pantalla 2021-10-09 a las 23 51 34](https://user-images.githubusercontent.com/10128951/136674576-0f7fd29a-b8e6-4c63-9203-67e6cf077dec.png)

It looks fine to me.

**Comment by jmaeshawn** [comment]
Did you have to do something special to get it to work correctly? I just tried it on a brand new computer with a fresh install of Windows 10 and nothing else installed except smplayer, and it still renders the subtitles at the incorrect size. :(

**Comment by smplayer-dev** [comment]
Nothing, maybe I changed the font color, but that's all.

**Comment by smplayer-dev** [comment]
I'm testing now on a Windows 10 installed on a virtual machine, and yes, now I can see the problem. It's weird.
Maybe it's a bug in mpv, subtitles are also huge when I play the video directly in mpv.
The subtitle size is correct in mplayer.

The problem seem to be fixed in the development version. I've just downloaded this version and I think it works fine:
https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20211010-git-b3f3c3f.7z/download
