### ISSUE TITLE
Why is the hash of The Fosshub installer different than the Github one?

### ISSUE THREAD

**Issue by Jimmy03** [smplayer-dev/smplayer#244]
For **smplayer-21.8.0-x64.exe**

Fosshub: SHA-256: 686af2ca94b7b0c1dfc259c8861c35fe7a99ed46dddc027522677e6e66ef6281

Github: SHA-256: 53222ad52cb2144231773c49877d2ad2bcdfbc55e5c4c6b50805621e2149d8bc

If we previously installed via Fosshub, should we continue using those for updates?
mpv 0.32 has a security vulnerability, so need to update.

**Comment by smplayer-dev** [comment]
The difference is that the packages at Fosshub are digitally signed while the packages at github are not.

I've just uploaded the signed packages to github, so the problem should be fixed now.
