### ISSUE TITLE
Optional support for MPV Plugins (or at the very least SponsorBlock)

### ISSUE THREAD

**Issue by MintMain21** [smplayer-dev/smplayer#261]
**Is your feature request related to a problem? Please describe.**
Before trying SMPlayer, I tried Celluloid for it's compatibility with MPV Plugins (more specifically, I wanted to use https://github.com/po5/mpv_sponsorblock). I was quickly turned off by some technical issues with Celluloid, most notably it's excessive RAM usage. After using SMPlayer for a while now and discovering https://codeberg.org/jouni/mpv_sponsorblock_minimal, I decided to try Celluloid again to see if the plugin would work there. It does, and I applied my experience with SMPlayer to ironing out all the other technical kinks I had. Unfortunately, Celluloid still uses a lot of RAM. I would like to use the same plugin on SMPlayer, but SMPlayer does not seem compatible with MPV Plugins quite like how Celluloid is.

**Describe the solution you'd like**
Offer a GUI option in SMPlayer settings to use and customize additional MPV Plugins (and set their respective keyboard shortcuts). Or at the very least, integrate the Sponsorblock plugin into SMPlayer itself.

**Describe alternatives you've considered**
I could live using Celluloid (so long as I can wrap my head around how to restrict it's RAM consumption), but I've grown accustomed to SMPlayer and would welcome a means to apply the MPV Sponsorblock plugin to it. 

**Additional context**
Pretty much the only MPV Plugin I care about is Sponsorblock, maybe also the one where you can view DVD Chapters from a "Menu" without actually loading the DVD Menu. 

Edit: Solution found. Added --scripts=[File Location for Plugin] to SMPlayer's "Options for MPV" and it works perfectly.

**Comment by XRaTiX** [comment]
How do you have it? I have it like this but its not working,I tried with mpv_sponsorblock (no minimal) and not working either.

![image](https://user-images.githubusercontent.com/40683158/140619993-cffe1a7b-bae6-4cf0-ab1c-b5906e521c0a.png)

**Comment by MintMain21** [comment]
You also have to go to Network Settings and set "Support for video sites": to mpv+youtube+dl

**Comment by XRaTiX** [comment]
> You also have to go to Network Settings and set "Support for video sites": to mpv+youtube+dl

That was it,thanks very much.
