### ISSUE TITLE
On fullscreening SMPlayer jumps to the monitor it was last closed on

### ISSUE THREAD

**Issue by ifohancroft** [smplayer-dev/smplayer#29]
**Describe the bug**
If you have SMPlayer on one monitor and close it, then you open it, move it to another monitor and try to fullscreen it (double clicking on the video), it fullscreens but the now fullscreen window jumps to the monitor you last closed it on. It used to only happen if the option Remember window position and size was turned on, but now it happens regardless of that option.

**To Reproduce**
1. Start SMPlayer on one of the monitors on a multi-monitor setup.
2. Close it.
3. Start it again
4. Move it to a monitor different than the one it was one when you closed it.
5. Fullscreen it
6. The fullscreen window jumps to the monitor you closed it on.

To be able to full screen it on the monitor you want, you have to move it to it, close it and open it again.

**Expected behavior**
1. Start SMPlayer.
2. Fullscreen it
3. It fullscreens on the monitor it is, regardless of what monitor it was last closed on.

**Your Enviroment**
 - SMPlayer version: Version: 21.1.0 (revision 9475) | Using Qt 5.15.2 (compiled with Qt 5.15.2) | Using MPV 0.33.0
 - OS: Manjaro Linux 20.2.1
 - Multimedia engine you're using with SMPlayer (preferences -> general):
 [ ] MPlayer
 [X] MPV: Set by Multimedia Engine: Other and pointed to as /usr/bin/mpv (As far as I remember, I didn't change it upon install and it was like that upon install)

**Logs**
Here is the log: https://gist.github.com/ifohancroft/10c99778164ae7a1ffdd1a253ec4e800

**Additional context**
The bug has been present in SMPlayer across different Linux distributions, desktop environments and SMPlayer backends since at least 2019 judging by my original bug report on SourceForge found here: https://sourceforge.net/p/smplayer/bugs/908/

**Comment by smplayer-dev** [comment]
I can't reproduce the problem (using smplayer 21.1.0 r9526 with Qt 5.15.2).

I can't reproduce it either with smplayer 21.1.0 r9475 on Ubuntu 20.04.

**Comment by ifohancroft** [comment]
> I can't reproduce the problem (using smplayer 21.1.0 r9526 with Qt 5.15.2).
> 
> I can't reproduce it either with smplayer 21.1.0 r9475 on Ubuntu 20.04.

Are you using Xorg or Wayland and are you using NVIDIA or AMD? Properietary driver or Open Source? Also single Xorg screen or one per monitor?

I'm using Xorg with NVIDIA's proprietary driver. Single Xorg screen. No Xinerama.

**Comment by smplayer-dev** [comment]
I've tested on a real computer with Ubuntu 16.04 and an ATI card. On a virtualbox with Ubuntu 20.04 (both xorg and wayland), a virtualbox with Manjaro KDE and a real computer with Windows 10. I wasn't able to reproduce the problem in any of them.

**Comment by ifohancroft** [comment]
> I've tested on a real computer with Ubuntu 16.04 and an ATI card. On a virtualbox with Ubuntu 20.04 (both xorg and wayland), a virtualbox with Manjaro KDE and a real computer with Windows 10. I wasn't able to reproduce the problem in any of them.

I forgot to mention I am running MATE on my Manjaro.
From what I was able to find, Ubuntu 16.04 may be using Wayland so I am not sure if it's an NVIDIA use case problem or an Xorg usecase problem or both and whether it's a Linux bug only.

What graphics card is the Windows machine running?

P.S. Here is a video demonstrating the bug: https://www.youtube.com/watch?v=YL6mqzvcSnk (When SMPlayer jumps to the second monitor, after opening it the second time, before I fullscreen it, that's not part of the bug, I just used a keyboard shortcut to move it to the second monitor instead of dragging it with the mouse there, the bug is after that when I fullscreen it and it jumps back to the first monitor)
Sorry for the squashed monitors, I fit two 1920 monitors into a single 1920 video.

**Comment by smplayer-dev** [comment]
Is the smplayer window maximized? That could make a difference. However I still can't reproduce the problem in my computer.

**Comment by ifohancroft** [comment]
> Is the smplayer window maximized? That could make a difference. However I still can't reproduce the problem in my computer.

That was a brilliant guess! Yes, it was maximized and yes, testing proves that it only happens when it's maximized.

**Comment by smplayer-dev** [comment]
Anyway I still can't reproduce it. Tested on Ubuntu 20.04, with the smplayer window maximized and using the key shortcut to move it to the other screen. Maybe it's a bug of your distro.

**Comment by ifohancroft** [comment]
Yeah, I have no idea why it can't be reproduced, but it's not the distro as it was happening to me on Fedora as well, when I was still using it. I was about to say that the use of shortcut is irrelevant but I just tested and 1. If you unmaximize it before moving - it doesn't happen and 2. If you drag it also becomes unmaximized so the bug again, doesn't happen.

I was using different desktop environment on Fedora than I am now on Manjaro, but I am starting to wonder if isn't the compositor causing it, as I believe I was using compton on XFCE on Fedora and now I am using picom on MATE on Manjaro which is a fork of compton. Unless, it is a common feature among the two window managers that doesn't change a certain property of the window, as the shortcut I use isn't a custom one, but the built in window manager feature to move the window to the right monitor.

I think perhaps this bug report should be closed and I should test with other applications and perhaps open a bug report for the window manager.
