### ISSUE TITLE
svn_revision.h USE_SVN_VERSIONS use_svn_versions svn_revision are obsolete with the github repo

### ISSUE THREAD

**Issue by jospezial** [smplayer-dev/smplayer#30]
I was writing a live ebuild for Gentoo which uses this github repo but got the error
```
version.cpp:28:10: fatal error: svn_revision.h: No such file or directory
   28 | #include "svn_revision.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:2711: .obj/version.o] Error 1
```
My only solution was to change
#define USE_SVN_VERSIONS 1
to
#define USE_SVN_VERSIONS 0
in
https://github.com/smplayer-dev/smplayer/blob/154349ba055647bf0a2cd854a32793546eb59d4e/src/version.cpp#L22

I have read svn_revision.h has to be generated with get_svn_revision.sh.
Maybe all the svn references need a clean-up.

**Comment by smplayer-dev** [comment]
Even if you get the sources from git, you can still call `get_svn_revision`.sh to prevent that error.
Since I still use svn instead of git this issue won't be fixed for the moment.

**Comment by jospezial** [comment]
But if get_svn_revision.sh does not get the svn_revision and writes
SVN-r0UNKNOWN
and
#define SVN_REVISION "0UNKNOWN"
because there is no ".svn" or useable output of svn info, then it makes no sense.
It would be better to make the "#define USE_SVN_VERSIONS" configurable or conditional depend with "if" on existence of ".svn".

As you took get_svn_revision.sh from mplayer, maybe code from there would help in future with git:
https://github.com/mpv-player/mpv/blob/master/version.sh

**Comment by smplayer-dev** [comment]
Hopefully this is fixed in https://github.com/smplayer-dev/smplayer/commit/170e77fed669c1a877966d521d1e71422c670d68.
