### ISSUE TITLE
SMPlayer does not shuffle the playlist when the 'Shuffle' button is enabled.

### ISSUE THREAD

**Issue by ElektroStudios** [smplayer-dev/smplayer#312]
**Describe the bug**
SMPlayer does not shuffle the playlist when the 'Shuffle' button is enabled.

Note that I didn't had this issue in previous versions. But I'm not sure which version I was using before I've updated to v21.10.0. Sorry.

**To Reproduce**

1. Run SMPlayer.
2. If the 'Shuffle' button is disabled, enable it.
3. Drag&Drop a couple of videos to the SMPlayer Window (this will generate a playlist).
4. Press the 'Next file' button to reproduce the next video in the playlist.

At this point you will notice the SMPlayer will reproduce the videos in normal order (1, 2, 3, 4...), not in shuffle mode.

**Workaround**
To solve the issue just be sure to Drag&Drop the files / load a playlist with the 'Shuffle' button disabled, then enable the button to shuffle the current playlist.

**Your Enviroment**
 - SMPlayer version: 21.10.0 (revision 10000) x64
 - OS: Windows 10
 - Multimedia engine you're using with SMPlayer: MPlayer

**Comment by smplayer-dev** [comment]
Hopefully this is fixed now
https://github.com/smplayer-dev/smplayer/commit/f111ba2b30a30c8aa40f48379353dcdcf6be6640
