### ISSUE TITLE
Volume slider does not folllow the setting --volume=<anyvalue> and/or -volume=<anyvalue>

### ISSUE THREAD

**Issue by ghost** [smplayer-dev/smplayer#314]
The --volume and -volume option works, however...

**Describe the bug**
Setting the mpv option --volume=<anyvalue> and/or -volume<anyvalue> in Advanced settings does not affect the actual volume slider. Is this supposed to be like that? If so, but _why?_

In other words, if I set --volume/-volume=0, the internal player volume is at 0, it works. But the interface volume slider skin thing is not at 0. If I use arrow keys to adjust the volume, it does not start at 0, it starts at whatever the slider is at, for example, 50.

Tested with every other skin as well, still the same result.

**Expected behavior**
When I set --volume=0 and I need the slider to be exactly at zero so I can start adjusting the volume with keyboard starting at 0 whenever I start a new playback.

**Screenshot**
![2021-12-16_13 44 18_Thursday](https://user-images.githubusercontent.com/7377351/146315145-6fbc59dd-f0b6-4c0c-90b3-556c95ec0445.png)
Screenshot above shows the volume slider at 50 since the previous playback.
I started a new playback with --volume/-volume=0, but the slider is still at 50, while the internal player volume is 0.

**Your Enviroment**
 - SMPlayer version: 21.10.0
 - Multimedia engine you're using with SMPlayer (preferences -> general):
 [ ] MPlayer
 [/] MPV

Thank you.

**Comment by smplayer-dev** [comment]
This is normal, smplayer doesn't analyze the options you pass to mpv/mplayer in preferences -> advanced, so there could be inconsistencies in the interface. I won't fix this because it would be too complex to check for all options and I think it's not worth it.
