### ISSUE TITLE
Typo on the 'First steps with SMPlayer' page

### ISSUE THREAD

**Issue by adem4ik** [smplayer-dev/smplayer#334]
**Describe the bug**
It should be 'bottom' instead of 'botton'

**To Reproduce**
1. Open https://www.smplayer.info/en/first-steps
2. Scroll to 'Basic' - 'Play a movie file' section

**Expected behavior**
It should be 'You can use the control at the **bottom** of the player to pause it, rewind, seek...'

**Screenshots**
![image](https://user-images.githubusercontent.com/4707112/147614454-2363ec5f-9522-46ef-b7a1-74a1daa1e008.png)

**Comment by smplayer-dev** [comment]
Thanks for the report. It's fixed now.
