### ISSUE TITLE
Smplayer 21.1.0 does not play m3u files

### ISSUE THREAD

**Issue by semola** [smplayer-dev/smplayer#34]
Hello. 
I have windows 10 and linux ubuntu Os and the smplayer does not play .m3u files (iptv play list link).
I have done downgrade version 19.10 and the problem resolved.
In linux the problem exist yet.
Is there any solution?

**Comment by smplayer-dev** [comment]
Please send the logs after trying to play a m3u file.

**Comment by semola** [comment]
Linux Ubuntu
```

/usr/bin/mpv --no-config --no-quiet --terminal --no-msg-color --input-ipc-server=/tmp/smplayer-mpv-2557 --msg-level=ffmpeg/demuxer=error --no-fs --hwdec=no --sub-auto=fuzzy --no-input-default-bindings --input-vo-keyboard=no --no-input-cursor --cursor-autohide=no --no-keepaspect --wid=52428963 --monitorpixelaspect=1 --osd-level=1 --osd-scale=1 --osd-bar-align-y=0.6 --sub-ass --embeddedfonts --sub-ass-line-spacing=0 --sub-scale=1 --sub-font=Arial --sub-color=#ffffffff --sub-shadow-color=#ff000000 --sub-border-color=#ff000000 --sub-border-size=0.75 --sub-shadow-offset=2.5 --sub-font-size=50 --sub-bold=no --sub-italic=no --sub-margin-y=8 --sub-margin-x=20 --sub-codepage=ISO-8859-1 --sub-pos=100 --volume=55 --cache=auto --screenshot-template=cap_%F_%p_%02n --screenshot-format=jpg --screenshot-directory=/home/nikos/Pictures/smplayer_screenshots --audio-pitch-correction=yes --volume-max=110 --ytdl=no --term-playing-msg=MPV_VERSION=${=mpv-version:}
INFO_VIDEO_WIDTH=${=width}
INFO_VIDEO_HEIGHT=${=height}
INFO_VIDEO_ASPECT=${=video-params/aspect}
INFO_VIDEO_FPS=${=container-fps:${=fps}}
INFO_VIDEO_FORMAT=${=video-format}
INFO_VIDEO_CODEC=${=video-codec}
INFO_AUDIO_FORMAT=${=audio-codec-name}
INFO_AUDIO_CODEC=${=audio-codec}
INFO_AUDIO_RATE=${=audio-params/samplerate}
INFO_AUDIO_NCH=${=audio-params/channel-count}
INFO_LENGTH=${=duration:${=length}}
INFO_DEMUXER=${=current-demuxer:${=demuxer}}
INFO_SEEKABLE=${=seekable}
INFO_TITLES=${=disc-titles}
INFO_CHAPTERS=${=chapters}
INFO_TRACKS_COUNT=${=track-list/count}
METADATA_TITLE=${metadata/by-key/title:}
METADATA_ARTIST=${metadata/by-key/artist:}
METADATA_ALBUM=${metadata/by-key/album:}
METADATA_GENRE=${metadata/by-key/genre:}
METADATA_DATE=${metadata/by-key/date:}
METADATA_TRACK=${metadata/by-key/track:}
METADATA_COPYRIGHT=${metadata/by-key/copyright:}
INFO_MEDIA_TITLE=${=media-title:}
INFO_STREAM_PATH=${stream-path}
 --audio-client-name=SMPlayer --term-status-msg=STATUS: ${=time-pos} / ${=duration:${=length:0}} P: ${=pause} B: ${=paused-for-cache} I: ${=core-idle} VB: ${=video-bitrate:0} AB: ${=audio-bitrate:0} http://escape-iptv.com:8800/movie/semola/xxxxxxxxxx/48553.mp4

Failed to open http://escape-iptv.com:8800/movie/semola/xxxxxxxxxx/48553.mp4.
Exiting... (Errors when loading file)

```

**Comment by smplayer-dev** [comment]
I don't know, mpv fails to play the file but it doesn't say the reason.

**Comment by semola** [comment]
Before a few days was okay.
And my friend has the same problem.
With m3u8 files is okay. 
I will send you log file from win.

**Comment by smplayer-dev** [comment]
Enable the `verbose` option in preferences -> advanced -> logs. Maybe that way mpv will provide more info about the failure.

**Comment by semola** [comment]
C:/Users/semol/Downloads/smplayer-portable-21.1.0.0/mpv/mpv.exe --no-config --no-quiet --terminal --no-msg-color --input-ipc-server=C:/Users/semol/AppData/Local/Temp/smplayer-mpv-22b4 --msg-level=ffmpeg/demuxer=error -v --no-fs --hwdec=no --sub-auto=fuzzy --vo=direct3d, --priority=normal --no-input-default-bindings --input-vo-keyboard=no --no-input-cursor --cursor-autohide=no --no-keepaspect --wid=329420 --monitorpixelaspect=1 --osd-level=1 --osd-scale=1 --osd-bar-align-y=0.6 --sub-ass --embeddedfonts --sub-ass-line-spacing=0 --sub-scale=1 --sub-font=Arial --sub-color=#ffffffff --sub-shadow-color=#ff000000 --sub-border-color=#ff000000 --sub-border-size=0.75 --sub-shadow-offset=2.5 --sub-font-size=50 --sub-bold=no --sub-italic=no --sub-margin-y=8 --sub-margin-x=20 --sub-codepage=ISO-8859-1 --sub-pos=100 --volume=50 --cache=auto --screenshot-template=cap_%F_%p_%02n --screenshot-format=jpg --screenshot-directory=.\screenshots --audio-pitch-correction=yes --af-add=@aeq:lavfi=[firequalizer=gain='cubic_interpolate(f)':zero_phase=on:wfunc=tukey:delay=0.027:gain_entry='entry(0,0);entry(62.5,0);entry(125,0);entry(250,0);entry(500,0);entry(1000,0);entry(2000,0);entry(4000,0);entry(8000,0);entry(16000,0)'] --volume-max=100 --ytdl=no --term-playing-msg=MPV_VERSION=${=mpv-version:}
INFO_VIDEO_WIDTH=${=width}
INFO_VIDEO_HEIGHT=${=height}
INFO_VIDEO_ASPECT=${=video-params/aspect}
INFO_VIDEO_FPS=${=container-fps:${=fps}}
INFO_VIDEO_FORMAT=${=video-format}
INFO_VIDEO_CODEC=${=video-codec}
INFO_AUDIO_FORMAT=${=audio-codec-name}
INFO_AUDIO_CODEC=${=audio-codec}
INFO_AUDIO_RATE=${=audio-params/samplerate}
INFO_AUDIO_NCH=${=audio-params/channel-count}
INFO_LENGTH=${=duration:${=length}}
INFO_DEMUXER=${=current-demuxer:${=demuxer}}
INFO_SEEKABLE=${=seekable}
INFO_TITLES=${=disc-titles}
INFO_CHAPTERS=${=chapters}
INFO_TRACKS_COUNT=${=track-list/count}
METADATA_TITLE=${metadata/by-key/title:}
METADATA_ARTIST=${metadata/by-key/artist:}
METADATA_ALBUM=${metadata/by-key/album:}
METADATA_GENRE=${metadata/by-key/genre:}
METADATA_DATE=${metadata/by-key/date:}
METADATA_TRACK=${metadata/by-key/track:}
METADATA_COPYRIGHT=${metadata/by-key/copyright:}
INFO_MEDIA_TITLE=${=media-title:}
INFO_STREAM_PATH=${stream-path}
 --term-status-msg=STATUS: ${=time-pos} / ${=duration:${=length:0}} P: ${=pause} B: ${=paused-for-cache} I: ${=core-idle} VB: ${=video-bitrate:0} AB: ${=audio-bitrate:0} http://escape-iptv.com:8800/movie/semola/xxxxxx/47718.mp4

Command line options: '--no-config' '--no-quiet' '--terminal' '--no-msg-color' '--input-ipc-server=C:/Users/semol/AppData/Local/Temp/smplayer-mpv-22b4' '--msg-level=ffmpeg/demuxer=error' '-v' '--no-fs' '--hwdec=no' '--sub-auto=fuzzy' '--vo=direct3d,' '--priority=normal' '--no-input-default-bindings' '--input-vo-keyboard=no' '--no-input-cursor' '--cursor-autohide=no' '--no-keepaspect' '--wid=329420' '--monitorpixelaspect=1' '--osd-level=1' '--osd-scale=1' '--osd-bar-align-y=0.6' '--sub-ass' '--embeddedfonts' '--sub-ass-line-spacing=0' '--sub-scale=1' '--sub-font=Arial' '--sub-color=#ffffffff' '--sub-shadow-color=#ff000000' '--sub-border-color=#ff000000' '--sub-border-size=0.75' '--sub-shadow-offset=2.5' '--sub-font-size=50' '--sub-bold=no' '--sub-italic=no' '--sub-margin-y=8' '--sub-margin-x=20' '--sub-codepage=ISO-8859-1' '--sub-pos=100' '--volume=50' '--cache=auto' '--screenshot-template=cap_%F_%p_%02n' '--screenshot-format=jpg' '--screenshot-directory=.\screenshots' '--audio-pitch-correction=yes' '--af-add=@aeq:lavfi=[firequalizer=gain='cubic_interpolate(f)':zero_phase=on:wfunc=tukey:delay=0.027:gain_entry='entry(0,0);entry(62.5,0);entry(125,0);entry(250,0);entry(500,0);entry(1000,0);entry(2000,0);entry(4000,0);entry(8000,0);entry(16000,0)']' '--volume-max=100' '--ytdl=no' '--term-playing-msg=MPV_VERSION=${=mpv-version:}
[debug] INFO_VIDEO_WIDTH=${=width}
[debug] INFO_VIDEO_HEIGHT=${=height}
[debug] INFO_VIDEO_ASPECT=${=video-params/aspect}
[debug] INFO_VIDEO_FPS=${=container-fps:${=fps}}
[debug] INFO_VIDEO_FORMAT=${=video-format}
[debug] INFO_VIDEO_CODEC=${=video-codec}
[debug] INFO_AUDIO_FORMAT=${=audio-codec-name}
[debug] INFO_AUDIO_CODEC=${=audio-codec}
[debug] INFO_AUDIO_RATE=${=audio-params/samplerate}
[debug] INFO_AUDIO_NCH=${=audio-params/channel-count}
[debug] INFO_LENGTH=${=duration:${=length}}
[debug] INFO_DEMUXER=${=current-demuxer:${=demuxer}}
[debug] INFO_SEEKABLE=${=seekable}
[debug] INFO_TITLES=${=disc-titles}
[debug] INFO_CHAPTERS=${=chapters}
[debug] INFO_TRACKS_COUNT=${=track-list/count}
[debug] METADATA_TITLE=${metadata/by-key/title:}
[debug] METADATA_ARTIST=${metadata/by-key/artist:}
[debug] METADATA_ALBUM=${metadata/by-key/album:}
[debug] METADATA_GENRE=${metadata/by-key/genre:}
[debug] METADATA_DATE=${metadata/by-key/date:}
[debug] METADATA_TRACK=${metadata/by-key/track:}
[debug] METADATA_COPYRIGHT=${metadata/by-key/copyright:}
[debug] INFO_MEDIA_TITLE=${=media-title:}
[debug] INFO_STREAM_PATH=${stream-path}
' '--term-status-msg=STATUS: ${=time-pos} / ${=duration:${=length:0}} P: ${=pause} B: ${=paused-for-cache} I: ${=core-idle} VB: ${=video-bitrate:0} AB: ${=audio-bitrate:0}' 'http://escape-iptv.com:8800/movie/semola/xxxxxxx/47718.mp4'
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Mon Jan 27 12:34:40 +08 2020
ffmpeg library versions:
   libavutil       56.38.100
   libavcodec      58.67.100
   libavformat     58.36.100
   libswscale      5.6.100
   libavfilter     7.71.100
   libswresample   3.6.100
ffmpeg version: git-2020-01-26-5e6210015

Configuration: /home/shinchiro/build/build64/packages/mpv-stable-prefix/src/mpv-stable/waf configure --enable-static-build --enable-pdf-build --disable-manpage-build --enable-libmpv-shared --enable-lua --enable-javascript --enable-sdl2 --enable-libarchive --enable-libass --enable-libbluray --enable-dvdnav --enable-uchardet --enable-rubberband --enable-lcms2 --enable-openal --enable-spirv-cross --enable-vulkan --enable-vapoursynth --prefix=/home/shinchiro/build/build64/install/mingw
List of enabled features: asm atomics build-date cplayer cuda-hwaccel cuda-interop d3d-hwaccel d3d11 d3d9-hwaccel debug-build direct3d dos-paths drmprime dvdnav egl-angle egl-angle-win32 egl-helpers ffmpeg ffnvcodec gl gl-dxinterop gl-dxinterop-d3d9 gl-win32 glob glob-win32 gnuc gpl iconv javascript jpeg lcms2 libarchive libass libass-osd libav-any libavcodec libavdevice libavutil libbluray libm libmpv-shared libplacebo lua luajit mingw noexecstack openal optimize plain-gl posix-or-mingw rubberband sdl2 sdl2-audio sdl2-gamepad sdl2-video shaderc shaderc-static spirv-cross spirv-cross-static static-build stdatomic uchardet vapoursynth vulkan wasapi win32-desktop win32-internal-pthreads win32-pipes zlib
Setting option 'config' = 'no' (flags = 8)
Setting option 'quiet' = 'no' (flags = 8)
Setting option 'terminal' = '' (flags = 8)
Setting option 'msg-color' = 'no' (flags = 8)
Setting option 'input-ipc-server' = 'C:/Users/semol/AppData/Local/Temp/smplayer-mpv-22b4' (flags = 8)
Setting option 'msg-level' = 'ffmpeg/demuxer=error' (flags = 8)
Setting option 'v' = '' (flags = 8)
Setting option 'fs' = 'no' (flags = 8)
Setting option 'hwdec' = 'no' (flags = 8)
Setting option 'sub-auto' = 'fuzzy' (flags = 8)
Setting option 'vo' = 'direct3d,' (flags = 8)
Setting option 'priority' = 'normal' (flags = 8)
Setting option 'input-default-bindings' = 'no' (flags = 8)
Setting option 'input-vo-keyboard' = 'no' (flags = 8)
Setting option 'input-cursor' = 'no' (flags = 8)
Setting option 'cursor-autohide' = 'no' (flags = 8)
Setting option 'keepaspect' = 'no' (flags = 8)
Setting option 'wid' = '329420' (flags = 8)
Setting option 'monitorpixelaspect' = '1' (flags = 8)
Setting option 'osd-level' = '1' (flags = 8)
Setting option 'osd-scale' = '1' (flags = 8)
Setting option 'osd-bar-align-y' = '0.6' (flags = 8)
Setting option 'sub-ass' = '' (flags = 8)
Setting option 'embeddedfonts' = '' (flags = 8)
Setting option 'sub-ass-line-spacing' = '0' (flags = 8)
Setting option 'sub-scale' = '1' (flags = 8)
Setting option 'sub-font' = 'Arial' (flags = 8)
Setting option 'sub-color' = '#ffffffff' (flags = 8)
Setting option 'sub-shadow-color' = '#ff000000' (flags = 8)
Setting option 'sub-border-color' = '#ff000000' (flags = 8)
Setting option 'sub-border-size' = '0.75' (flags = 8)
Setting option 'sub-shadow-offset' = '2.5' (flags = 8)
Setting option 'sub-font-size' = '50' (flags = 8)
Setting option 'sub-bold' = 'no' (flags = 8)
Setting option 'sub-italic' = 'no' (flags = 8)
Setting option 'sub-margin-y' = '8' (flags = 8)
Setting option 'sub-margin-x' = '20' (flags = 8)
Setting option 'sub-codepage' = 'ISO-8859-1' (flags = 8)
Setting option 'sub-pos' = '100' (flags = 8)
Setting option 'volume' = '50' (flags = 8)
Setting option 'cache' = 'auto' (flags = 8)
Setting option 'screenshot-template' = 'cap_%F_%p_%02n' (flags = 8)
Setting option 'screenshot-format' = 'jpg' (flags = 8)
Setting option 'screenshot-directory' = '.\screenshots' (flags = 8)
Setting option 'audio-pitch-correction' = 'yes' (flags = 8)
Setting option 'af-add' = '@aeq:lavfi=[firequalizer=gain='cubic_interpolate(f)':zero_phase=on:wfunc=tukey:delay=0.027:gain_entry='entry(0,0);entry(62.5,0);entry(125,0);entry(250,0);entry(500,0);entry(1000,0);entry(2000,0);entry(4000,0);entry(8000,0);entry(16000,0)']' (flags = 8)
Setting option 'volume-max' = '100' (flags = 8)
Setting option 'ytdl' = 'no' (flags = 8)
Setting option 'term-playing-msg' = 'MPV_VERSION=${=mpv-version:}
[debug] INFO_VIDEO_WIDTH=${=width}
[debug] INFO_VIDEO_HEIGHT=${=height}
[debug] INFO_VIDEO_ASPECT=${=video-params/aspect}
[debug] INFO_VIDEO_FPS=${=container-fps:${=fps}}
[debug] INFO_VIDEO_FORMAT=${=video-format}
[debug] INFO_VIDEO_CODEC=${=video-codec}
[debug] INFO_AUDIO_FORMAT=${=audio-codec-name}
[debug] INFO_AUDIO_CODEC=${=audio-codec}
[debug] INFO_AUDIO_RATE=${=audio-params/samplerate}
[debug] INFO_AUDIO_NCH=${=audio-params/channel-count}
[debug] INFO_LENGTH=${=duration:${=length}}
[debug] INFO_DEMUXER=${=current-demuxer:${=demuxer}}
[debug] INFO_SEEKABLE=${=seekable}
[debug] INFO_TITLES=${=disc-titles}
[debug] INFO_CHAPTERS=${=chapters}
[debug] INFO_TRACKS_COUNT=${=track-list/count}
[debug] METADATA_TITLE=${metadata/by-key/title:}
[debug] METADATA_ARTIST=${metadata/by-key/artist:}
[debug] METADATA_ALBUM=${metadata/by-key/album:}
[debug] METADATA_GENRE=${metadata/by-key/genre:}
[debug] METADATA_DATE=${metadata/by-key/date:}
[debug] METADATA_TRACK=${metadata/by-key/track:}
[debug] METADATA_COPYRIGHT=${metadata/by-key/copyright:}
[debug] INFO_MEDIA_TITLE=${=media-title:}
[debug] INFO_STREAM_PATH=${stream-path}
' (flags = 8)
Setting option 'term-status-msg' = 'STATUS: ${=time-pos} / ${=duration:${=length:0}} P: ${=pause} B: ${=paused-for-cache} I: ${=core-idle} VB: ${=video-bitrate:0} AB: ${=audio-bitrate:0}' (flags = 8)
Waiting for scripts...
[ipc] Starting IPC master
[ipc] Listening to IPC pipe.
Set property: shared-script-properties -> 1
Set property: shared-script-properties -> 1
Set property: shared-script-properties -> 1
[osd/libass] Shaper: FriBidi 1.0.8 (SIMPLE) HarfBuzz-ng 2.6.4 (COMPLEX)
[osd/libass] Setting up fonts...
[osd/libass] Using font provider directwrite
[osd/libass] Done.
Done loading scripts.
[ffmpeg] Opening http://escape-iptv.com:8800/movie/semola/xxxxxx/47718.mp4
[osd/libass] Shaper: FriBidi 1.0.8 (SIMPLE) HarfBuzz-ng 2.6.4 (COMPLEX)
[osd/libass] Setting up fonts...
[osd/libass] Using font provider directwrite
[osd/libass] Done.
Set property: shared-script-properties -> 1
[stream] Failed to open http://escape-iptv.com:8800/movie/semola/xxxxxxx/47718.mp4.
Opening failed or was aborted: http://escape-iptv.com:8800/movie/semola/xxxxxxxx/47718.mp4
finished playback, loading failed (reason 4)


Exiting... (Errors when loading file)
Set property: shared-script-properties -> 1
Set property: shared-script-properties -> 1

**Comment by semola** [comment]
Tis is the log from 19.10 version.
This version playing okay on windows


C:/Program Files/SMPlayer/mpv/mpv.exe --no-config --no-quiet --terminal --no-msg-color --input-file=/dev/stdin --msg-level=ffmpeg/demuxer=error --no-fs --hwdec=no --sub-auto=fuzzy --vo=direct3d, --priority=normal --no-input-default-bindings --input-vo-keyboard=no --no-input-cursor --cursor-autohide=no --no-keepaspect --wid=459604 --monitorpixelaspect=1 --osd-level=1 --osd-scale=1 --osd-bar-align-y=0.6 --sub-ass --embeddedfonts --sub-ass-line-spacing=0 --sub-scale=1 --sub-font=Arial --sub-color=#ffffffff --sub-shadow-color=#ff000000 --sub-border-color=#ff000000 --sub-border-size=0.75 --sub-shadow-offset=2.5 --sub-font-size=50 --sub-bold=no --sub-italic=no --sub-margin-y=8 --sub-margin-x=20 --sub-codepage=ISO-8859-1 --sub-pos=100 --volume=38 --cache=auto --screenshot-template=cap_%F_%p_%02n --screenshot-format=jpg --screenshot-directory=C:\Users\semol\Pictures\smplayer_screenshots --audio-pitch-correction=yes --af-add=lavfi=[firequalizer=gain='cubic_interpolate(f)':zero_phase=on:wfunc=tukey:delay=0.027:gain_entry='entry(0,0);entry(62.5,0);entry(125,0);entry(250,0);entry(500,0);entry(1000,0);entry(2000,0);entry(4000,0);entry(8000,0);entry(16000,0)'] --volume-max=100 --ytdl --term-playing-msg=MPV_VERSION=${=mpv-version:}
INFO_VIDEO_WIDTH=${=width}
INFO_VIDEO_HEIGHT=${=height}
INFO_VIDEO_ASPECT=${=video-params/aspect}
INFO_VIDEO_FPS=${=container-fps:${=fps}}
INFO_VIDEO_FORMAT=${=video-format}
INFO_VIDEO_CODEC=${=video-codec}
INFO_AUDIO_FORMAT=${=audio-codec-name}
INFO_AUDIO_CODEC=${=audio-codec}
INFO_AUDIO_RATE=${=audio-params/samplerate}
INFO_AUDIO_NCH=${=audio-params/channel-count}
INFO_LENGTH=${=duration:${=length}}
INFO_DEMUXER=${=current-demuxer:${=demuxer}}
INFO_SEEKABLE=${=seekable}
INFO_TITLES=${=disc-titles}
INFO_CHAPTERS=${=chapters}
INFO_TRACKS_COUNT=${=track-list/count}
METADATA_TITLE=${metadata/by-key/title:}
METADATA_ARTIST=${metadata/by-key/artist:}
METADATA_ALBUM=${metadata/by-key/album:}
METADATA_GENRE=${metadata/by-key/genre:}
METADATA_DATE=${metadata/by-key/date:}
METADATA_TRACK=${metadata/by-key/track:}
METADATA_COPYRIGHT=${metadata/by-key/copyright:}
INFO_MEDIA_TITLE=${=media-title:}
INFO_STREAM_PATH=${stream-path}
 --term-status-msg=STATUS: ${=time-pos} / ${=duration:${=length:0}} P: ${=pause} B: ${=paused-for-cache} I: ${=core-idle} VB: ${=video-bitrate:0} AB: ${=audio-bitrate:0} http://escape-iptv.com:8800/semola/xxxxxxx/17

Playing: http://escape-iptv.com:8800/semola/xxxxxx/17
 (+) Video --vid=1 (h264 720x576 25.000fps)
 (+) Audio --aid=1 --alang=gre (mp2 2ch 48000Hz)
     Subs  --sid=1 --slang=gre (dvb_subtitle)
AO: [wasapi] 48000Hz 5.1 6ch float
VO: [direct3d] 720x576 => 1047x576 yuv420p
INFO_VIDEO_DSIZE=1047x576
MPV_VERSION=mpv 0.29.0-86-g880c59d189
INFO_VIDEO_WIDTH=720
INFO_VIDEO_HEIGHT=576
INFO_VIDEO_ASPECT=1.817708
INFO_VIDEO_FPS=25.000000
INFO_VIDEO_FORMAT=h264
INFO_VIDEO_CODEC=h264 (H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10)
INFO_AUDIO_FORMAT=mp2
INFO_AUDIO_CODEC=mp2 (MP2 (MPEG audio layer 2))
INFO_AUDIO_RATE=48000
INFO_AUDIO_NCH=2
INFO_LENGTH=13.342556
INFO_DEMUXER=lavf
INFO_SEEKABLE=no
INFO_TITLES=
INFO_CHAPTERS=0
INFO_TRACKS_COUNT=3
METADATA_TITLE=
METADATA_ARTIST=
METADATA_ALBUM=
METADATA_GENRE=
METADATA_DATE=
METADATA_TRACK=
METADATA_COPYRIGHT=
INFO_MEDIA_TITLE=17
INFO_STREAM_PATH=http://escape-iptv.com:8800/semola/xxxxxxxxx/17
INFO_TRACK_0: video 1 '' '' yes
INFO_TRACK_1: audio 1 'gre' '' yes
INFO_TRACK_2: sub 1 'gre' '' no

**Comment by smplayer-dev** [comment]
Does it play on Windows?
Maybe that URL is not available.

**Comment by semola** [comment]
No that url playing with 19.10 version on widows.
Even with vlc player.
Strange.

**Comment by smplayer-dev** [comment]
Version 19.10 on Windows is using mpv 0.29 while version 21.1 is using mpv 0.32. Maybe it's a bug in mpv 0.32. 
You can get other versions of mpv here: https://sourceforge.net/projects/mpv-player-windows/files/
You can try to replace version 0.32 supplied by smplayer 21.1 with another one and see if you find another version with the problem fixed.

**Comment by semola** [comment]
Yes.
You have right.
I replaced the mpv folder from 21.1 version by the mpv folder fron 19.10 version.
The issue resoved.
I must do something like that in linux. Maybe.
Thank you very much.
Best regards.

**Comment by smplayer-dev** [comment]
What version of Ubuntu are you using?

**Comment by semola** [comment]
20.10
The same happen in zorin 15

**Comment by smplayer-dev** [comment]
Ubuntu 20.10  includes mpv 0.32.
I think you can get version 0.33 from this PPA:
https://launchpad.net/~mc3man/+archive/ubuntu/mpv-tests?field.series_filter=groovy

**Comment by semola** [comment]
Still nothing.

**Comment by smplayer-dev** [comment]
Does it work if you play the video directly with mpv?
`mpv http://escape-iptv.com:8800/semola/xxxxxxxxx/17`

**Comment by semola** [comment]
no, does not play.
Mpv is closes.

**Comment by smplayer-dev** [comment]
Then it seems a bug in mpv. You can report it here: https://mpv.io/bug-reports
Does the url play if you use mplayer instead?

`mplayer http://escape-iptv.com:8800/semola/xxxxxxxxx/17`

**Comment by semola** [comment]
Yes but is not like mpv.
You say, to i choose mplayer in smplayer?

**Comment by smplayer-dev** [comment]
If mplayer works then you can use it in smplayer in preferences -> general.
Anyway as this actually seems a bug in mpv I'm closing the issue.
