### ISSUE TITLE
Other video default options in Windows are needed. Mpv defaults are superior

### ISSUE THREAD

**Issue by onetoomanyonesandzeroes** [smplayer-dev/smplayer#349]
I noticed watching a film first in mpv then in smplayer, that it looked poorer in the latter, more ashy, watered down, lacking in colour, contrast everything. So I dug into the video options and saw as default something, which after playing around with the other options available, I identified as '**direct3d**'. Changing this to **libmpv** or **gpu** made the video regain its quality.
Not many would dig into the options so it would be better to keep mpv defaults (brightness, contrast, colour). 
Glad you fixed it.

**Comment by smplayer-dev** [comment]
I changed the default to direct3d some time ago because some people reported problems with gpu (no image).
But I think I'll change it back to gpu anyway.

**Comment by smplayer-dev** [comment]
Fixed in https://github.com/smplayer-dev/smplayer/commit/8ea6f42925c8733992997f9baae16ffcd7ead42b
