### ISSUE TITLE
Selected play speed not save for entire playlist!

### ISSUE THREAD

**Issue by hamedsbt** [smplayer-dev/smplayer#35]
I'm using 21.1.0 rev.9475
I drag and drop a folder to smplayer and set play-speed to 1.4x but after end of play first file, the speed revert back to 1x, so I have to set play speed for each file on each play start. it's so annoying for my usage.
I know about keyboard shortcut and toolbar... but it's better the setting be stateful & independent on each application instance.
Thank you developers.

**Comment by halilbrhmtrn** [comment]
any updates ? if you don't have time i can do this with some guidance @smplayer-dev

**Comment by smplayer-dev** [comment]
It's not easy to fix this. But you can add `--speed=1.4` in preferences -> advanced -> options for mpv. That will play all videos at the specified speed.

**Comment by halilbrhmtrn** [comment]
yes i tried that but it throws error.

**Comment by smplayer-dev** [comment]
What error?

**Comment by halilbrhmtrn** [comment]
```
/usr/bin/mplayer -noquiet -slave -identify -nofs -sub-fuzziness 1 -nodr -double -nomouseinput -input nodefault-bindings:conf=/dev/null -nokeepaspect -wid 16777236 -monitorpixelaspect 1 -osdlevel 0 -subfont-osd-scale 3 -progbar-align 80 -ass -embeddedfonts -ass-line-spacing 0 -ass-font-scale 1 -noflip-hebrew -ass-styles /home/halilbrhmtrn/.config/smplayer/styles.ass -subcp ISO-8859-9 -subpos 100 -volume 39 -speed 1.3 -ss 8 -vf-add screenshot=/home/halilbrhmtrn/Pictures/smplayer_screenshots/shot -noslices -af-add scaletempo -softvol -softvol-max 110 --speed=1.4 /home/halilbrhmtrn/Downloads/

Unknown option on the command line: --speed=1.4
Error parsing option on the command line: --speed=1.4
MPlayer 1.3.0 (Debian), built with gcc-10 (C) 2000-2016 MPlayer Team
ID_EXIT=NONE
```


that's what i got when i try to add the ```--speed=1.4``` option

**Comment by smplayer-dev** [comment]
`--speed=1.4` is the option name for mpv. For mplayer you have to use `-speed 1.4`

**Comment by halilbrhmtrn** [comment]
Thank you! i thought i tried `-speed 1.4 `as well but apparently i was using like this `-speed=1.4`. So in case anyone still getting error make sure there is no `=` for mplayer.

**Comment by hamedsbt** [comment]
I have other issues (such as: resize window throw error and...) this application can be a good media player but not for while. I'll switch back to VLC because it's very stable. 
Thank you developers.
