### ISSUE TITLE
Option to display file name in window title

### ISSUE THREAD

**Issue by cheater** [smplayer-dev/smplayer#380]
**Describe the bug**
I keep my files named very meticulously. Unfortunately, a bunch of files have embedded titles, and SMPlayer always shows those in the window title instead. Those embedded file names are invariably something stupid, so it's more of a bug than a feature request, but of course feel free to re-categorize. I would like there to be an option that disables this behavior.

**Comment by smplayer-dev** [comment]
Go to preferences -> advanced, turn off "show tag info in window title".

**Comment by cheater** [comment]
That was it, thank you.

The name of this option doesn't suggest it would do what I was looking for. Can I suggest renaming this to "Show embedded media title in window title instead of file name"?
