### ISSUE TITLE
SMPlayer's Thumbnail generator fails [MPV/ZIMG ISSUE]

### ISSUE THREAD

**Issue by fredlkrue** [smplayer-dev/smplayer#40]
When I try to generate a thumbmail I get the error message displayed in the attached file.

Version: 21.1.0 (revision 9502)
Development version
Using Qt 5.12.8 (compiled with Qt 5.12.8)
Using MPV 0.33.0

![Screenshot from 2021-04-12 19-15-50](https://user-images.githubusercontent.com/66029769/114478803-bce5bc80-9bc4-11eb-89d0-5d326d10d1f8.png)

**Comment by smplayer-dev** [comment]
You didn't send the logs so I have no idea. But it works for me fine with smplayer r9555 and mpv 0.33.1.

**Comment by fredlkrue** [comment]
> You didn't send the logs so I have no idea. But it works for me fine with smplayer r9555 and mpv 0.33.1.

mpv log: https://pastebin.com/heNGmCRX
smplayer log: https://pastebin.com/a4K2M76w

**Comment by smplayer-dev** [comment]
Does it still fail if you select the option to extract frames as jpg instead of png?

**Comment by fredlkrue** [comment]
> Does it still fail if you select the option to extract frames as jpg instead of png?

It fails on both png and jpg.

**Comment by smplayer-dev** [comment]
What Linux distro are you using?

**Comment by fredlkrue** [comment]
Ubuntu 20.04 LTS

**Comment by smplayer-dev** [comment]
I've just tested on Ubuntu 20.04. The version of mpv provided by this distro is 0.32.0-1ubuntu1 and it works fine with the thumbnail generator. 

Did you get mpv 0.33.0 from a PPA or something?

I've just tested with mpv 0.33.0 from https://launchpad.net/~mc3man/+archive/ubuntu/mpv-tests, it still works fine for me.

**Comment by fredlkrue** [comment]
I am using the version from that PPA: mc3man/mpv-tests

**Comment by smplayer-dev** [comment]
I tested that version and it works fine for me. Do you have this problem with all videos?

**Comment by fredlkrue** [comment]
Yes it happens with all videos. I even tested with fresh SMPlayer settings but it still happens.

**Comment by smplayer-dev** [comment]
Does this command work for you? It should create a file named 00000001.png in the /tmp folder.

`/usr/bin/mpv --no-config --no-audio --no-cache --hr-seek=yes --sid=no --frames=1 --framedrop=no --start=20 --vo-image-format=png --vo-image-outdir=/tmp/ --vo=image --vo-image-png-compression=0 /media/ext3/1916690478.mp4`

**Comment by fredlkrue** [comment]
> Does this command work for you? It should create a file named 00000001.png in the /tmp folder.
> 
> `/usr/bin/mpv --no-config --no-audio --no-cache --hr-seek=yes --sid=no --frames=1 --framedrop=no --start=20 --vo-image-format=png --vo-image-outdir=/tmp/ --vo=image --vo-image-png-compression=0 /media/ext3/1916690478.mp4`

I get the following:

/usr/bin/mpv --no-config --no-audio --no-cache --hr-seek=yes --sid=no --frames=1 --framedrop=no --start=20 --vo-image-format=png --vo-image-outdir=/tmp/ --vo=image --vo-image-png-compression=0 /media/ext3/1916690478.mp4
 (+) Video --vid=1 (*) (h264 1920x1080 25.000fps)
     Audio --aid=1 (*) (aac 2ch 48000Hz)
[vo/image] Creating output directory '/tmp/'...
VO: [image] 1920x1080 yuv420p
[vo/image] Saving /tmp/00000001.png
mpv: ../video/zimg.c:241: repack_entrypoint: Assertion `!(i & (mp_repack_get_align_y(r->repack) - 1))' failed.
Aborted (core dumped)

**Comment by smplayer-dev** [comment]
Then it's a problem in mpv or in one of the libraries it uses.

**Comment by fredlkrue** [comment]
I see, thanks for your help.

**Comment by smplayer-dev** [comment]
The problem was already [reported](http://old-forum.smplayer.info/viewtopic.php?p=23758&sid=db15a8d09197fc7702a27daa1b688098#p23758)  some months ago in the old forum. It seems a bug in the zimg library.

**Comment by fredlkrue** [comment]
Ok, not a big deal. I will just wait for an update. Thanks!

**Comment by fredlkrue** [comment]
Installing **mpv_0.33.1+wsl.1_amd64.deb** from https://non-gnu.uvt.nl/debian/focal/mpv/ fixes my issue.
