### ISSUE TITLE
Main toolbar get locked

### ISSUE THREAD

**Issue by korongmambu** [smplayer-dev/smplayer#404]
**Describe the bug**
Main toolbar get locked on top after upgrade

**To Reproduce**
1. Upgrade to latest version
2. Main toolbar just move automatically to top (before in mine on left side)
3. And can't be move again to the left side

**Expected behavior**
Main toolbar can be move again to left side

**Your Enviroment**
 - SMPlayer version: 22.2.0
 - OS: Arch Linux
 - Multimedia engine you're using with SMPlayer (preferences -> general): MPV

**Comment by smplayer-dev** [comment]
I see. Maybe a bug in the Qt package in Arch Linux. Try using a snap or flatpak package, I think those packages don't have this problem.
https://www.smplayer.info/install-snap-flatpak-appimage.php

**Comment by korongmambu** [comment]
You're right, I've installed smplayer from flatpak and main toolbar can be move again. Thanks!
