### ISSUE TITLE
The sound doesn't work

### ISSUE THREAD

**Issue by guglovich** [smplayer-dev/smplayer#409]
**Describe the bug**
The sound doesn't work

**To Reproduce**
Start any audio or video file

**Expected behavior**
There has to be sound and there has to be a visualisation in the mixer. But the mixer doesn't even show that sound is running in the app (screenshot below).

**Screenshots**
![Снимок экрана_2022-03-12_18-28-37](https://user-images.githubusercontent.com/54148165/158024486-b6901017-2a16-4a1f-92f2-0fc049fb99d4.png)

**Your Enviroment**
 - SMPlayer version: 22.2.0
 - OS: Arch Rolling
 - Multimedia engine you're using with SMPlayer (preferences -> general): Other
 [ ] MPlayer
 [ ] MPV

**Logs**
[log.txt](https://github.com/smplayer-dev/smplayer/files/8237865/log.txt)

**Comment by smplayer-dev** [comment]
I don't see any error in the log, so I don't know.
Try selecting another audio output in preferences -> general -> audio.

**Comment by guglovich** [comment]
> I don't see any error in the log, so I don't know.
> Try selecting another audio output in preferences -> general -> audio.

Tried all the options.

**Comment by smplayer-dev** [comment]
I don't know. Have you tried to change the audio device in the menu _Audio -> Send audio to_?

**Comment by guglovich** [comment]
> I don't know. Have you tried to change the audio device in the menu _Audio -> Send audio to_?

Yes, I did. I've tried every possible option. Neither headphones nor two pairs of speakers turned on. And I have three devices plugged in, none of the three have received sound.

**Comment by smplayer-dev** [comment]
Does the audio work if you play a file directly with mpv?

**Comment by guglovich** [comment]
Yes, there is sound through mpv

**Comment by smplayer-dev** [comment]
The audio should work on smplayer as well. Check if smplayer is muted in the system mixer or something.

**Comment by guglovich** [comment]
Attaching a video demonstration
https://user-images.githubusercontent.com/54148165/159737476-68c0fc28-d334-4b5a-a39a-f2d0ffaa54a0.mp4

**Comment by guglovich** [comment]
The problem is solved. You had to turn the volume slider. Apparently there's a rare bug with the volume switching or display, as it was set to maximum, as you can see in the video.
