### ISSUE TITLE
SMplayer adds unnecessary black bars

### ISSUE THREAD

**Issue by jimmy-1000** [smplayer-dev/smplayer#41]
**English**
When the video has a higher resolution than monitor, SMplayer adds unnecessary black bars. Other players like mpv don't add these bars. I use Windows 7 but this bug is shown in all systems.

**Español**
Cuando el vídeo tiene una resolución mayor a la del monitor, SMplayer agrega barras negras innecesarias, cuanto mayor es la resolución del vídeo, más grandes son las barras. Otros reproductores como el mismo mpv, no agregan estas barras.

![1](https://user-images.githubusercontent.com/78575427/114486235-b6f2da00-9bca-11eb-880a-7810a946e313.jpg)
![2](https://user-images.githubusercontent.com/78575427/114486239-b78b7080-9bca-11eb-9368-9ada0ebdef12.jpg)

**Comment by smplayer-dev** [comment]
¿Sigue pasando si pones la opción "Ajuste automático del tamaño" en "Siempre que sea necesario" en preferencias -> interfaz?

**Comment by jimmy-1000** [comment]
> 
> 
> ¿Sigue pasando si pones la opción "Ajuste automático del tamaño" en "Siempre que sea necesario" en preferencias -> interfaz?

Hola don Ricardo, sí ahí está en "Ajuste automático->Siempre que sea necesario". Si usted no ha visto esto, se puede deber a que usted usa un monitor de muy alta resolución y los videos que ha reproducido son de resolución menor a la del monitor. Olvidé decir que estoy usando un monitor 720, y esos vídeos que puse de ejemplo son 1080.  Si uso un monitor 1080, las barras negras disminuyen un poco y si usara un monitor 4K, las barras ya no aparecen. Si reproduzco cualquier vídeo con resolución por debajo de 720 (o el monitor que esté usando) no aparecen barras negras. Como decía, arriba, SMplayer agrega barras negras cuando el vídeo tiene una resolución igual o mayor al vídeo que se esté usando.

**Comment by smplayer-dev** [comment]
Prueba a desactivar la opción "Evitar que la ventana quede fuera de la pantalla".

**Comment by jimmy-1000** [comment]
No funciona, de hecho ya he probado todas las opciones; aquí otras capturas de un mismo vídeo resolución 1080 en un monitor 1280x720 reproducido en smplayer, mpv y media player clasic:

**SMplayer**

![smplayer](https://user-images.githubusercontent.com/78575427/114595552-c0705680-9c4b-11eb-885a-9e410f98823f.jpg)


**mpv**

![mpv](https://user-images.githubusercontent.com/78575427/114595729-f281b880-9c4b-11eb-8f00-ef6dc04927cb.jpg)


**MPC-HC**

![mpc](https://user-images.githubusercontent.com/78575427/114595796-01686b00-9c4c-11eb-9afd-e2d4597d9b8e.jpg)

**Comment by jimmy-1000** [comment]
Este sujeto comenta el mismo problema aquí http://old-forum.smplayer.info/viewtopic.php?f=2&t=8903
pero no le dio el título correcto ya que él cree que la relación de aspecto tiene algo que ver, pero no es así.

**Comment by smplayer-dev** [comment]
He intentado solucionarlo en la [versión 21.1.0.9594](https://github.com/smplayer-dev/smplayer/releases/tag/v21.1.0.9594) ¿puedes probarla?

**Comment by jimmy-1000** [comment]
> 
> 
> He intentado solucionarlo en la [versión 21.1.0.9594](https://github.com/smplayer-dev/smplayer/releases/tag/v21.1.0.9594) ¿puedes probarla?

¡Lo lograste arreglar Ricardo! Qué carga, pura vida, muchas gracias 👌

![foto](https://user-images.githubusercontent.com/78575427/115769187-7e8c9200-a368-11eb-9663-3949267dec23.jpg)
