### ISSUE TITLE
A minor typo in the greek translation

### ISSUE THREAD

**Issue by pitsi** [smplayer-dev/smplayer#419]
**Describe the bug**
There is a minor typo at the greek translation of the update notification dialog.

**To Reproduce**
1. Use windows (any version) with a greek locale and an outdated version of smplayer
2. Launch smplayer 
3. Go to help > check for updates

**Expected behavior**
The text on the last line should read "Θέλετε να μάθετε..." instead of "Θέλενε τα μαθετε..."

**Screenshots**
![thelene](https://user-images.githubusercontent.com/5880037/159335628-3ad092fc-869a-4a50-ba35-abe21769fb68.jpg)

**Your Enviroment**
 - SMPlayer version: 22.2 (pictured is 21.10, right before the uprade to 22.2)
 - OS: Windows 7
 - Multimedia engine you're using with SMPlayer (preferences -> general):
 [x] MPlayer
 [ ] MPV

**Logs**
Not needed,

**Additional context**
I searched the source code so as to find the relevant line in any file and just tell you where is the typo, but I could not find it.
I also don't know if smplayer can have a different locale than the os it is installed in.
It's something minor, but I reported it because it sounds funny and like it is pronounced in greek rural areas. My granpa would probably pronounce it like so :D

**Comment by smplayer-dev** [comment]
The Greek translation files are here:
https://www.transifex.com/rvm/smplayer/language/el/

**Comment by pitsi** [comment]
That link gets me to a 404 page of transifex. Do I need a transifex account to see it?
Likewise, there is no clickable language in 
https://www.transifex.com/rvm/smplayer/

**Comment by smplayer-dev** [comment]
I think I fixed it: https://github.com/smplayer-dev/smplayer/commit/9eb923e00449e801997a7535f5cbe6610514dae0

**Comment by pitsi** [comment]
Thank you very much!
I am now closing this.
