### ISSUE TITLE
QUESTION: What does the [reminder] count= setting in smplayer.ini do?

### ISSUE THREAD

**Issue by ghost** [smplayer-dev/smplayer#437]
```
[reminder]
count=2473
```

This setting confuses me, it seems to increase when I open SMPlayer but other than that it doesn't seem useful for anything else.

Also, is there a way to stop this number from going up? The reason is that I'm trying to put this file in a git repo but this would just keep introducing meaningless changes for git.

**Comment by smplayer-dev** [comment]
It counts the times you open smplayer.
You can turn it off by commenting the line `#define DONATE_REMINDER` in basegui.h and recompiling.

**Comment by ghost** [comment]
> and recompiling

Okay, I guess I have to exclude this file.
