### ISSUE TITLE
SMPlayer stopped choosing audio track after python-markdown & python-setuptools updated

### ISSUE THREAD

**Issue by rado84-github** [smplayer-dev/smplayer#443]
Edited (after I found which packages cause the problem):

**Describe the bug**
 SMPlayer stopped choosing prefered adio track after 2 python packages updated: python-markdown && python-setuptools.

**To Reproduce**
1. Set SMPlayer to choose prefered audio track to whatever you want, like eng, for example.
2. Update these two packages: python-markdown && python-setuptools.
3. Run any mkv video file which contains different languages and see that it doesn't choose eng as audio track.

**Your Enviroment**
 - SMPlayer version: 22.2.0-1
 - OS: Arch LTS
 - Multimedia engine you're using with SMPlayer: MPV.

**Comment by smplayer-dev** [comment]
I don't think this is a bug of smplayer. The track selection is done by mpv. Also smplayer doesn't use python.

**Comment by rado84-github** [comment]
> I don't think this is a bug of smplayer. The track selection is done by mpv. Also smplayer doesn't use python.

SMP may not be using python but it's using gcc-libs and glibc and python is their dependency. So somehow, indirectly, SMP depends on python. It is a fact that after updating the two packages in the title SMP stopped choosing the audio track. I tested it twice before updating the title and the report content.
AFAIK mpv is just a player with no settings whatsoever. The audio track selection setting is in SMP, not in mpv, which makes me think it's SMP that does the selection.

**Comment by smplayer-dev** [comment]
SMPlayer just passes to mpv your preferred audio and subtitle language using the mpv options `--alang` and `--slang`.

**Comment by rado84-github** [comment]
I understand. Well, whatever the cause of this problem, one fact remains unchanged - adding the said two packages to pacman's ignore list and preventing them from ever updating fixed the problem.
Still, I'll report the problem to the mpv developer, if they're on github.

**Comment by raszpl** [comment]
> AFAIK mpv is just a player with no settings whatsoever.

its quite powerful player with plenty of scripting support, but afaik it supports Lua and not python.

> 1. Set SMPlayer to choose prefered audio track to whatever you want, like eng, for example.

preferred audio track from what source? maybe whatever you are playing is being generated with python on your system?

**Comment by rado84-github** [comment]
> > AFAIK mpv is just a player with no settings whatsoever.
> 
> its quite powerful player with plenty of scripting support, but afaik it supports Lua and not python.
> 
> > 1. Set SMPlayer to choose prefered audio track to whatever you want, like eng, for example.
> 
> preferred audio track from what source? maybe whatever you are playing is being generated with python on your system?

I fixed the problem long ago. As it turned out at a later point, for an unknown reason the source (a MKV container) didn't have any metadata files which would help not only for mediainfo to read the info but that data absence was the reason for SMPlayer not being able to read the audio track labels. You know, MKVs usually come with at least 1 audio track and each is labeled "ENG", "RUS" and so on. But without the metadata SMP can't read these labels and displays all tracks as "Unknown". I fixed the problem by downloading another release of that TV show's season - one that had metadata. However, strangely enough, before I found the real cause of the problem, downgrading these two packages I mentioned somehow reversed it.

But to answer your question - I doubt it was python generated. The source has always been the same in the past 7 years: a MKV container and I doubt there's any python involved in it.

**Comment by raszpl** [comment]
smplayer is fully standalone and doesnt use any shared libraries. It must of been compounding of factors that led you astray, perhaps you redownloaded that show in parallel with downgrading python libraries, or you used something like unpacked youtube-dl (its a python tool and can be run using local python interpreted).

In any case sounds like this is not smplayer bug and can be closed.
