### ISSUE TITLE
Support for screenshots in the WebP format

### ISSUE THREAD

**Issue by arisboch** [smplayer-dev/smplayer#450]
I know that mpv, the backend player SMPlayer uses, can save in the WebP format as well, but SMPlayer, at least the Linux version (I use  version 21.10.0 (revision 10000) using Qt 5.15.3 (compiled with Qt 5.15.2) and MPV 0.34.1), doesn't give that option to choose (the dropdown menu has only "png", "ppm", "pgm", "pgmyuv", "tga", "jpg" and "jpeg" (aren't the last two options not basically the same thing?)). It'd be nice, if SMPlayer would let the user choose WebP as a screenshot file format, as well.

**Comment by smplayer-dev** [comment]
It should be fixed now.
https://github.com/smplayer-dev/smplayer/commit/cc89762ae55a2051e785ffb0fec514900160b264

**Comment by arisboch** [comment]
Thx!
