### ISSUE TITLE
Typos in First steps guide on the site

### ISSUE THREAD

**Issue by adem4ik** [smplayer-dev/smplayer#468]
**Describe the bug**
There is a typo on https://www.smplayer.info/en/first-steps :  `To play a Youtube video, just select Youtube browser in the Options menu.`

**To Reproduce**
1. Open https://www.smplayer.info/en/first-steps

**Expected behavior**
To play a Youtube video, just select **Youtube browser** in the **View** menu.

**Screenshots**
![image](https://user-images.githubusercontent.com/4707112/175813451-1160afbe-b492-43ed-bc99-73e817559866.png)
![image](https://user-images.githubusercontent.com/4707112/175813428-b369f715-4fef-41a0-abe6-3003f2b75b2b.png)

**Your Enviroment**
N/A

**Logs**
N/A

**Additional context**
Also there is another string on Transifex with this typo, but I couldn't find its actual placement on the site:
`To play or download a Youtube video, just select Youtube browser in the Options menu.`

**Comment by smplayer-dev** [comment]
I think this is fixed now.
