### ISSUE TITLE
Remove KDE from desktop-file categories

### ISSUE THREAD

**Issue by prettyv** [smplayer-dev/smplayer#49]
**Describe the bug**
SMPlayer specifies ```KDE``` in the Categories field of its .desktop file, leading KDE file managers like Dolphin to treat SMPlayer as kio-aware and passing opened files via URL for all protocols kio supports, like ```smb```. When using mpv as the player backend this works fine as long as ffmpeg is built with support for these protocols, but on Arch Linux this isn't true, and won't be, at least for smb (https://bugs.archlinux.org/task/69798).

I wonder why this was added originally?

**To Reproduce**
1. In Dolphin, under Arch Linux, navigate to a folder on a SMB-share containing multimedia files.
2. Open any video/audio file with SMPlayer
3. SMPlayer fails with error: ```[ffmpeg] Protocol not found. Make sure ffmpeg/Libav is compiled with networking support.
Failed to open smb://@server.local:445/Videos/example.mkv.```

**Expected behavior**
SMPlayer plays the video/audio file just fine, because Dolphin doesn't assume SMPlayer is a KDE app and passes a ```file://``` URL instead.

**Your Enviroment**
 - SMPlayer version: 21.1.0
 - OS: Arch Linux (up-to-date)
 - Multimedia engine you're using with SMPlayer (preferences -> general):
 [ ] MPlayer
 [x] MPV

**Logs**
[smplayer.log](https://github.com/smplayer-dev/smplayer/files/6319476/smplayer.log)

**Comment by smplayer-dev** [comment]
It was probably added because someone else requested. However that was many years ago so I don't remember the reason.

Found it:
https://sourceforge.net/p/smplayer/bugs/485/

**Comment by prettyv** [comment]
I see, kio-fuse which has been released this last year set out to solve exactly the problem the referenced bug talks about at the right place, i.e. KDE's ecosystem itself. Claiming to be a KDE app when you can't guarantee to support the same set of protocols at this point hurts more than it helps, insofar as it was ever more than a workaround (using ```X-KDE-Protocols``` would have been more semantically useful, although I'm not sure about the exact situation in 2012 of course).

**Comment by smplayer-dev** [comment]
So what modification do you propose?

**Comment by prettyv** [comment]
I propose just removing ```KDE``` from the Categories field again, as stated in the issue title.
