### ISSUE TITLE
Does this guide still applicable?

### ISSUE THREAD

**Issue by ghost** [smplayer-dev/smplayer#528]
https://cyberraidentech.blogspot.com/2021/01/smplayer-best-settings.html

I found and started to follow it a long time ago. Today I checked the log of SMPlayer and MPV and I found d3d11va-copy is always failed to initialize. This made me shocked. I have followed this guide for a very long time and I really think it gives me the best experience.

BTW, I'm on Windows 8.1 64 bit. SMPlayer and MPV are latest.

**Comment by raszpl** [comment]
is it abailable in the system? Why not set it to auto and let mpv select the best one?

**Comment by ghost** [comment]
> is it abailable in the system? Why not set it to auto and let mpv select the best one?

It's definitely available on the system. No idea why it failed to initialize. BTW, I will reset everything to use default setting.
