### ISSUE TITLE
Missing interface styles [ver. 21.1.0.9576]

### ISSUE THREAD

**Issue by Matthaiks** [smplayer-dev/smplayer#53]
**Describe the bug**
WindowsXP and WindowsVista styles are missing from the latest development version.

**To Reproduce**
1. Go to SMPlayer - Preferences - Interface
2. Click on 'Style:'
3. See limited list of styles

**Expected behavior**
Possibility to choose missing styles.

**Screenshots**

Stable version:
![Stable](https://user-images.githubusercontent.com/3577122/115219881-3a02bb80-a108-11eb-9591-60289a07cb21.png)

Development version:
![Dev](https://user-images.githubusercontent.com/3577122/115220152-82ba7480-a108-11eb-8a5e-7b5e1cf8f1a3.png)

**Your Enviroment**
 - SMPlayer version: 21.1.0.9576
 - OS:  Windows 10
 - Multimedia engine you're using with SMPlayer (preferences -> general):
 [ ] MPlayer
 [X] MPV

**Additional context**
IMHO, "WindowsVista" is the best style for Windows 10 as it makes SMPlayer to look more like a native app. The "Windows" style looks very outdated, like from Windows 2000.

**Comment by smplayer-dev** [comment]
The WindowsVista style is back but I think the WindowsXP style has been removed from Qt.
