### ISSUE TITLE
MicrosoftStore version still 21.10

### ISSUE THREAD

**Issue by ivysrono** [smplayer-dev/smplayer#537]
[SMPlayer for Windows - Microsoft Store](https://apps.microsoft.com/store/detail/smplayer-for-windows/9N80Q5M0QXW6)

**Comment by jobukkit** [comment]
Still hasn't been updated a year later.

**Comment by freispiel** [comment]
Is there any reason why the store version has never been updated since it was originally uploaded in October 2021?
Do you need any kind of support to update the store version with every new release, @smplayer-dev?

**Comment by smplayer-dev** [comment]
I'll try to fix it.

**Comment by smplayer-dev** [comment]
Done.

**Comment by ivysrono** [comment]
It is v23.12 now.

**Comment by Vorvalk** [comment]
Make latest version 24.5 available in store please. Thank you.

**Comment by smplayer-dev** [comment]
Isn't 24.5 already in the store?

**Comment by Vorvalk** [comment]
Hello,

No at this point the installed version is 23.12.0
[cid:a2bf6949-d3ae-42eb-b9ad-09417895edb9]

[cid:c125aa1c-5c04-40b8-ac09-a5c7d1332bb6]
________________________________
