### ISSUE TITLE
Launch mpv with custom commands using smplayer

### ISSUE THREAD

**Issue by goyalyashpal** [smplayer-dev/smplayer#559]
**Problem**
Required some way of using smplayer via remote from other device like via [mpvremote android app](https://f-droid.org/packages/miccah.mpvremote/)

**Describe the solution you'd like**
mpv already has some stuff for being controlled from external programs: refer [the mpv documentation](https://mpv.io/manual/master/#using-mpv-from-other-programs-or-scripts)

So, having an ability to launch mpv with some custom options (`--input-ipc-server` in this case):
* either with smplayer i.e. say from cli etc 
* or from within smplayer
* ... or other such

**Describe alternatives you've considered**
Dedicated remote implementation lol, but that's not needed i guess if one implementation of remote already exists

**Additional context**
Version: 22.7.0 (revision 10091) (64-bit)
Using Qt: 5.15.2 (compiled with Qt 5.15.2)
Using MPV: 0.34.0

**Comment by smplayer-dev** [comment]
You can use the [mpris interface](https://specifications.freedesktop.org/mpris-spec/latest/) to control smplayer from another application.

**Comment by goyalyashpal** [comment]
* thanks for the info, 
* but the problem there - for the time being - would be that i couldn't find any mpris interface based remote ...
* on either of the fdroid compatible repos like: f-droid official, izzy on droid, and several others

so, still is there a way to acomplish the above asked?
