### ISSUE TITLE
How much data will be written when "Remember time position" is enabled?

### ISSUE THREAD

**Issue by playgithub** [smplayer-dev/smplayer#581]
e.g.
When "Remember time position" is enabled and play a video of 1 hour, how much data will be written to disk totally for the function.

**Comment by smplayer-dev** [comment]
About 1.5 - 2 Kb for each file you play.

**Comment by playgithub** [comment]
> About 1.5 - 2 Kb for each file you play.

It should depends on the time of the video/audio, right?

**Comment by playgithub** [comment]
I've tried to find the code, but failed, any help?
