### ISSUE TITLE
Docked playlist doesn't visually update after coming back from fullscreen

### ISSUE THREAD

**Issue by DaviMedrade** [smplayer-dev/smplayer#604]
**Describe the bug**
After entering and then leaving fullscreen, the playlist stops showing updates like scrolling and selection.

**To Reproduce**
1. Open SMPlayer. If the playlist is not visible, enable it with Ctrl+L (or View → Playlist).
2. Open a playlist, or add files to the default empty playlist.
3. Check that the playlist window shows in real time when you click on a file or scroll the list of files.
4. Before you start playing any video, go to fullscreen, then leave fullscreen.
5. Check that the playlist window still works as described in step 3 above.
6. Start playing a video, go to fullscreen, then leave fullscreen.
7. Check that, now, if you click on a file on the playlist or scroll the list, it remains visually static (the list of files doesn't scroll despite the scrollbar showing that the scroll action was recognized, and when you click on a file it is not highlighted).
8. If you enter and leave fullscreen mode again, then the playlist will be repainted (the list of files will be repainted according to the last scrolling action, and the last file that was clicked will be highlighted), but the issue described in item 7 persists (clicking on another file won't highlight it, for example, until you enter and leave fullscreen mode again).

**Expected behavior**
After leaving fullscreen mode, the playlist should continue to work as described in step 3 above.

**Your Enviroment**
 - SMPlayer version: 22.7.0 from the Ubuntu PPA - Using Qt 5.15.6 (compiled with Qt 5.15.3)
 - OS: Ubuntu 22.10
 - Multimedia engine you're using with SMPlayer (preferences -> general): mpv compiled from source using mpv-build; NVIDIA binary drivers (520). The issue happens with any vo (I tested with gpu, gpu-next, xv, x11, and vdpau).

**Additional context**
Note that the issue is triggered not by going into fullscreen per se, but by going into fullscreen after a video has started playing (even if it's paused or stopped).

This might be related to #591, if the main issue there is in fact the one described in my comment there (if it's not, I can file a new issue for that problem).

**Comment by sleeksorrow** [comment]
Can confirm on Ubuntu 22.10 with KDE Plasma 5.26.4 with SMPlayer version: 22.7.0 from PPA and self compiled

**Comment by sleeksorrow** [comment]
I can also trigger this bug by activating and deactivating compact mode (ctrl-c)

**Comment by sleeksorrow** [comment]
Also for this bug, flatpak version is not affected, but it's quite dated.
https://flathub.org/apps/details/info.smplayer.SMPlayer

**Comment by DaviMedrade** [comment]
Edited to add: Using Qt 5.15.6 (compiled with Qt 5.15.3)

**Comment by sleeksorrow** [comment]
This is driving me mad already.... the flatpak version is no real workaround for me as I have trouble using my self compiled mpv with it

**Comment by DaviMedrade** [comment]
This problem seems to have gone away once I updated to Ubuntu 23.04.

The About screen shows:
Version: 22.7.0 (revision 10091)
Using Qt 5.15.8 (compiled with Qt 5.15.6)

**Comment by DaviMedrade** [comment]
@sleeksorrow do you intend to update to 23.04? If so I'll wait until you can validate that it fixes this for you as well before closing this issue (if the repo owner doesn't do it before that).

**Comment by sleeksorrow** [comment]
Can confirm this is resolved for me with Ubuntu 23.04. What a bliss.
