### ISSUE TITLE
Feature Request: better handling of seek bar dragging on Windows

### ISSUE THREAD

**Issue by sdugoten** [smplayer-dev/smplayer#687]
**Is your feature request related to a problem? Please describe.**
Right now, you will have to click precisely on the seek bar that "little vertical bar" in order to allow you to drag backward or forward.   If you are on windows with high resolution, you will really need to click carefully in order to click right on top of that little vertical bar.

![image](https://user-images.githubusercontent.com/7108552/228381783-aad37935-afa8-4477-a4bd-69d9fc2a1903.png)

**Describe the solution you'd like**
For other video player, you don't have to precisely click on the little vertical bar in order to allow you to drag back and forth.  It would be nice if you can click anywhere on the seek bar and still allow you to drag backward and forward.

**Comment by BenjaminRi** [comment]
Note that this seems to happen on Linux as well and probably on all platforms.

This is a very old issue: http://old-forum.smplayer.info/viewtopic.php?f=2&t=8612

Still seems unfixed. The volume slider is also affected. You can work around it by double-clicking which mostly works, but it's still annoying, especially on shorter videos where the seeker knob jumps during playback.
