### ISSUE TITLE
Releases built for Debian are for oldstable Buster - build for stable distribution

### ISSUE THREAD

**Issue by dougK44883** [smplayer-dev/smplayer#718]
**Is your feature request related to a problem? Please describe.**
Awesome you build releases for Debian Linux.  Debian 10 - Buster is no longer the stable distribution - https://wiki.debian.org/DebianBuster it's now know as oldstable.  
**Describe the solution you'd like**
A release of smplayer from smplayer-dev for Debian 11 - Buster aka stable.
**Describe alternatives you've considered**
From time to time there are issues with different repositories `http://download.opensuse.org/repositories/home:` and expired keys - not just smplayer.  github sends out email notices when there's a new release, so I can update then... manually.
**Additional context**
I've been using smplayer for almost 10yrs now!!  It's customizable UI makes it the best!  (yes I click on the donate button from time to time) THANKS

**Comment by smplayer-dev** [comment]
Please check if this package for Debian 11 works for you (the artifact at the bottom):
https://github.com/smplayer-dev/smplayer/actions/runs/5103832991

**Comment by dougK44883** [comment]
Installs and see no issues - again big THANKS
![image](https://github.com/smplayer-dev/smplayer/assets/42115699/f6f3bbf5-b2fb-4788-a796-ff6cc5aa53d7)

(looks like your date looks, uh, outdated)

**Comment by dougK44883** [comment]
On June 08 it was announced [Debian 12 "bookworm" released](https://www.debian.org/News/2023/20230610).... So now [bullsesys is oldstable](https://wiki.debian.org/DebianOldStable) and buster is oldoldstable.  Me, I haven't [yet] upgraded and it's unclear if there's any incompatibility, and I believe these git releases are labeled "for testing"
