### ISSUE TITLE
smplayer is showing this error: Error parsing option one-instance (option not found)

### ISSUE THREAD

**Issue by RiKkzu** [smplayer-dev/smplayer#776]
Your Enviroment

    SMPlayer version: 22.7.0
    OS: Linux debian 6.1.0-10-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-2 (2023-07-27) x86_64 GNU/Linux
    Multimedia engine you're using with SMPlayer: mpv 0.35.1

Logs
/usr/bin/mpv --no-quiet --terminal --no-msg-color --input-ipc-server=/tmp/smplayer-mpv-2f4c --msg-level=ffmpeg/demuxer=error --video-rotate=no --no-config --no-fs --hwdec=vaapi --sub-auto=fuzzy --framedrop=decoder+vo --no-input-default-bindings --input-vo-keyboard=no --no-input-cursor --cursor-autohide=no --no-keepaspect --wid=56623127 --monitorpixelaspect=1 --osd-level=1 --osd-scale=1 --osd-bar-align-y=0.6 --sub-ass --embeddedfonts --sub-ass-line-spacing=0 --sub-scale=1 --sub-font=Arial --sub-color=#ffffffff --sub-shadow-color=#ff000000 --sub-border-color=#ff000000 --sub-border-size=0.75 --sub-shadow-offset=2.5 --sub-font-size=50 --sub-bold=no --sub-italic=no --sub-margin-y=8 --sub-margin-x=20 --sub-codepage=ISO-8859-1 --sub-pos=100 --volume=96 --demuxer-max-bytes=2097152 --screenshot-template=cap_%F_%p_%02n --screenshot-format=jpg --screenshot-directory=/home/digma/Изображения/smplayer_screenshots --af-add=lavfi=[acompressor] --audio-pitch-correction=yes --volume-max=200 --ytdl -ytdl-format=bestvideo[height<=?480]+bestaudio/best[height<=?480] --script-opts=ytdl_hook-ytdl_path=yt-dlp --ytdl-format=best,22 --term-playing-msg=MPV_VERSION=${=mpv-version:}
INFO_VIDEO_WIDTH=${=width}
INFO_VIDEO_HEIGHT=${=height}
INFO_VIDEO_ASPECT=${=video-params/aspect}
INFO_VIDEO_FPS=${=container-fps:${=fps}}
INFO_VIDEO_FORMAT=${=video-format}
INFO_VIDEO_CODEC=${=video-codec}
INFO_DEMUX_ROTATION=${=track-list/0/demux-rotation}
INFO_AUDIO_FORMAT=${=audio-codec-name}
INFO_AUDIO_CODEC=${=audio-codec}
INFO_AUDIO_RATE=${=audio-params/samplerate}
INFO_AUDIO_NCH=${=audio-params/channel-count}
INFO_LENGTH=${=duration:${=length}}
INFO_DEMUXER=${=current-demuxer:${=demuxer}}
INFO_SEEKABLE=${=seekable}
INFO_TITLES=${=disc-titles}
INFO_CHAPTERS=${=chapters}
INFO_TRACKS_COUNT=${=track-list/count}
METADATA_TITLE=${metadata/by-key/title:}
METADATA_ARTIST=${metadata/by-key/artist:}
METADATA_ALBUM=${metadata/by-key/album:}
METADATA_GENRE=${metadata/by-key/genre:}
METADATA_DATE=${metadata/by-key/date:}
METADATA_TRACK=${metadata/by-key/track:}
METADATA_COPYRIGHT=${metadata/by-key/copyright:}
INFO_MEDIA_TITLE=${=media-title:}
INFO_STREAM_PATH=${stream-path}
 --audio-client-name=SMPlayer --term-status-msg=STATUS: ${=time-pos} / ${=duration:${=length:0}} P: ${=pause} B: ${=paused-for-cache} I: ${=core-idle} VB: ${=video-bitrate:0} AB: ${=audio-bitrate:0} --one-instance

Error parsing option one-instance (option not found)
Setting commandline option --one-instance= failed.
Exiting... (Fatal error)

**Comment by smplayer-dev** [comment]
SMPlayer doesn't pass that --one-instance option to mpv. I guess you're somehow doing it. Be sure it's not in preferences -> advanced -> options for mplayer/mpv.

**Comment by RiKkzu** [comment]
Thank you. I didn't think to check the link directly in the application. Instead, I used the browser extension "Open in VLC", it looks like it added parameters.
