### ISSUE TITLE
SMPlayer - Youtube playlist - plays first song ONLY then stops playing :(

### ISSUE THREAD

**Issue by s4sharing** [smplayer-dev/smplayer#78]
_SMPlayer_ > _Open_ > _URL..._

https://www.youtube.com/playlist?list=OLAK5uy_nqZO7FXLCDTTJXzK8kMZEc04wmL9N3aKo

**ERROR**

Error transferring https://www.youtube.com/list_ajax?
 action_get_list=1&style=xml&Iist=OLAK5uy_nqZO7FXLCDTTJXzK8kMZEc04wmL9N3aKo
 - server replied: **Not Found**

 SMPlayer © 2006-2020 Ricardo Villalba
 <rvm@users.sourceforge.net>
 Version: 21.1.0 (revision 9475)(64-bit)
 Portable Edition
 Using Qt 5.6.0 (compiled with Qt 5.6.0)
 Using MPV 0.32.0

**Comment by smplayer-dev** [comment]
Duplicated of #12.
It was already fixed. Try [this version](https://github.com/smplayer-dev/smplayer/releases/tag/v21.1.0.9609).

**Comment by s4sharing** [comment]
downloaded SMPlayer v21.1.0.9609 x64 Portable OK

Latest Release. Development version. For testing.

SMPlayer > Open > URL...

https://www.youtube.com/playlist?list=OLAK5uy_nqZO7FXLCDTTJXzK8kMZEc04wmL9N3aKo

**plays first song ONLY then stops playing :(**

**Comment by smplayer-dev** [comment]
You have to load it in the playlist: View -> Playlist, Load/Save button -> Load playlist from URL.

**Comment by s4sharing** [comment]
great - yes that works! my fave media player :)
**thank you**!
