### ISSUE TITLE
Wrong volume values (OSD) in different video sizes (aspect ratios)

### ISSUE THREAD

**Issue by AngryPhantom** [smplayer-dev/smplayer#792]
**Describe the bug**

I get wrong volume numbers in the on-screen display (OSD) when changing video size to **full-screen**. I mapped volume control to mouse scroll in the Preferences. So, when I scroll the wheel I see different volume levels. Though it's OK in other modes like Ctrl+1, Ctrl+2.
I've made two screenshots and also recorded a video of this issue.

**To Reproduce**

1. Open a video file.
2. Slightly scroll your mouse up and down to see the volume level
3. Change the video size to fullscreen
4. Scroll your mouse again
5. The level is different

**Expected behavior**

Volume numbers in the on-screen display (OSD) should be the same in any video size.

**Screenshots**

Screenshot 1, video size 100% (Ctrl+1):

![Screen_01](https://github.com/smplayer-dev/smplayer/assets/17167075/46ff864e-64eb-428c-8880-3a1d379a43e0)

Screenshot 2, video is full-screen (pressed F):

![Screen_02](https://github.com/smplayer-dev/smplayer/assets/17167075/60173c32-6fba-447f-b732-5d12c1fcacb5)

**Video**

https://github.com/smplayer-dev/smplayer/assets/17167075/6ab23515-b4c9-4eb4-98c9-1b9f6e2925ff

**Your Enviroment**
 - SMPlayer version: Version: 23.6.0 (revision 10157), Using Qt 5.15.10 (compiled with Qt 5.15.10), Using MPV 0.36.0
 - OS: Arch Linux
 - Multimedia engine you're using with SMPlayer (preferences -> general): /usr/bin/mpv

Thank you in advance.

**P.S.** When I finished writing and editing this report I've just realized that it actually shows the same volume in the status bar and in the full-screen video.

So, I guess **something is wrong with the on-screen display** (OSD) code since it differs from the one in the status bar.
<br/>
<br/>

**Comment by AngryPhantom** [comment]
So, basically, the issue is just **different values** in the OSD and in the status bar.

![volume](https://github.com/smplayer-dev/smplayer/assets/17167075/c04bc5c7-9bb7-41a5-b9f7-fa65b4ea1804)

What am I doing wrong?

**Comment by smplayer-dev** [comment]
The value in the OSD is displayed by mpv and the value in the status bar is displayed by smplayer.
Set the "Max. amplification" option in preferences -> general -> audio to 100 and both values will be the same.

**Comment by AngryPhantom** [comment]
> Set the "Max. amplification" option in preferences -> general -> audio to 100 and both values will be the same.

Oh, my bad :( Only polluted the issues section. I'm sorry. Closing.
