### ISSUE TITLE
Save video to disk

### ISSUE THREAD

**Issue by kekukui** [smplayer-dev/smplayer#80]
In the following example, `SMplayer` renders this javascript blob correctly when the page URL is pasted, and `youtube-dl` can save it to disk.  In this situation it would be useful to display a `save` button on the toolbar or context menu.  (VLC has save capability, but its labeled "convert" and does not appear on the toolbar.)

https://www.adultswim.com/videos/rick-and-morty/pickle-rick

**Comment by smplayer-dev** [comment]
Sorry, but I'm not going to add an option to download videos. If you use smtube there's an indirect way to do it, right click on video, select play on a web browser. Right click on the video in the web browser, it will probably have an option to download the video.

**Comment by kekukui** [comment]
OK thanks for the information.  But it does not seem to be working.

![image](https://user-images.githubusercontent.com/20834957/117047729-34000380-ace0-11eb-84dd-e4648fa05bfc.png)

**Comment by smplayer-dev** [comment]
If you're using the development version of smplayer, the one available here at github, you also need the development version of smtube: https://github.com/smplayer-dev/smtube/releases/tag/v20.6.0.1017

**Comment by kekukui** [comment]
> **you also need the development version of smtube**

Alright, I have it working now.  But the method you describe only supports YouTube, is that correct?  (`youtube-dl` works on many other sites, like the example in my original post.)

**Comment by smplayer-dev** [comment]
Yes, that only works for Youtube videos.

I'm afraid I can't add an option in SMPlayer to download videos because maybe I can get into legal troubles, so I prefer not to.
