### ISSUE TITLE
[v23.6.0+] Unable to load playlists in m3u8-format (small bug introduced with commit from 2022)

### ISSUE THREAD

**Issue by e-d-n-a** [smplayer-dev/smplayer#802]
### **Describe the bug**
It's a simple bug that prevents opening/loading playlists in m3u8-format (so just a simple m3u in utf-8 encoding).
Now (in latest version) it throws an error showing a dialog informing about an unsupported file format.
I'm sure it worked in previous versions of SMPlayer as most of my playlists that I saved and loaded before are in m3u8-format.
[load_m3u is still capable](https://github.com/smplayer-dev/smplayer/blob/7d4d7ec4c23867a3a70ff353423cbe7e04bfcd5c/src/playlist.cpp#L984) of loading m3u8-files as well!

So I investigated this issue quickly myself and found, that the way playlists get loaded was changed in 2022 ([load-function in v23.6.0](https://github.com/smplayer-dev/smplayer/blob/aff9170c5f053ec493597f7e340475fdfb7b0b0e/src/playlist.cpp#L1383)) with [this commit](https://github.com/smplayer-dev/smplayer/commit/f4a165fc8f9eda2c67ceddf3d317dc2f948d94e9).
You can also check from [the blame here](https://github.com/smplayer-dev/smplayer/blame/7d4d7ec4c23867a3a70ff353423cbe7e04bfcd5c/src/playlist.cpp#L1383).
It explicitly checks for valid file formats with extra if-clauses, but a check for the m3u8-format has probably been forgotten.

[This line](https://github.com/smplayer-dev/smplayer/blob/7d4d7ec4c23867a3a70ff353423cbe7e04bfcd5c/src/playlist.cpp#L1403) should actually be something like:
`if (suffix == "m3u" || suffix == "m3u8") {`

### **To Reproduce**
1. Invoke open playlist dialog (from open menu or playlist menu)
2. Choose a m3u8 playlist (already allowed by the file filter!)
3. Click open
4. Refuses to open it and reports "m3u8" as an unsupported file type for playlists with an error dialog (see screenshot below).

### **Expected behavior**
Just allow to open playlists in m3u8-format as it is supported and was possible before.

### **Screenshots**
![2023-09-26 07_46_13-Wrong playlist](https://github.com/smplayer-dev/smplayer/assets/8239937/682a3a78-775f-41d0-b10b-cfc9e4d9618d)

### **Your Enviroment**
 - SMPlayer version: v23.6.0
 - OS: Windows 7
 - Multimedia engine you're using with SMPlayer (preferences -> general):
 [ ] MPlayer
 [ X ] MPV

**Logs**
No info in log. Just the dialog informing about "wrong" file format.

**Additional context**
Just noticed it after having no issues in previous versions as [load_m3u was the default](https://github.com/smplayer-dev/smplayer/blob/06363d7f3573dc4fc2159424ea9f4b80976ed123/src/playlist.cpp#L1403) (in v22.7.0) used in the else-case and works fine for m3u8-files.

**Comment by smplayer-dev** [comment]
Fixed.
