### ISSUE TITLE
OpenSubtitles.org API deprecation and end of life - upgrade to new REST API on OpenSubtitles.com

### ISSUE THREAD

**Issue by Thierry7754** [smplayer-dev/smplayer#833]
Hello,

OpenSubtitles.org has announced the end of its original API and will cease functioning by the end of 2023 (https://forum.opensubtitles.org/viewtopic.php?f=1&t=18389&p=49836).

I would like an enhancements / a new feature to be able to consume the new REST API on opensubtitles.com as a replacement of the current option available in SMplayer.

Thx in advance for your dev.

Regards,

**Comment by smplayer-dev** [comment]
I'm already working in the adaptation for the REST API.

**Comment by smplayer-dev** [comment]
[Version 10184](https://github.com/smplayer-dev/smplayer/releases/tag/v23.6.0.10184) uses the REST API. Please test and let me know if you find any problem.

**Comment by Thierry7754** [comment]
Hello Ricardo,

Thx for your support.
I've tested 2 package in the version 10184 (smplayer-23.6.0.10184-x64-qt5.6-unsigned.exe and  smplayer-23.6.0.10184-x64-unsigned.exe)
I've noticed subtitles are still provided frrom opensubtitles.org instead of opensubtitles.com 
I was expecting a way to enter the API key and I don't find any field for that.
Unless I'am mistaken, I was not able to pull subtitles from opensubtitles.com with the API with the version 10184
![Capture](https://github.com/smplayer-dev/smplayer/assets/140586247/00c04836-5ef9-40df-8c77-e2245e92c9d9)

Access to API DOC => https://opensubtitles.stoplight.io/docs/opensubtitles-api/e3750fd63a100-getting-started

**Comment by Thierry7754** [comment]
API key created on opensubtitles.com

![Capture2](https://github.com/smplayer-dev/smplayer/assets/140586247/760b022d-6872-4f75-a9cd-e0cf9a9685ef)

**Comment by smplayer-dev** [comment]
I haven't changed the opensubtitles link yet, but it's using opensubtitles.com.
As far as I know you don't need to use your own api key, that's why there isn't a field for it. The code uses my api key.

**Comment by Thierry7754** [comment]
Hi Ricardo,
Subtitles can be downloaded with my user account from opensubtitles.com.
But behavior in this version seems to have changed.

Previously, when I clicked on "find subtitle at..." in the subtitles drop-down menu, all subtiles available in opensubltitles.org was directly provided in the list.
Now, the list is empty by default.
When I click on the search button, nothing happened. To retreive subtitles you must click on the "refresh button".
Could you applied same behavior as before ?
Thx for your support.

**Comment by smplayer-dev** [comment]
The behavior should be the same as before. Click on the Options button in the subtitles window and select "Hash" as search method and see if that fixes it.

**Comment by hnsteyding** [comment]
I have the same behavior - all commits after 18554be and the latest test release version 23.6.0.10190 show zero results.
It doesn't matter if i select "Hash", "Filename" or "Hash and Filename" as search method in "Options" in the subtitles window.

Only the official release 23.6.0 (revision 10157) or test release version 23.6.0.10170 works.

**Comment by smplayer-dev** [comment]
Please send the smplayer log after the subtitle search so that I can try to figure out the problem.

**Comment by hnsteyding** [comment]
I've made log files from different smplayer revisions/commits
[smplayer-log-working-test-release-revision-10176.log](https://github.com/smplayer-dev/smplayer/files/13646477/smplayer-log-working-test-release-revision-10176.log)
[smplayer-log-not-working-commit-910a0eb-revision-10195.log](https://github.com/smplayer-dev/smplayer/files/13646478/smplayer-log-not-working-commit-910a0eb-revision-10195.log)
[smplayer-log-not-working-latest-test-release-revision-10190.log](https://github.com/smplayer-dev/smplayer/files/13646479/smplayer-log-not-working-latest-test-release-revision-10190.log)
[smplayer-log-working-official-release-23.6.0.log](https://github.com/smplayer-dev/smplayer/files/13646480/smplayer-log-working-official-release-23.6.0.log)

**Comment by hnsteyding** [comment]
I've made log files from different revisions/commits:
[smplayer-log-working-test-release-revision-10176.log](https://github.com/smplayer-dev/smplayer/files/13646555/smplayer-log-working-test-release-revision-10176.log)
[smplayer-log-not-working-commit-910a0eb-revision-10195.log](https://github.com/smplayer-dev/smplayer/files/13646556/smplayer-log-not-working-commit-910a0eb-revision-10195.log)
[smplayer-log-not-working-latest-test-release-revision-10190.log](https://github.com/smplayer-dev/smplayer/files/13646557/smplayer-log-not-working-latest-test-release-revision-10190.log)
[smplayer-log-working-official-release-23.6.0.log](https://github.com/smplayer-dev/smplayer/files/13646558/smplayer-log-working-official-release-23.6.0.log)

**Comment by smplayer-dev** [comment]
If I search for "matrix" I get 51 results. Are you filtering for a specific language?

**Comment by hnsteyding** [comment]
I search for "matrix" in all languages and get '100 files available' in working releases/commits:
![grafik](https://github.com/smplayer-dev/smplayer/assets/65712636/a2acad31-feaf-46f9-a80f-08a9a6aae116)

If i switch to english language in working releases/commits i get 9 results and '100 files available':
![grafik](https://github.com/smplayer-dev/smplayer/assets/65712636/7ded560b-8803-4e7f-8012-58687acdee9f)

**Comment by smplayer-dev** [comment]
Check [this version](https://github.com/smplayer-dev/smplayer/releases/tag/v23.6.0.10197)

Now if you select a language it will search for subtitles in that language only.

**Comment by hnsteyding** [comment]
@smplayer-dev
the latest test release version 23.6.0.10197 show also zero results so i could not check if i select a language it will search for subtitles in that language only.

**Comment by smplayer-dev** [comment]
Select a language and then search, see if now you get results.

**Comment by hnsteyding** [comment]
OK, i found out that it works from Version 23.6.0.10184 on only if i load a video file or media and then search fo subtitles.
Works also then without select a language.

Search only for a title without previously load a video file or media shows still zero results.

**Comment by smplayer-dev** [comment]
I can't reproduce this problem in my computer. I play a video, open the find subtitles window and it displays some results. What's the file name of you video?

**Comment by hnsteyding** [comment]
I've compile SMplayer against latest source code (Version 23.6.0.10199) and now it works also without previously load a video file or media.

I use an ISO file from Disneys cartoon MULAN and also type "Matrix" in "Search for title" field in "Find Subtitles" window  without previously load MATRIX video  file or media - every time i got expected results now.

Everything works now - i don't know what was wrong in the past....

**Comment by Shadowized** [comment]
I don't know if I should make a new topic for this but when I'm searching with v23.12.0.10207, for instance "**Some.Show.Name.S05E01**" I'm being given results for S01,S02,S03,S04 and so on, if I wrap it in quotes I get only **one** result when there is meant to be **five**.  Not sure what to do.

**Comment by smplayer-dev** [comment]
> I don't know if I should make a new topic for this but when I'm searching with v23.12.0.10207, for instance "**Some.Show.Name.S05E01**" I'm being given results for S01,S02,S03,S04 and so on, if I wrap it in quotes I get only **one** result when there is meant to be **five**. Not sure what to do.

This problem may be fixed in version 10213:
https://github.com/smplayer-dev/smplayer/releases/tag/v23.12.0.10213

**Comment by Shadowized** [comment]
I just tested v23.12.0.10213 and the searches I performed are returning the correct results now 👍

**Comment by mkey** [comment]
Hello, referring to the REST API issue.

I have now installed SMPlayer 23.12.0-1. For the past few days subtitles downloaded through "Subtitles \ Find subtitles on OpenSubtitles.org..." will only contain one subtitle line stating "Become OpenSubtitles.org VIP member to get subtitles -> osdb.link/vip"

Does this mean that this functionality from now onward is limited to opensubtitle VIP members?

**Comment by smplayer-dev** [comment]
No. That happens with the old API.

From version 23.12 smplayer uses the new API and the downloaded subtitles are correct. Be sure you're really using version 23.12.

**Comment by mkey** [comment]
> No. That happens with the old API.
> 
> From version 23.12 smplayer uses the new API and the downloaded subtitles are correct. Be sure you're really using version 23.12.

Thanks for the reply and confirmation. I am quite confident that I am using the correct version.

![image](https://github.com/smplayer-dev/smplayer/assets/672581/e8e322f7-b424-47c7-ad9a-73045b37a7f6)

I have updated my system a few hours ago but haven't still rebooted. Possibly that's causing the issue, but smplayer is obviously on the correct version.

**Comment by mkey** [comment]
OK, I have downloaded your appimage and with that the subtitle download is working fine. I see also that in this version you have renamed the button from "Find subtitles" to "Download subtitles".

Maybe/very probably an issue with whatever is available in the Arch repository. Thanks.

Update:

All OK on my end after performing a reboot. Very strange stuff, it shows the correct version but the module being run is older.
