### ISSUE TITLE
Version 23.6.0 does not install properly on Ubuntu

### ISSUE THREAD

**Issue by LarryM04** [smplayer-dev/smplayer#834]
**Describe the bug**
On Ubuntu (23.10) using the menu bar item "Open" then "File" opens a Windows looking dialog box with that contains "Computer" and "76" in the left hand side and "/" on the right hand side.  Clicking on "/" shows the directories "bin, etc, home, lib, lib32, meta,snap, usr, and var.  Note - there is not lib32 or meta directories on the system, and this list misses several existing directories.  Attempting to play a file not in one of these directories results in a file not found error

**To Reproduce**
1. Go to "Open", the "File"
2. Click on '/'
3. See error

**Expected behavior**
Expect a normal Ubuntu looking window with all existing directories

**Screenshots**
![Screenshot from 2023-11-18 09-22-26](https://github.com/smplayer-dev/smplayer/assets/25868883/493775af-12da-4a7e-93fc-0daebafdb95e)

**Your Enviroment**
 - SMPlayer version: 23.6.0
 - OS: Ubuntu 23.10
 - Multimedia engine you're using with SMPlayer (preferences -> general):
 [ ] MPlayer
 [X] MPV

**Logs**
Reproduce the bug in your computer and attach the smplayer log (menu View) here.

**Additional context**
Version 22.2.0 used to install properly

**Comment by smplayer-dev** [comment]
It looks like you're using a snap package, which has some restrictions. You can try to install a deb package from here:
https://github.com/smplayer-dev/smplayer/releases/tag/v23.6.0

**Comment by LarryM04** [comment]
Yes, I did use the snap package.  Removed that one and downloaded the "jammy" deb file:

larry@minis-l: sudo dpkg -i smplayer*
[sudo] password for larry:
Selecting previously unselected package smplayer.
(Reading database ... 172563 files and directories currently installed.)
Preparing to unpack smplayer_23.6.0-1.ubuntu-jammy_amd64.deb ...
Unpacking smplayer (23.6.0-1~ubuntu-jammy) ...
dpkg: dependency problems prevent configuration of smplayer:
 smplayer depends on libqt5core5a (>= 5.15.1); however:
  Package libqt5core5a is not installed.
 smplayer depends on libqt5dbus5 (>= 5.14.1); however:
  Package libqt5dbus5 is not installed.
 smplayer depends on libqt5gui5 (>= 5.11.0~rc1) | libqt5gui5-gles (>= 5.11.0~rc1); however:
  Package libqt5gui5 is not installed.
  Package libqt5gui5-gles is not installed.
 smplayer depends on libqt5network5 (>= 5.14.1); however:
  Package libqt5network5 is not installed.
 smplayer depends on libqt5widgets5 (>= 5.15.1); however:
  Package libqt5widgets5 is not installed.
 smplayer depends on libqt5xml5 (>= 5.0.2); however:
  Package libqt5xml5 is not installed.

dpkg: error processing package smplayer (--install):
 dependency problems - leaving unconfigured
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for gnome-menus (3.36.0-1.1ubuntu1) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu5) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for man-db (2.11.2-3) ...
Errors were encountered while processing:
 smplayer

So it looks like several Qt 5 libs are missing.  For another package, I have Qt 6 installed.  Is there a way to get smplayer to use that?  I'm concerned that loading Qt 5 would break Qt 6...


how would I install the libs smplayer needs?



Then I tried:
Did the steps liisted on the web site:

sudo add-apt-repository ppa:rvm/smplayer 
sudo apt-get update 
sudo apt-get install smplayer smplayer-themes smplayer-skins 


Takes an error that smplayer-skins is not found.  Removed that part and smplayer 22.7 loaded.  It does bring up an Ubuntu looking dialog box to open a file, but everything I tried takes this error "Oops, something went wrong MPlayer/mpv crashed.  See the log for more info: and in the log:

METADATA_DATE=

METADATA_TRACK=

METADATA_COPYRIGHT=

INFO_MEDIA_TITLE=Crappie Wisdom.mp4

INFO_STREAM_PATH=/smb/Helios4/Movies/Fishing/Crappie Wisdom.mp4

[vo/xv] X11 can't keep up! Waiting for XShm completion events...

INFO_TRACK_0: video 1 '' '' yes

INFO_TRACK_1: audio 1 '' '' yes

Exiting... (Quit)

**Comment by smplayer-dev** [comment]
Be sure mpv is installed and type this in a terminal to be sure it works fine:
`mpv --version`

**Comment by LarryM04** [comment]
I've tried mpv and mplayer and get the same results.

Versions:

larry@minis-l: mpv --version
mpv 0.36.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
libplacebo version: v6.292.0
FFmpeg version: 6.0-6ubuntu1
FFmpeg library versions:
   libavutil       58.2.100
   libavcodec      60.3.100
   libavformat     60.3.100
   libswscale      7.1.100
   libavfilter     9.3.100
   libswresample   4.10.100

larry@minis-l: mplayer --version
Unknown option on the command line: --version
Error parsing option on the command line: --version
MPlayer 1.5+svn38423-2build1 (Debian)

**Comment by smplayer-dev** [comment]
I'm afraid I can't reproduce this problem on my computer with Ubuntu 22.04.
Just in case try deleting the file `~/.config/smplayer/player_info.ini`

**Comment by LarryM04** [comment]
Hmm, after deleting that file, when set to mpv, I get audio, but no video.  Moving the time slider gets the "Opps" message.  Using mplayer gets the Opps just like before.  From the command line, both mplayer and mpv work.

How about this - tell me  how to completely wipe SMplayer and all its artifacts so there's no trace of it on my system, then which, installation procedure should I run?  Also note - it worked fine for me when the system was on 22.x - something changed on 23.x?  The initial install of SMplayer was on a fresh install of 23 (not an updated to 23)

**Comment by smplayer-dev** [comment]
> Hmm, after deleting that file, when set to mpv, I get audio, but no video. Moving the time slider gets the "Opps" message. Using mplayer gets the Opps just like before. From the command line, both mplayer and mpv work.

Could you paste the log after that error?

> How about this - tell me how to completely wipe SMplayer and all its artifacts so there's no trace of it on my system, then which, installation procedure should I run?

Delete the folder `~/.config/smplayer`

> Also note - it worked fine for me when the system was on 22.x - something changed on 23.x? The initial install of SMplayer was on a fresh install of 23 (not an updated to 23)

I haven't actually tested smplayer on ubuntu 23.

**Comment by LarryM04** [comment]
I did
`sudo apt-get remove smplayer smplayer-themes` (the opposite of my previous install)
`rm -r  ~/.config/smplayer`
`rm -r ~/snap/smplayer` (I had previously done a snap remove)

I've done snap, smplayer_23.6.0-1.ubuntu-jammy_amd64, sudo apt-get install smplayer and from the App Center.  None have worked.  

What install method should I try?

**Comment by smplayer-dev** [comment]
I think I'll install Ubuntu 23.10 to try to find out the problem.

**Comment by LarryM04** [comment]
That'd be great... but do a clean install of Ubuntu.  My concern is that on an update a critical file might not be removed.

Anxious to hear your results

**Comment by smplayer-dev** [comment]
Can you play videos with mpv?

I've just tested mpv Ubuntu 23.10 in a virtual box, I get this error when I try to play a video:

```
[vo/gpu/opengl] Suspected software renderer or indirect context.
[vo/gpu/drm] VT_GETMODE failed: Inappropriate ioctl for device
[vo/gpu/drm] Failed to set up VT switcher. Terminal switching will be unavailable.
pci id for fd 10: 1b36:0100, driver (null)
MESA-LOADER: failed to open qxl: /usr/lib/dri/qxl_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
pci id for fd 11: 1b36:0100, driver (null)
kmsro: driver missing
[vo/gpu] Failed to create GBM surface.
[vo/gpu] Failed to setup GBM.
[vo/gpu] Failed to commit atomic request: Function not implemented
```

But maybe it's a problem of the virtual machine.

If I use --vo=x11 then the video plays fine.

**Comment by LarryM04** [comment]
Yes, both mpv and mplayer work fine when I use them from the command line.

I think the clue is the dialog box that I showed in the first post.  That's a Windows style dialog box, It has  Windows directories, not Linux directories (there is some overlap).  Here's what SMPlayer shows for Open|File on Ubuntu 22:

![Screenshot from 2023-12-03 00-23-58](https://github.com/smplayer-dev/smplayer/assets/25868883/20a682df-0aed-4c1f-b1e8-4d58c7c213c8)

I really think something is not getting properly installed, or something that was in Ubuntu 22 is no longer there on 23.  SMplayer does properly play files IF they are found in one of the directories listed in that Windows style box, but not if they are in another (legitimate) directory on the system.

**Comment by smplayer-dev** [comment]
> Yes, both mpv and mplayer work fine when I use them from the command line.

I've just installed Ubuntu 23.10 in a virtual machine, using virtualbox, now smplayer works fine with mpv with the default options, no crashes, so I'm afraid I can't reproduce your problem.

> I really think something is not getting properly installed, or something that was in Ubuntu 22 is no longer there on 23. SMplayer does properly play files IF they are found in one of the directories listed in that Windows style box, but not if they are in another (legitimate) directory on the system.

Snap applications run in a restricted enviroment with limited access, I think it's normal that it uses the Qt file dialog instead of the system one. If you can't play videos from some directories maybe you need to give it more permissions, you can do it within the ubuntu software application.

![Captura desde 2023-12-03 12-18-02](https://github.com/smplayer-dev/smplayer/assets/10128951/246b4e5f-e060-4fce-832b-f0fa89ab246c)

Or you can also try the flatpak package and see if that works better for you.

**Comment by LarryM04** [comment]
I still think you are not understanding the problem, I must be doing a poor job of explaining... Look at the "look and feel" of the dialog box in the first post.  It's a "Windows" style box.  It has Windows directories (lib32) listed that don't even exist.  This is what comes up for me on Ubuntu 23.  Now look at the dialog box a few posts ago.  This is what comes up on Ubuntu 22 and is a proper looking dialog box.  It is not a permissions problem, the directories that are missing are wide open.

When you do "Open", then "File" which style dialog box do you see?  Do you see all the directories?  Any extras?

I used MULTIPLE installation proceedures, always got the WIndows style dialog.   If its a "snap" installation problem, how do I fix that?

**Comment by smplayer-dev** [comment]
The Windows style dialog is actually the Qt file dialog. The lib32 folder is a linux folder.

Suggestion: try the flatpak package.
I've just installed it in Ubuntu 23.10 in the virtual machine and it works fine. And it uses the gnome file dialog.

If you don't have flatpak:

Install flatpak:

```
sudo apt install flatpak
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

```
Install smplayer:
```
sudo flatpak install info.smplayer.SMPlayer
```

Run it:
`flatpak run info.smplayer.SMPlayer
`

**Comment by LarryM04** [comment]
YES!  Doing this proceedure works!  Thank you.   ...but you should adjust all the other places that do installs on 23.  I used the App Center, snap, etc

**Comment by LarryM04** [comment]
The "Flatpak" installation is a success.  This needs to be shown on the SMPlayer download page
