### ISSUE TITLE
Audio setting - WASAPI exclusive mode

### ISSUE THREAD

**Issue by Jawzper** [smplayer-dev/smplayer#840]
I have not been able to find a way to use WASAPI exclusive mode in SMPlayer. Without it, audio is always going through the Windows sound mixer and being altered, and if I want to hear my lossless audio files unaltered with my hi-fi setup I have to use a different program.

Support for WASAPI exclusive mode would allow users to bypass the sound mixer and push the audio stream directly to a hardware output for better audio quality experience

**Comment by smplayer-dev** [comment]
Try adding `--audio-exclusive=yes` in preferences -> advanced -> mplayer/mpv -> options.

**Comment by Jawzper** [comment]
I'm don't think that's working, audio isn't exclusive as I can still hear system sounds while using SMPlayer. I'd note that it seems to be directing sound to the audio device selected in Windows, and switches to whatever device I choose from the system tray. I don't see an option to specify which sound device to use, is there a command I can add for this too? It may help, any time I have used WASAPI in the past I have had to specify an output device.

**Comment by smplayer-dev** [comment]
In menu `Audio -> Send audio to`, you can select the audio device.

**Comment by Jawzper** [comment]
All right, that's definitely working. But the audio does not seem to be exclusive. I can still hear system sounds while audio is playing.

**Comment by bob860712** [comment]
Add 

>-audio-exclusive

 in preferences -> advanced -> mplayer/mpv -> options instead.

**Comment by Jawzper** [comment]
> Add
> 
> > -audio-exclusive
> 
> in preferences -> advanced -> mplayer/mpv -> options instead.

That works. Thanks!
