### ISSUE TITLE
mpv 0.37.0: "Audio codec" and "Video codec" not highlighted in "File properties"

### ISSUE THREAD

**Issue by Matthaiks** [smplayer-dev/smplayer#851]
**Describe the bug**
SMPlayer does not automatically highlight video and audio codecs in the File properties window.

**To Reproduce**
1. Install mpv 0.37.0
2. Play some video
3. Go to File properties
4. Inspect the Audio codec and Video codec tabs

**Expected behavior**
Appropriate audio and video codecs should be highlighted.

**Your Enviroment**
 - SMPlayer version: 23.6.0 x64
 - OS: Windows 10 22H2x64
 - Multimedia engine you're using with SMPlayer (preferences -> general):
 [ ] MPlayer
 [X] MPV

**Additional context**
Seems to be fine with older versions of mpv.

**Comment by smplayer-dev** [comment]
I think it's fixed in commit https://github.com/smplayer-dev/smplayer/commit/910a0ebd76249b956a151336ced480f1b752f2df

You can find a Windows build with this change here (artifacts at the bottom):
https://github.com/smplayer-dev/smplayer/actions/runs/7169022830

**Comment by Matthaiks** [comment]
Fixed. Thanks!
