### ISSUE TITLE
SMplayer play only audio on Youtube videos

### ISSUE THREAD

**Issue by hnsteyding** [smplayer-dev/smplayer#852]
**Describe the bug**
SMplayer play only audio on Youtube videos - no video output

**To Reproduce**
1. Go to 'Open' -> 'URL' -> put YouTube video url in "SMplayer - Enter URL" field and click on OK
2. SMplayer minimized and play only audio of Youtube video. If you maximize SMplayer window it is "grey"

**Expected behavior**
Play Youtube video/URL in SMplayer

**Screenshots**
SMplayer minimized and play only audio of Youtube video:
![grafik](https://github.com/smplayer-dev/smplayer/assets/65712636/3f895345-4aa5-4783-a085-3396a9b812b0)

maximize SMplayer window it is "grey":
![grafik](https://github.com/smplayer-dev/smplayer/assets/65712636/5205c72f-74e5-434f-9705-ccdd521d9bd0)

**Your Enviroment**
 - SMPlayer version: 23.6.0 (Revision 10176)
 - yt-dlp version: 2023.11.16
 - OS: Windows 10
 - Multimedia engine you're using with SMPlayer (preferences -> general):
 [X ] MPlayer
 [ ] MPV

It make no difference with SMplayer version is used - i've checked Version v21.10.0 and above.

**Logs**
[smplayer-ytdl.log](https://github.com/smplayer-dev/smplayer/files/13648029/smplayer-ytdl.log)
[mplayer-ytdl.log](https://github.com/smplayer-dev/smplayer/files/13648030/mplayer-ytdl.log)
Translation of:
"Dateiname ist zu lang, datei- oder verzeichnisspezifische Konfigurationsdateien k�nnen nicht geladen werden"
"Filename is too long, can not load file or directory specific config files"
My SMplayer setting file:
[smplayer.ini.txt](https://github.com/smplayer-dev/smplayer/files/13648050/smplayer.ini.txt)

**Maybe to fix the problem:**
On windows the following pipe parameters from _yt-dlp.exe_ to _mplayer.exe_ will play YouTube videos:
_**yt-dlp -o - "URL of YouTube video" | .\apps\mplayer.exe -**_

**Comment by smplayer-dev** [comment]
I can't reproduce this problem in my computer.
Does it work if use mpv instead of mplayer?

**Comment by bob860712** [comment]
Config file corrupted I guess, had similar problem with only video output but no sound. Replace the config file with an old one might work.

**Comment by hnsteyding** [comment]
@bob860712:
Yes, thats it.
Config file was corrupted - i've delete old file and let created a new one via SMplayer.
