### ISSUE TITLE
Subtitles open with huge font

### ISSUE THREAD

**Issue by paul1149** [smplayer-dev/smplayer#856]
Whenever I open a subtitled file in SMP, the subtitles are huge. I have to adjust the size down and then back up to normal.

![smp suttitles huge](https://github.com/smplayer-dev/smplayer/assets/13952246/ba3717e9-1c05-4fde-9369-9454cc7c2a17)

 - SMPlayer  Version: 23.6.0 (revision 10157)
Using Qt 5.15.8 (compiled with Qt 5.15.8)
Using MPV 0.36.0

 - OS: MX Linux 23 x64
 - Multimedia engine you're using with SMPlayer
 MPV

I have set the default font ratio to 1.
I have set the default font down to 7.
I have restarted SMP, the subtitles are huge each time and must be adjusted down.

I have had this problem for a long time, but finally am trying to find an answer to it.

Thanks.

**Comment by smplayer-dev** [comment]
Be sure the option "Use the ASS library" in preferences -> subtitles is enabled.

**Comment by paul1149** [comment]
Yes, thanks. That has always been enabled, except I toggled it off briefly for testing.

**Comment by smplayer-dev** [comment]
So is this issue fixed?

**Comment by paul1149** [comment]
No, there's been no change here.

**Comment by smplayer-dev** [comment]
The only way I can get huge subtitles is by turning off the option "Use the ASS library".
Does this problem also happen if you use a snap or flatpak package?
https://www.smplayer.info/install-snap-flatpak-appimage.php

**Comment by paul1149** [comment]
Thanks, but I'm not going to install a flatpak of SMP.

**Comment by smplayer-dev** [comment]
What about the Appimage? It doesn't require installation.

**Comment by paul1149** [comment]
Thanks. 
Ok, I tried the appimage. Same problem.

**Comment by smplayer-dev** [comment]
With the appimage, go to preferences -> general and select "mpv" from the dropdown menu, to be sure it's using the mpv binary provided by the package instead of the one installed in your system. Be sure it's not selected "other" and /usr/bin/mpv

**Comment by paul1149** [comment]
Ok. I did that just now, then restarted the appimage, and the problem still persists.

**Comment by smplayer-dev** [comment]
Can you send me your smplayer.ini?

**Comment by paul1149** [comment]
Sure. I guess you mean here? Attached.
[smplayer.zip](https://github.com/smplayer-dev/smplayer/files/13753844/smplayer.zip)

**Comment by smplayer-dev** [comment]
You need to enable the option "Freetype support" in the subtitles section.

**Comment by paul1149** [comment]
PERFECT! That immediately solved the problem. Now all the other parameters are working also, like font face, size and color, outline, etc. 

Thanks so much. Really appreciated. :)
