### ISSUE TITLE
Error downloading subtitles - "Download failed: Protocol "" is unknown."

### ISSUE THREAD

**Issue by hnsteyding** [smplayer-dev/smplayer#871]
**Describe the bug**
Subtitles could not be downloaded

**To Reproduce**
1.
![grafik](https://github.com/smplayer-dev/smplayer/assets/65712636/b24b354b-9851-4ce8-9033-623ef66ff3b7)

2.
![grafik](https://github.com/smplayer-dev/smplayer/assets/65712636/3b3b83a7-42c8-43ff-8d9c-2bd59587821d)

**Expected behavior**
Download subtitle files

**Your Enviroment**
 - SMPlayer version: 23.12.0 (revision 10207)
 - OS: Windows 10
 - Multimedia engine you're using with SMPlayer (preferences -> general):
 [X] MPlayer
 [ ] MPV

**Logs**
[SMPLayer.log](https://github.com/smplayer-dev/smplayer/files/13799167/SMPLayer.log)

**Additional context**
Download subtitle via OpenSubtitle website gives me an 20 second counter before downloading:
![grafik](https://github.com/smplayer-dev/smplayer/assets/65712636/1fc3d0c9-4ac2-4a80-b0f3-a318dc04a503)

**Comment by smplayer-dev** [comment]
It seems that now you need to enter your login credentials from opensubtitles.com in the options window.

**Comment by hnsteyding** [comment]
This means every user must from now on request personal login credentials from opensubtitles.com and enter/save these credentials in SMPLayer ?

**Comment by ajangir** [comment]
My old install was 22.7.0 with opensubtitles.org domain and filled in login credentials.
it started showing 
`1
00:00:00,001 --> 04:00:00,000
Become OpenSubtitles.org VIP member 
to get subtitles -> osdb.link/vip `
for every downloaded subtitles file.

I upgraded smplayer to the latest one being 23.12.0, even after entering the login credentials, it is now behaving like the issue presented.
opensubtitles have now two domains : .com and .org.

the wait time is 10 sec after creating account on opensubstitles.com. To skip the waiting, be a VIP member.
any solution for this?

**Comment by smplayer-dev** [comment]
> This means every user must from now on request personal login credentials from opensubtitles.com and enter/save these credentials in SMPLayer ?

According to the API documentation, it should allow 5 downloads per IP per 24 hours without requiring login. However, currently, if you're not logged in, you get that error.

**Comment by smplayer-dev** [comment]
> I upgraded smplayer to the latest one being 23.12.0, even after entering the login credentials, it is now behaving like the issue presented. opensubtitles have now two domains : .com and .org.
> 

You need to enter the credentials from opensubtitles.com. The old credentials from opensubtitles.org are not valid.

**Comment by hnsteyding** [comment]
I've now registered on opensubtitles.com and put my credetials in SMPlayer but error still exists.
I also leave my browser open while i'm logged in and start SMPlayer - does'nt work.
I log off from website and start SMPlayer - no luck.

See log file
[SMPlayer-log-01.01.2024.log](https://github.com/smplayer-dev/smplayer/files/13805671/SMPlayer-log-01.01.2024.log)

**Comment by kudorgyozo** [comment]
Same here Doesn't work even with credentials.  Version: 23.12.0 (revision 10207) (64-bit)

**Comment by pleoset** [comment]
The API is depreciated, from now on only VIP members have access to it ...

**Comment by smplayer-dev** [comment]
The weird thing is that it works for me. Right now it even works without login.

**Comment by pleoset** [comment]
> The weird thing is that it works for me. Right now it even works without login.

Maybe you are a VIP member? (using the old API?) I've tried everything, even new accounts on both .org and .com and the same error - Download failed: Protocol "" is unknown.

**Comment by smplayer-dev** [comment]
I'm not a VIP member and I'm using the new API. I think that error happens when the daily quote is reached. I have an old account that allows me to download 200 subtitles and a new one that allows 20. You can see how much downloads you are allowed in the opensubtitles.com profile.

**Comment by pleoset** [comment]
Both accounts have 0 daily downloads count. Maybe something's wrong with OpenSubtitles at this point, I don't know. But it does not work.

**Comment by pleoset** [comment]
Now suddenly started working! The error is gone, and subs are downloading just fine. And now I can see they are using the .com website and DB to count downloads. So I guess it was a transition moment that caused the issue.

**Comment by El-Doro** [comment]
Hello,
First of all thank you for your work and commitment. I have been using and recommending smplayer for years and I am grateful.
Using Ubuntu 22.04 64 bits I also updated smplayer to last version to benefit from opensibtitles API switch (Version : 23.12.0 (révision 10207)).
I created an account on their new website (.com) and verified it, entered these credentials in smplayer download subtitles options and I get same error message : "Protocol "" is unknown". I checked limit on my opensubtitles account and still ok at 0/20

**Comment by smplayer-dev** [comment]
I see. I get that error now with my new account but it's still work with the older one. I don't know what it's going on.

**Comment by smplayer-dev** [comment]
Doing more tests now I'm getting this:

`{"requests":100,"remaining":0,"message":"You have downloaded your allowed 100 subtitles for 24h.Your quota will be renewed in 09 hours and 37 minutes (2024-01-02 23:59:59 UTC) ts=1704205349 ","reset_time":"09 hours and 37 minutes","reset_time_utc":"2024-01-02T23:59:59.000Z","uk":"app_ud_71238","uid":535665,"ts":1704205349}`

So how come it says that I have downloaded all my subtitles when I haven't?

**Comment by ThomasSeeker** [comment]
Hey there, ... I have 2 problems here.

1. Same as in thread title: "Download failed: Protocol "" is unknown."

2. The "Search"-Button in the "Look for Title"-row does not work anymore. Pressing it leads to 0 results always. Only the "Refresh"-Button fills the list with results. 

My version:  23.12.0 (Revision 10207)

EDIT: Problem 2 seems minor, but since the Refresh-Button creates the search term out of the file name ... a dedicated search for something else is now impossible.

**Comment by smplayer-dev** [comment]
For the second problem, if the search method is "Hash and filename", try to change it to "filename".

**Comment by ThomasSeeker** [comment]
Ah, thank you Ricardo! ... The second issue is solved! ... :-)  ... Hoping for the best for the first one.

**Comment by hnsteyding** [comment]
(At the moment ?) i could download subtitles.

@smplayer-dev:
Thanks for "enabling" the remaining downloads from opensubtitles,com in the status bar (https://github.com/smplayer-dev/smplayer/commit/bf160e163649586f0a29fb6bffeb916bb10bb383) :-)

**Comment by El-Doro** [comment]
I confirm it is working fine now and I do not meet the error any more ! t
I think you can close tbe issue. Thanks

**Comment by TheRammix** [comment]
It still says "Error: daily quota exceeded" even after I registered and put my credentials in the settings.
![image](https://github.com/user-attachments/assets/7827ce4b-3d18-457d-af9c-67837b99c766)
Version 24.5.0 revision 10277.

**Comment by hnsteyding** [comment]
I think that error happens when the daily quote is reached.
Did this happend also the next day ?
