### ISSUE TITLE
setting error when using the libmpv output driver

### ISSUE THREAD

**Issue by tonho911** [smplayer-dev/smplayer#875]
i am using mac monterey with smplayer Version: 23.12.0
  when playing a video with default settings and mouse seek is normal but if it is set
smplayer->preferences->general->video->output driver->libmpv
all mouse seek settings and x button 1 & 2 do not function like driver output->default (normal)
I've tried adding settings to the MPV in the MPV config section but it doesn't work, where is the error and how do I solve it, sir?

**Comment by smplayer-dev** [comment]
When you use libmpv the video is displayed separately from SMPlayer and all keystrokes and mouse events are handled by mpv.
I think under this circumstances it would be better just to run mpv on its own instead of within SMPlayer, so you can configure mpv as you wish.

**Comment by tonho911** [comment]
> When you use libmpv the video is displayed separately from SMPlayer and all keystrokes and mouse events are handled by mpv.
> I think under this circumstances it would be better just to run mpv on its own instead of within SMPlayer, so you can configure mpv as you wish.

on the original MPV Mac all the config inputs are located here  ~/.config/mpv/input.conf.

Before I used it, I could set mouse seek and other things, (original MPV without SMPlayer), but where is the SMPlayer config for MPV(libmpv)?

I tried editing it in the same place as the original mpv but there was no change

Please sir, where is the config located so that I can reuse the conf that I feel comfortable using

**Comment by smplayer-dev** [comment]
The mpv files are in the same location. It's just that smplayer tells mpv to ignore them. To prevent it, edit the file `~/.config/smplayer/smplayer.ini` and change `disable_player_config` to false.

**Comment by tonho911** [comment]
> The mpv files are in the same location. It's just that smplayer tells mpv to ignore them. To prevent it, edit the file `~/.config/smplayer/smplayer.ini` and change `disable_player_config` to false.

Wow, this works bro, I can set it up like using a regular MPV but with SMPlayer, thank you bro for your help...

But one more question I have that still makes me confused about where to look for the settings, namely why the video starts out as widescreen in the default MPV but instead becomes full screen in the SMPlayer version of MPV, it seems strange that a human head would look long and flat.
where can I find the settings bro to make it look like the default MPV (widescreen)?
I'll give you 2 photos of the differences,photo yang widescreen lah yang enak di pandang karena sesuai dan gambar tidak blur
![Screenshot at Jan 04 01-01-28](https://github.com/smplayer-dev/smplayer/assets/148846306/1cb02332-88a3-4f44-b54b-3a2d6d81fcc2)
![Screenshot at Jan 04 01-03-40](https://github.com/smplayer-dev/smplayer/assets/148846306/692689b6-3907-4aa2-8874-631b272c037a)

**Comment by tonho911** [comment]
example widescreen (original mpv)
![Screenshot at Jan 04 01-20-23](https://github.com/smplayer-dev/smplayer/assets/148846306/82d649d4-3897-420e-af52-b20024dc6ec2)
fullscreen (smplayer feat MPV)
![Screenshot at Jan 04 01-21-46](https://github.com/smplayer-dev/smplayer/assets/148846306/4f6727d9-217a-4a85-b5f9-6f2e0faf94b8)

**Comment by Raza-0007** [comment]
This stretching issue can be fixed by choosing the correct aspect ratio under `Video -> Aspect ratio`

**Comment by tonho911** [comment]
> This stretching issue can be fixed by choosing the correct aspect ratio under `Video -> Aspect ratio`

I've tried all the options but it doesn't change the screen size to the default MPV without SMPlayer bro (widescreen), maybe there's something wrong in my settings?
![Uploading Screenshot at Jan 04 07-12-48.png…]()

**Comment by tonho911** [comment]
> This stretching issue can be fixed by choosing the correct aspect ratio under `Video -> Aspect ratio`

I've tried all the options but it doesn't change the screen size to the default MPV without SMPlayer bro (widescreen), maybe there's something wrong in my settings?
![Screenshot at Jan 04 07-12-48](https://github.com/smplayer-dev/smplayer/assets/148846306/882e90d8-8648-41ec-99bf-440a20c89d44)

**Comment by tonho911** [comment]
> This stretching issue can be fixed by choosing the correct aspect ratio under `Video -> Aspect ratio`

Oh yeah, I forgot the advanted->monitor aspect, I also tried changing it but nothing happened
![Screenshot at Jan 04 07-29-58](https://github.com/smplayer-dev/smplayer/assets/148846306/94b77dac-9e2b-4006-bccd-e2ef4e4feff3)

**Comment by Raza-0007** [comment]
Have you tired resetting smplayer settings to default! 

You can do this by deleting the `smplayer.ini `and `playlist.ini`. When you run smplayer again it will regenerate these files with default values.

**Comment by tonho911** [comment]
> Have you tired resetting smplayer settings to default!
> 
> You can do this by deleting the `smplayer.ini `and `playlist.ini`. When you run smplayer again it will regenerate these files with default values.

yes and it's done but it doesn't change anything it still remains full screen and when I press shift+a it should be able to change according to my wishes eg original and so on but it's not like smplayer which doesn't want to let go of control

**Comment by Raza-0007** [comment]
I read in your other post that you are using a different mpv build then the one that comes bundled with smplayer. Does this issue happen on the official smplayer for Mac build too? If not then there is something going on under the hood in smplayer code that is not interacting well with the mpv build that you are using, and only @smplayer-dev will be able to help you with that.

Also try looking at both smplayer and mpv logs, what do they say?

**Comment by tonho911** [comment]
> I read in your other post that you are using a different mpv build then the one that comes bundled with smplayer. Does this issue happen on the official smplayer for Mac build too? If not then there is something going on under the hood in smplayer code that is not interacting well with the mpv build that you are using, and only @smplayer-dev will be able to help you with that.
> 
> Also try looking at both smplayer and mpv logs, what do they say?

no, I don't use any other mpv apart from smplayer because I tried compiling it and it failed, I used smplayer+original mpv from smplayer dev, that's why I think there are bugs or something that is still hidden (conf) specifically for Mac or patches that are bugs that I don't know where it is.
because I tried with original mpv+mpv.conf+input.conf everything runs normally (the video that appears is widescreen/original aspect ratio)
and one more thing, before trying it on Smplayer, I deleted the original MPV from the Mac application so that the results I expected would come true
yes, I think smplayer dev can easily help me, but thank you bro for your help

**Comment by tonho911** [comment]
@Raza-0007 where I can find this smplayer and mpv logs?

**Comment by Raza-0007** [comment]
>I used smplayer+original mpv from smplayer dev, that's why I think there are bugs or something that is still hidden (conf) specifically for Mac or patches that are bugs that I don't know where it is.

There is no hidden conf file in smplayer. All smplayer conf settings are contained within `smplayer.ini`

You can try the @smplayer-dev suggestion of setting `disable_player_config` to false and then put your `mpv.conf` and `input.conf` file within the mpv folder in their original locations.

I personally use a custom `mpv.conf` with smplayer by putting a conf file anywhere on the system and then passing the following command here `Preferences -> Advanced -> Mplayer/mpv -> Options`

`-include=C:\Portable\SMPlayer_mpv.conf`

where `C:\Portable\SMPlayer_mpv.conf` is the path of that file.

.
.
>where I can find this smplayer and mpv logs?

mpv log and smplayer log can be generated from "View -> Logs"

**Comment by smplayer-dev** [comment]
I think you just need to enable the option "Run mplayer/mpv in its own window" in preferences -> advanced ->  mplayer/mpv to prevent smplayer to use any option which alter the size of the window.

**Comment by tonho911** [comment]
> I think you just need to enable the option "Run mplayer/mpv in its own window" in preferences -> advanced -> mplayer/mpv to prevent smplayer to use any option which alter the size of the window.

wow this is cool, everything is normal but something is missing, namely the playlist, the playlist doesn't follow the file that was last opened and when it is closed everything goes back to the beginning and the order of file number one
