### ISSUE TITLE
Please upgrade MPlayer's ffmpeg class library and its related components so that SMPlayer can smoothly play 4K 60FPS VP9 encoded .webm format videos

### ISSUE THREAD

**Issue by zhouxinghong** [smplayer-dev/smplayer#884]
Please upgrade **MPlayer**'s ffmpeg class library and its related components so that SMPlayer can smoothly play **4K 60FPS VP9 encoded .webm format videos**

Using the **MPlayer** engine in the latest version of SMPlayer to play **4K 60FPS VP9-encoded .webm format video** is very laggy and cannot be played smoothly.

**PC environment:**
1. Windows 10 19044
2. CPU i5 3210
3. Memory 8G
4. Graphics card:
   4.1. Intel Integrated Graphics 4000
   4.2. NVIDIA: GT610
5. Western Digital mechanical hard drive 5400 rpm
6. The latest smplayer client
7. **Video:** 4K 60FPS VP9 encoded .webm format videos

This player is really great! none of them! Thank you so much for bringing **MPlayer** back to life again! 😜👍🎉

**Comment by zhouxinghong** [comment]
[Test Video](https://www.youtube.com/watch?v=FyTSAC9vxsQ)

**Comment by zhouxinghong** [comment]
The above problems also exist when playing local 4K 60 FPS VP9 encoded .webm videos.
[Test Video](https://www.youtube.com/watch?v=FyTSAC9vxsQ)

**Comment by smplayer-dev** [comment]
You can update both mplayer and mpv by yourself:
http://www.mplayerhq.hu/design7/dload.html
https://sourceforge.net/projects/mpv-player-windows/files/release/

**Comment by zhouxinghong** [comment]
mpv has poor video rendering quality and is deprecated.

**Comment by Raza-0007** [comment]
> mpv has poor video rendering quality and is deprecated.

I think you have got it backwards. mplayer is almost a dead project nowadays, but its fork mpv is under active development. 

> PC environment:
>
>    CPU i5 3210
>    Graphics card:
>    Intel Integrated Graphics 4000
>    NVIDIA: GT610


I am almost 90% sure that your PC's specs do not meet the minimum requirement to smoothly play 4K 60 FPS content. You may be able to do 4K @ 30 FPS, but not more than that.

**Comment by zhouxinghong** [comment]
The same 4k 60fps vp9 encoded .webm video can be played smoothly using mpv, but the video quality is obviously not as severe as the color (pixel) distortion of the mplayer video.

question?
Hello! Is there any way to adjust the color and image quality of the video played by mpv to be consistent with the color and image quality of the video played by mplayer?

**Comment by Raza-0007** [comment]
I just played the [test video](https://www.youtube.com/watch?v=FyTSAC9vxsQ) you linked above both with Firefox, and after downloading locally, with smplayer 23.12 running mpv 0.37, and both are playing fine for me. I do not notice any color distortion in smplayer running with mpv 0.37.

You may have accidentally enabled some settings that is causing the issue. Try resetting smplayer settings to default by deleting `smplayer.ini` file and see if that resolves your issue.

**Comment by zhouxinghong** [comment]
Can you play it again in smplayer running mplayer, and then compare the colors carefully? You will find that the video quality and color effects of mplayer are much better than those of mpv.

**Comment by zhouxinghong** [comment]
Let me know if you think so too! 😜

**Comment by Raza-0007** [comment]
I played the clip both with mplayer with default profile, and mpv with my custom high-quality profile. I did not notice any color inaccuracies, but mpv's rendering was head and shoulders better than that of mplayer's, but that might be due to the higher quality presets being used in my mpv profile. 

I have to say that mpv's rendering was closer to what Firefox displayed, while mplayer's rendering seemed a little low quality. Colors were fine however.

**Comment by zhouxinghong** [comment]
Can you play it again with the same video rendering quality? Then please tell me the result😜

**Comment by zhouxinghong** [comment]
The color and picture quality of mplayer is much better than any video player, including vlc.

**Comment by Raza-0007** [comment]
> Can you play it again with the same video rendering quality? Then please tell me the result

I can't because mplayer does not understand those newer parameters. For example, mplayer does not know what `vo=gpu-next` is and it crashes when it is in my profile.

**Comment by zhouxinghong** [comment]
Could you please try again using vo=gpu in mpv? This should be the default setting

**Comment by zhouxinghong** [comment]
In addition, FireFox's color for video playback is also wrong. I have reported this problem to Firefox. However, Chrome's color for video playback is much better than FireFox, and is closer to mplayer.

**Comment by Raza-0007** [comment]
> Could you please try again using vo=gpu in mpv? This should be the default setting

I just did, paused the screen at 25 sec, at the parrot. The colors are exactly the same, but mpv's rendering looks sharper and better, but that might be due to the higher quality downscaler that I am using with mpv. Also `gpu-next` is a much higher quality renderer than `gpu`

Keep in mind that the display might have an effect as well, I currently only have 1080p display, so playing the same content on a 4K display might give slightly different results. But since it is a comparison, I doubt the result will be any better for mplayer even on a 4K display. 

Also keep in mind that the mplayer version that is bundled in with smplayer is from dec 2022. While my mpv version is from dec 2023. mpv has a newer version of ffmpeg library built-in.

> In addition, FireFox's color for video playback is also wrong. I have reported this problem to Firefox. However, Chrome's color for video playback is much better than FireFox, and is closer to mplayer.

Each browser or media player will render the video slightly differently based on the built-in parameters. Unless the colors are completely off, there is no right or wrong rendering.

**Comment by zhouxinghong** [comment]
OK! Thank you very, very much for your help! 👍👍👍🎉😜
in addition! Can you share your mpv high-definition, high-quality video player configuration with me? I want to try it out on my laptop.

**Comment by Raza-0007** [comment]
> Can you share your mpv high-definition, high-quality video player configuration with me? I want to try it out on my laptop.

Absolutely. 

I only use mpv's built-in shaders and scalers. They give me excellent quality without over taxing my system.

I typically set the `vo=gpu-next, ao=wasapi and hwdec=auto` through smplayer, so they are normally not included in the custom options that I pass to mpv.

Each system is different so you can tweak each setting to see what works best for you. `gpu-api=vulkan` is highly recommended on Nvidia gpu's but depending on your gpu/gpu drivers it might not work.

Here is my config

```
vo=gpu-next
ao=wasapi
gpu-api=vulkan
hwdec=auto

scale=ewa_lanczos
cscale=ewa_lanczos
dscale=mitchell 

correct-downscaling=yes
linear-downscaling=yes 
sigmoid-upscaling=yes 

hdr-compute-peak=yes
hdr-peak-percentile=99.995
hdr-contrast-recovery=0.30
allow-delayed-peak-detect=no

dither-depth=auto
deband=yes 

video-sync=display-resample 
interpolation=yes
tscale=oversample
```

~Raza

**Comment by zhouxinghong** [comment]
Thank you very, very much for your help! My American friends! 👍👍👍🎉😜 I'll try it later and see how it works on my pc?
