### ISSUE TITLE
parsing option input-x11-keyboard (option not found)

### ISSUE THREAD

**Issue by DreamMaoMao** [smplayer-dev/smplayer#885]
**Describe the bug**

Many of the parameters generated by smplayer no longer exist on the latest mpv

**To Reproduce**

1.Update mpv to latest version
2.open a video

**Expected behavior**

**Screenshots**
![image](https://github.com/smplayer-dev/smplayer/assets/30348075/a877880f-735c-4730-9bcf-65c4da8c2ad5)

**Your Enviroment**
 - SMPlayer version: 版本: 23.12.0 (修订版 10213)开发版
 - OS: Arch Linux x86_64
 - Multimedia engine you're using with SMPlayer (preferences -> general):MPV

**Logs**

[mpv.log](https://github.com/smplayer-dev/smplayer/files/13926630/mpv.log)

**Comment by smplayer-dev** [comment]
It seems smplayer thinks you're using an old version of mpv, and it's using an old option. 
Try deleting the file `~/.config/smplayer/player_info.ini` and try again.

**Comment by DreamMaoMao** [comment]
it work thanks.
