### ISSUE TITLE
Playlist disappearing

### ISSUE THREAD

**Issue by PeteCrowe** [smplayer-dev/smplayer#895]
**Describe the bug**

Before version 23.12.0 was released, I used to open multiple smplayer instances (Mac Sonoma, terminal run: 

open /Applications/SMPlayer.app -n

When doing so, I would get each tiled instance to display the Playlist and would arrange it so I could view it on another monitor. All was well. I could switch between 4 instances of SMPlayer, and the relevant playlist would be displayed on the other monitor in the same location. This no longer works.

**To Reproduce**
1. Start SMPlayer, choose to display the playlist window. Move playlist to another monitor, restart SMPlayer and see if playlist displays again.

**Expected behavior**

Following the latest 23.12.0 update, I lost the ability to see Playlists in this way. It was even difficult finding THE playlist. It took me 10 minutes of searching and trying different things to uncover it. I can't reproduce what I did because there was so many things I tried.

I've downgraded to 23.6.0 and it is now working again.

**Screenshots**
No screenshot since the playlist window simply disappeared and wouldn't show despite restarts, and trying different setups (making the playlist window dockable and not.

**Your Enviroment**
 - SMPlayer version: **23.12.0**
 - OS: **Mac Sonoma 13.6.1 (22G313).**
 - Multimedia engine you're using with SMPlayer (preferences -> general):
 [ ] MPlayer
 [X] **MPV**

**Logs**
I've uninstalled 23.12.0 and am now using 23.6.0, so I no longer have the capability of logging it.

**Additional context**
-na-

**Comment by smplayer-dev** [comment]
There's been several bugfixes in the playlist in version 23.12 but I can't think of any that could cause that problem.
Is the option "the playlist windows dockable" on or off? Does it make any difference if you change it?

**Comment by PeteCrowe** [comment]
I'm so sorry...I've reinstalled the newest version (without uninstalling
the last), and it seems to work fine now. Perhaps if I uninstalled the
older one it wouldn't? Is there some kind of shared library?

As long as it works, I think I'm fine and the bugfix can be removed.

Thanks for your time and love your software.

Regards,

Peter Crowe
