### ISSUE TITLE
Hi! Friends, color controls don't work for .mp4

### ISSUE THREAD

**Issue by zhouxinghong** [smplayer-dev/smplayer#908]
**Describe the bug**
Hi! Friends, color controls don't work for .mp4
Windows 10
![image](https://github.com/smplayer-dev/smplayer/assets/54253524/f9aa0d2f-8f0b-4ecc-a5be-62d10d6e2491)
![image](https://github.com/smplayer-dev/smplayer/assets/54253524/506bc4c9-2a57-4daa-aa00-e7d90c64624a)
![image](https://github.com/smplayer-dev/smplayer/assets/54253524/08694d7f-fb44-4905-9cc0-ea0e45e1231d)

**Expected behavior**

**Screenshots**
![image](https://github.com/smplayer-dev/smplayer/assets/54253524/f9aa0d2f-8f0b-4ecc-a5be-62d10d6e2491)
![image](https://github.com/smplayer-dev/smplayer/assets/54253524/506bc4c9-2a57-4daa-aa00-e7d90c64624a)
![image](https://github.com/smplayer-dev/smplayer/assets/54253524/08694d7f-fb44-4905-9cc0-ea0e45e1231d)

**Your Enviroment**
 Windows 10
![image](https://github.com/smplayer-dev/smplayer/assets/54253524/f9aa0d2f-8f0b-4ecc-a5be-62d10d6e2491)
![image](https://github.com/smplayer-dev/smplayer/assets/54253524/506bc4c9-2a57-4daa-aa00-e7d90c64624a)
![image](https://github.com/smplayer-dev/smplayer/assets/54253524/08694d7f-fb44-4905-9cc0-ea0e45e1231d)

**Logs**
Reproduce the bug in your computer and attach the smplayer log (menu View) here.

**Additional context**

**Comment by zhouxinghong** [comment]
The same problem exists if the playback engine is switched to MPlayer.

**Comment by Raza-0007** [comment]
If you want those controls to work then uncheck the "software equalizer" box, or if you really do want to use the software based equalizer then set the hardware decoding under `Preferences -> Performance -> Hardware decoding` to "none" or "auto-copy". 

In smplayer all video based filters are applied in the CPU, and if GPU based hardware decoding is enabled, they will not work. If you still want to use hardware decoding then use "auto-copy", because in this mode the decoded frame is sent back to the CPU before being displayed, so smplayer video filters will now work.

~Raza

**Comment by zhouxinghong** [comment]
What's confusing is that the same settings work fine for .webm format videos. So I'm sure this is a bug and need to fix it further.

**Comment by zhouxinghong** [comment]
![image](https://github.com/smplayer-dev/smplayer/assets/54253524/6dbbab68-0907-4c6f-aa41-762a6c65e4a8)Playing .mp4 according to the settings you provided still doesn't work.
But what is confusing is that the same settings work fine in .webm format videos. So I'm sure this is a bug and need to fix it further.

**Comment by zhouxinghong** [comment]
After repeated testing, it is not only ineffective for .mp4 video format, but also ineffective for all traditional video formats such as .avi, .mkv, etc.

**Comment by zhouxinghong** [comment]
> If you want those controls to work then uncheck the "software equalizer" box, or if you really do want to use the software based equalizer then set the hardware decoding under `Preferences -> Performance -> Hardware decoding` to "none" or "auto-copy".
> 
> In smplayer all video based filters are applied in the CPU, and if GPU based hardware decoding is enabled, they will not work. If you still want to use hardware decoding then use "auto-copy", because in this mode the decoded frame is sent back to the CPU before being displayed, so smplayer video filters will now work.
> 
> ~Raza

Thank you very much!🎉
