### ISSUE TITLE
SMplayer references a broken libvulkan resulting in some MKV files not playing - symbol lookup error vkCreateXlibSurfaceKHR

### ISSUE THREAD

**Issue by peddy22** [smplayer-dev/smplayer#917]
**Describe the bug**
I've noticed this bug for a long time. When playing certain MKV video files (I haven't found a pattern), the following mpv error appears: 
```

/usr/bin/mpv --no-quiet --terminal --no-msg-color --input-ipc-server=/tmp/smplayer-mpv-2d1be --msg-level=ffmpeg/demuxer=error --video-rotate=no --no-config --no-fs --hwdec=no --sub-auto=fuzzy --no-input-default-bindings --input-x11-keyboard=no --no-input-cursor --cursor-autohide=no --no-keepaspect --wid=83886097 --monitorpixelaspect=1 --osd-level=1 --osd-scale=1 --sub-ass --embeddedfonts --ass-line-spacing=0 --sub-scale=1.4 --sub-text-shadow-color=#ff000000 --sub-codepage=ISO-8859-1 --vid=1 --sub-pos=100 --volume=100 --cache=auto --screenshot-template=cap_%F_%p_%02n --screenshot-format=jpg --term-playing-msg=MPV_VERSION=${=mpv-version:}
INFO_VIDEO_WIDTH=${=width}
INFO_VIDEO_HEIGHT=${=height}
INFO_VIDEO_ASPECT=${=video-params/aspect}
INFO_VIDEO_FPS=${=container-fps:${=fps}}
INFO_VIDEO_FORMAT=${=video-format}
INFO_VIDEO_CODEC=${=video-format}
INFO_DEMUX_ROTATION=${=track-list/0/demux-rotation}
INFO_AUDIO_FORMAT=${=audio-codec-name}
INFO_AUDIO_CODEC=${=audio-codec-name}
INFO_AUDIO_RATE=${=audio-params/samplerate}
INFO_AUDIO_NCH=${=audio-params/channel-count}
INFO_LENGTH=${=duration:${=length}}
INFO_DEMUXER=${=current-demuxer:${=demuxer}}
INFO_SEEKABLE=${=seekable}
INFO_TITLES=${=disc-titles}
INFO_CHAPTERS=${=chapters}
INFO_TRACKS_COUNT=${=track-list/count}
METADATA_TITLE=${metadata/by-key/title:}
METADATA_ARTIST=${metadata/by-key/artist:}
METADATA_ALBUM=${metadata/by-key/album:}
METADATA_GENRE=${metadata/by-key/genre:}
METADATA_DATE=${metadata/by-key/date:}
METADATA_TRACK=${metadata/by-key/track:}
METADATA_COPYRIGHT=${metadata/by-key/copyright:}
INFO_MEDIA_TITLE=${=media-title:}
INFO_STREAM_PATH=${stream-path}
 --audio-client-name=SMPlayer --term-status-msg=STATUS: ${=time-pos} / ${=duration:${=length:0}} P: ${=pause} B: ${=paused-for-cache} I: ${=core-idle} VB: ${=video-bitrate:0} AB: ${=audio-bitrate:0} /home/user/3. Get To The Cause.mp4

/usr/bin/mpv: symbol lookup error: /usr/bin/mpv: undefined symbol: vkCreateXlibSurfaceKHR

```

The key part being
`/usr/bin/mpv: symbol lookup error: /usr/bin/mpv: undefined symbol: vkCreateXlibSurfaceKHR
`

**To Reproduce**
Open MKV file
mpv immediately crashes

**To Fix**
Make a file in /usr/local/bin/mpv with the following contents
```
#!/bin/sh
export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libvulkan.so.1

exec /usr/bin/mpv "$@"

```
then chmod +x the file to make it executable

Next in smplayer's preferences>general change the multimedia engine to 
`/usr/local/bin/mpv`

Everything works as expected

**Expected behavior**
The video should play 

**Screenshots**

**Your Enviroment**
 - SMPlayer version: Version: 23.12.0 (revision 10207)
 - OS: kubuntu 22.04
 - Multimedia engine you're using with SMPlayer (preferences -> general):
 [ X] MPV

**Logs**
See above

**Additional context**
Thanks to [this person](https://www.reddit.com/r/archlinux/comments/r9nqkf/mpv_symbol_look_up_error/) who showed how to solve a similar problem with Chrome (mpv embedded in chrome?)

Thanks, hope this bug report is helpful

**Comment by smplayer-dev** [comment]
Do you have this problem when trying to open a file from the chrome browser?
It seems to be a problem in chrome.

**Comment by peddy22** [comment]
No, from the kde file browser or directly from the torrent client

Arno

**Comment by smplayer-dev** [comment]
Anyway this seems a problem in mpv, it seems it wasn't compiled correctly. It's something I can't fix.
Try a snap or a flatpak package, those include its own version of mpv, and check if the problem still happens:
https://github.com/smplayer-dev/smplayer/releases/tag/v23.12.0.10229

**Comment by peddy22** [comment]
I tried the AppImage, it works. Thanks for your help.
Arno

**Comment by akontsevich** [comment]
Works perfectly for me, for openSUSE script would be:

```
#!/bin/sh
export LD_PRELOAD=/usr/lib64/libvulkan.so.1

exec /usr/bin/mpv "$@"
```

Strange thing standalone `mpv` works just fine without exporting `libvulkan`, problem only if `smplayer` executes/uses it.
