### ISSUE TITLE
Windows 11 no sound playing .avi and some .mkv files

### ISSUE THREAD

**Issue by iskander959** [smplayer-dev/smplayer#924]
Have bought a mini-PC Beelink SER5 MAX [AMD Ryzen 7 5800H] with windows 11 on board.
Connected it with DAS Terramaster D5-300 with my collection of movies.
installed smplayer-23.12.0-x64
When I play any .avi file it plays no sound, and when I manually select an audio track from file, player says "audio is disabled".
When I play  some of the .mkv files, sometimes it plays sound, sometimes not.
Media Player Classic is playing all of the files with sound.
A have a game-pc with a Windows 10 on, with WIn10 all files playing on SMPlayer well.
Appreciate any help
Thank you!

**Comment by smplayer-dev** [comment]
That's weird. Please send the SMPlayer log (menu View) after playing a file with this problem.

**Comment by iskander959** [comment]
[LogSmPlayerAVI.txt](https://github.com/smplayer-dev/smplayer/files/14628225/LogSmPlayerAVI.txt)
[LogSmPlayerMKV.txt](https://github.com/smplayer-dev/smplayer/files/14628226/LogSmPlayerMKV.txt)

**Comment by smplayer-dev** [comment]
You're forcing the use of the hwac3 codec, I guess it could be causing the problem. Check if it works without it.

**Comment by iskander959** [comment]
This is strange. I can swear, that i do not change any setting, except "make default player" and "launch in fullscreen mode".
Anyway, problem solved by reverting all setting to default.
