### ISSUE TITLE
Force closing after check update

### ISSUE THREAD

**Issue by fegyorgy** [smplayer-dev/smplayer#93]
If I check for updates or search for subtitles online, the SMPlayer force closeing. After clean install too. 21.1.0 64-bit.

**Comment by smplayer-dev** [comment]
I never experienced that problem. Could you test this version?
https://github.com/smplayer-dev/smplayer/releases/tag/v21.1.0.9630

**Comment by fegyorgy** [comment]
Thank you, this version is ok!!
