### ISSUE TITLE
Windows Store version newer than reported available

### ISSUE THREAD

**Issue by mrandreastoth** [smplayer-dev/smplayer#943]
When checking for updates using a Windows Store installed version of SMPlayer, the reported installed version is newer than the available version, as per the following text copy of the dialog.

```
---------------------------
Checking for updates
---------------------------
Congratulations, SMPlayer is up to date.<br><br>Installed version: 23.12.0.10227<br>Available version: 23.12.0.10207
---------------------------
OK   
---------------------------
```

I don't know how the check is performed, but there are two possible options...

1. It checks against a known URL for a specific platform that returns the available version, in which case there needs to be a different URL for the Store version which not only must be maintained on the server-side but must be used by the Store version of MVPlayer.

OR

2. It passes the platform as part of the URL and the server looks up the available version for that platform in which case SMPlayer must include that it is the Store version and the server must maintain data to support such a call.

**Comment by smplayer-dev** [comment]
The version for the Windows Store was created later and it's actually newer than the normal version.

**Comment by mrandreastoth** [comment]
Yes, and it is confusing as an official build should *never* be newer than the official available version. That is why I suggest that two versions be maintained, one for the Windows Store version and one for the standard Windows version possibly using one of the options I suggested above. This would improve the UX.
