### ISSUE TITLE
Version 24.5.0 does not disable screen dimming

### ISSUE THREAD

**Issue by BellavGFH** [smplayer-dev/smplayer#974]
After upgrade, SMPlayer 24.5.0 does not disable screen dimming by power management (laptop on battery)

**To Reproduce**
1. Install/ upgrade SMPlayer v 24.5.0
2. Play video, either in window or full screen.
3. After certain interval, screen brightness will be reduced.
4. Downgrade to SMPlayer 21.10.0 solves the issue, restores expected behaviour

**Expected behavior**
No screen dimming during video playback.

**Your Enviroment**
 - OS: Linux (.deb install)
 - Multimedia engine you're using with SMPlayer (preferences -> general):
MPV

**Comment by smplayer-dev** [comment]
Could you tell me what is the latest version without that problem? (version 21.10 is very old)
https://github.com/smplayer-dev/smplayer/releases

**Comment by BellavGFH** [comment]
I apologise for jumping back so far. It's what my main repo had.
Here is what I found. Versions used are (dpkg -i ) release version here...

21.10.0 --- Starting out, all good
24.5.0 --- Just checking, screen dimming occurs

smplayer_23.12.0 --- All good, no screen dimming
smplayer_23.12.0.10212 --- All good, no screen dimming
smplayer_23.12.0.10213 --- All good, no screen dimming
smplayer_23.12.0.10226 --- All good, no screen dimming
smplayer_23.12.0.10229 --- All good, no screen dimming
++++++++++++++
smplayer_23.12.0.10237 --- Screen dimming
smplayer_23.12.0.10245 --- Screen dimming
++++++++++++++
smplayer_21.10.0 --- All good, no screen dimming

Hope this helps...

**Comment by smplayer-dev** [comment]
Try passing the option --stop-xscreensaver in preferences -> advanced -> mplayer/mpv and see if that fixes it.

**Comment by BellavGFH** [comment]
Yep, that did it, THX!
