### ISSUE TITLE
SMPlayer update on Flathub ?

### ISSUE THREAD

**Issue by repsorp** [smplayer-dev/smplayer#989]
Hi,
is anyone in charge of flatpak updates on flathub?
The last update was 5 months ago with version 23.12.0
https://flathub.org/apps/info.smplayer.SMPlayer

**Comment by smplayer-dev** [comment]
Sorry, I'm afraid I didn't have time to do it yet. Unfortunately there are problems with the latest runtime that I have to solve.
https://github.com/flathub/info.smplayer.SMPlayer/pull/8#issuecomment-1872108365

**Comment by repsorp** [comment]
No problem, don't be sorry
Keep it up

**Comment by smplayer-dev** [comment]
Fixed.

**Comment by repsorp** [comment]
> Fixed.

Cool, thanks 
Some issues though...
forward/backward (10 sec, 1 min, 10 min) shortcuts operate very erratically 
frozen image, sound doesn't match

**Comment by smplayer-dev** [comment]
I think it's fixed now.

**Comment by repsorp** [comment]
great, it's working fine now
Thanks
