### ISSUE TITLE
Unable to locate program input point GetSystemTimePreciseAsFileTime on dynamic link library KERNEL32.dll

### ISSUE THREAD

**Issue by drw2005** [smplayer-dev/smplayer#994]
**Describe the bug**

**Your Enviroment**
 - SMPlayer version：24.5.0
 - OS：Windows 7 x64
 - Multimedia engine you're using with SMPlayer 
 MPV

Unable to locate program input point GetSystemTimePreciseAsFileTime on dynamic link library KERNEL32.dll

Can you please tell me how to solve this problem? Thank you!

**Comment by smplayer-dev** [comment]
Version 24.5.0 includes a mpv version which requires at least Windows 8.
You can still use the 32 bit version of smplayer, which uses an old version of mpv.

**Comment by drw2005** [comment]
OK, you can change it to a 32-bit one.
